import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"";
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")??"";
const DOMAIN="relay.crownthrive.com";
const ROUTE=`mailgun:${DOMAIN}`;
const POLICY_ID="ct.pentamailer.policy.mailgun-delivery-resilience.v1";
const POLICY_VERSION="1.1.0";
const COPY_POLICY_ID="ct.pentamailer.policy.marketer-copy.v1";
const AUTHORITY_REF="ct-founder-directive-pentamail-provider-probation-20260826-v1";
const CONTACT_EMAIL="contact@crownthrive.com";
const COLLAB_CC="supportfw+6003623762e81d3790d346287982e333@inbound.portalmailbox.com";
const FOUNDER_BCC="jones.usmc.kj@gmail.com";
const PUBLIC_ADMIN_EMAILS=new Set([CONTACT_EMAIL]);
const INTERNAL_FROM_LOCAL=new Set(["thivebase","heartbeat","notifications","noreply","pentamail"]);
const MARKETER_FROM_LOCAL=new Set(["outreach","support"]);
type JsonRecord=Record<string,unknown>;
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff"}})}
async function rpc<T=any>(name:string,body:JsonRecord={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:SERVICE_ROLE_KEY,authorization:`Bearer ${SERVICE_ROLE_KEY}`,"content-type":"application/json"},body:JSON.stringify(body)});const t=await r.text();let d:any=t;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(`${name}:${r.status}:${typeof d==="string"?d.slice(0,300):JSON.stringify(d).slice(0,500)}`);return d as T}
async function actor(req:Request){const raw=req.headers.get("authorization")??"";const token=raw.toLowerCase().startsWith("bearer ")?raw.slice(7).trim():"";if(!token)return null;if(token===SERVICE_ROLE_KEY)return{email:"service_role",service:true};const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:ANON_KEY,authorization:`Bearer ${token}`}});if(!r.ok)return null;const u=await r.json();const email=String(u?.email??"").toLowerCase();try{const allowed=PUBLIC_ADMIN_EMAILS.has(email)||await rpc<boolean>("penta_mail_admin_allowed_v1",{p_recipient:email});return allowed?{email,service:false}:null}catch{return null}}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function retryAfterSeconds(v:string){const m=v.match(/enabled\s+in\s+(\d{1,6})\s+seconds?/i);if(!m)return null;const n=Number(m[1]);return Number.isInteger(n)&&n>=1&&n<=86400?n:null}
function authenticatedMailgunProbation(status:number,message:string){if(![401,403,429].includes(status))return null;const n=message.toLowerCase().replace(/\s+/g," ").trim();const retry=retryAfterSeconds(n);if(!(n.includes("account is on probation")||n.includes("account on probation"))||!n.includes("temporarily disabled")||!(n.includes("100 messages / hour")||n.includes("100 messages per hour"))||retry===null)return null;return{retry_after_seconds:retry}}
async function secret(){const v=await rpc("mailgun_relay_adapter_secret");const c=String(v?.credential??"");if(!c)throw new Error("credential_missing");return c}
function cleanName(v:unknown,fallback:string){const s=String(v??fallback).replace(/[<>\r\n]/g,"").trim().slice(0,80);return s||fallback}
async function providerHealth(onProviderCall:()=>void){const credential=await secret();const probe=await rpc("penta_mail_begin_mailgun_readback_v1",{});const probeId=String(probe?.probe_id??"");const probeGeneration=Number(probe?.probe_generation??0);const probeStartedAt=String(probe?.probe_started_at??"");if(!probeId||!Number.isSafeInteger(probeGeneration)||probeGeneration<1||!probeStartedAt)throw new Error("invalid_mailgun_readback_probe_token");const started=Date.now();onProviderCall();const response=await fetch(`https://api.mailgun.net/v3/domains/${DOMAIN}/sending_queues`,{headers:{authorization:`Basic ${btoa(`api:${credential}`)}`},signal:AbortSignal.timeout(15000)});const text=await response.text();let provider:any={};try{provider=text?JSON.parse(text):{}}catch{}const regularDisabled=provider?.regular&&typeof provider.regular==="object"?provider.regular.is_disabled!==false:true;const scheduledDisabled=provider?.scheduled&&typeof provider.scheduled==="object"?provider.scheduled.is_disabled!==false:true;const enabled=response.ok&&!regularDisabled&&!scheduledDisabled;const responseSha=await sha256(`${response.status}\n${text}`);const eventId=`mailgun-sending-queues:${probeId}`;const control=await rpc("penta_mail_record_mailgun_readback_v4",{p_probe_id:probeId,p_probe_generation:probeGeneration,p_readback_event_id:eventId,p_enabled:enabled,p_regular_disabled:regularDisabled,p_scheduled_disabled:scheduledDisabled,p_provider_http_status:response.status,p_response_sha256:responseSha,p_adapter_context:{readback_event_id:eventId,readback_probe_id:probeId,readback_probe_generation:probeGeneration,provider_route_id:ROUTE,domain:DOMAIN,region:"us",api_base:"https://api.mailgun.net",probe_started_at:probeStartedAt,observed_at:new Date().toISOString(),latency_ms:Date.now()-started,provider_call_made:true}});return{ok:response.ok,provider_status:response.status,enabled,regular_disabled:regularDisabled,scheduled_disabled:scheduledDisabled,provider_call_made:true,response_sha256:responseSha,control,raw_secret_exposed:false}}
async function marketerAuthorized(body:any,to:string){const messageType=String(body?.message_type??"").toLowerCase();if(await rpc<boolean>("penta_marketer_suppressed_v1",{p_email:to}))return{authorized:false,reason:"suppressed"};if(messageType==="locticians_claim"){const a=await rpc("penta_marketer_delivery_authorized_v1",{p_message_id:String(body?.message_id??""),p_recipient:to});return{authorized:a?.authorized===true,reason:a?.authorized===true?null:"legacy_delivery_authorization_denied",control:a}}const workId=String(body?.work_id??"");if(!workId)return{authorized:false,reason:"work_id_required"};const allowed=await rpc<boolean>("penta_marketer_external_recipient_allowed_v1",{p_recipient:to,p_work_id:workId});return{authorized:allowed===true,reason:allowed===true?null:"work_recipient_authorization_denied"}}
async function sendProvider(authenticated:any,body:any,scope:"internal"|"marketer"){const to=String(body?.to??"").toLowerCase().trim();const local=String(body?.from_local??(scope==="marketer"?"support":"pentamail")).toLowerCase().trim();const subject=String(body?.subject??"").trim();const messageText=String(body?.text??"").trim();const triggerRef=String(body?.trigger_ref??`mailgun-relay:${local}`).trim();const requestKey=String(body?.request_key??`edge:${crypto.randomUUID()}`).trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(to))return json({ok:false,error:"invalid_recipient",provider_call_made:false},400);if(!subject||subject.length>180||!messageText||messageText.length>60000)return json({ok:false,error:"invalid_message_shape",provider_call_made:false},400);if(!/^[A-Za-z0-9][A-Za-z0-9:._/-]{0,199}$/.test(triggerRef))return json({ok:false,error:"invalid_trigger_ref",provider_call_made:false},400);if(!requestKey||requestKey.length>240)return json({ok:false,error:"invalid_request_key",provider_call_made:false},400);
if(scope==="internal"){if(!INTERNAL_FROM_LOCAL.has(local))return json({ok:false,error:"from_local_not_allowlisted",provider_call_made:false},403);if(!await rpc<boolean>("penta_mail_recipient_allowed_v1",{p_recipient:to}))return json({ok:false,error:"recipient_not_allowlisted",provider_call_made:false},403)}else{if(!MARKETER_FROM_LOCAL.has(local))return json({ok:false,error:"marketer_from_local_not_allowlisted",provider_call_made:false},403);const a=await marketerAuthorized(body,to);if(!a.authorized)return json({ok:false,error:a.reason,authorization:a.control??null,provider_call_made:false},403)}
const reservation=await rpc("penta_mail_reserve_mailgun_rate_v2",{p_request_key:requestKey,p_trigger_ref:triggerRef});if(reservation?.allowed!==true){const reason=String(reservation?.reason??"rate_or_control_denied");const status=["rolling_hour_limit","controlled_release_batch_limit"].includes(reason)?429:reason==="trigger_probation"?423:503;return json({ok:false,error:reason,control:reservation,trigger_ref:triggerRef,provider_call_made:false,raw_secret_exposed:false},status)}
const credential=await secret();const fromName=scope==="marketer"?cleanName(body?.from_name,"CrownThrive"):cleanName(body?.from_name,`CrownThrive ${local}`);const visibleFrom=scope==="marketer"?CONTACT_EMAIL:`${local}@${DOMAIN}`;const form=new FormData();form.set("from",`${fromName} <${visibleFrom}>`);form.set("to",to);form.set("subject",subject);form.set("text",messageText);if(scope==="marketer"){form.set("h:Reply-To",CONTACT_EMAIL);form.set("cc",`${CONTACT_EMAIL}, ${COLLAB_CC}`);form.set("bcc",FOUNDER_BCC);form.set("v:copy_policy",COPY_POLICY_ID)}const messageType=String(body?.message_type??"").toLowerCase();const sendKind=String(body?.send_kind??"").toLowerCase();const listMail=["locticians_claim","sales_outreach","lead_nurture"].includes(messageType)||sendKind==="cold";if(scope==="marketer"&&listMail){form.set("h:List-Unsubscribe",`<mailto:${CONTACT_EMAIL}?subject=OPT%20OUT>`);form.set("h:List-Unsubscribe-Post","List-Unsubscribe=One-Click");form.set("o:tag",messageType==="locticians_claim"?"locticians-claim":"pentamarketer-outreach");if(body?.campaign_ref)form.set("v:campaign_ref",String(body.campaign_ref));if(body?.schedule_id)form.set("v:schedule_id",String(body.schedule_id))}
const payloadSha=await sha256(JSON.stringify({domain:DOMAIN,scope,from_local:local,visible_from:visibleFrom,copy_policy:scope==="marketer"?COPY_POLICY_ID:null,from_name:fromName,recipient:to,subject,text:messageText,trigger_ref:triggerRef,message_type:messageType,work_id:body?.work_id??null}));const attemptId=crypto.randomUUID();const attemptStart=await rpc("penta_mail_start_mailgun_attempt_v1",{p_request_key:requestKey,p_trigger_ref:triggerRef,p_payload_sha256:payloadSha,p_attempt_id:attemptId});if(attemptStart?.allowed!==true)return json({ok:false,error:String(attemptStart?.reason??"provider_attempt_not_authorized"),control:attemptStart,trigger_ref:triggerRef,provider_call_made:false,reconciliation_required:attemptStart?.reconciliation_required===true,raw_secret_exposed:false},503);
const started=Date.now();let response:Response;try{response=await fetch(`https://api.mailgun.net/v3/${DOMAIN}/messages`,{method:"POST",headers:{authorization:`Basic ${btoa(`api:${credential}`)}`},body:form,signal:AbortSignal.timeout(30000)})}catch{const outcomeSha=await sha256(`provider_outcome_unknown|${attemptId}|${payloadSha}`);await rpc("penta_mail_record_mailgun_attempt_outcome_v1",{p_attempt_id:attemptId,p_outcome_state:"ambiguous",p_provider_http_status:null,p_provider_message_id:null,p_response_sha256:outcomeSha,p_details:{reason_code:"provider_outcome_unknown",timeout_ms:30000,scope}});return json({ok:false,error:"provider_outcome_unknown",provider_attempt_id:attemptId,trigger_ref:triggerRef,provider_call_made:true,reconciliation_required:true,response_sha256:outcomeSha,raw_secret_exposed:false},504)}
const responseText=await response.text();let provider:any={};try{provider=responseText?JSON.parse(responseText):{}}catch{provider={message:responseText.slice(0,300)}}const providerMessage=String(provider?.message??"").slice(0,300);const providerId=String(provider?.id??"").slice(0,500)||null;const responseSha=await sha256(`${response.status}\n${responseText}`);const probation=authenticatedMailgunProbation(response.status,providerMessage);let probationControl:any=null;if(probation){probationControl=await rpc("penta_mail_accept_mailgun_probation_v3",{p_provider_event_id:`mailgun-api:${attemptId}`,p_provider_event_sha256:responseSha,p_trigger_ref:triggerRef,p_retry_after_seconds:probation.retry_after_seconds,p_evidence_kind:"authenticated_provider_response",p_authority_ref:AUTHORITY_REF})}await rpc("penta_mail_record_mailgun_attempt_outcome_v1",{p_attempt_id:attemptId,p_outcome_state:probation?"probation_detected":response.ok?"provider_accepted":"definitive_failure",p_provider_http_status:response.status,p_provider_message_id:providerId,p_response_sha256:responseSha,p_details:{reason_code:probation?"mailgun_account_probation_temporarily_disabled":response.ok?"provider_accepted":"provider_rejected",retry_after_seconds:probation?.retry_after_seconds??null,latency_ms:Date.now()-started,scope,message_type:messageType,work_id:body?.work_id??null,copy_policy:scope==="marketer"?COPY_POLICY_ID:null,visible_from:scope==="marketer"?CONTACT_EMAIL:null}});try{await rpc("integration_record_request",{p_service_id:"mailgun_relay",p_operation_key:scope==="marketer"?"messages.send_marketer":"messages.send_internal",p_http_method:"POST",p_path_template:`/v3/${DOMAIN}/messages`,p_http_status:response.status,p_success:response.ok,p_actor:`${authenticated.email}:${local}`,p_latency_ms:Date.now()-started,p_response_sha256:responseSha,p_notes:`transport_owner=PentaMail;scope=${scope};message_type=${messageType||"system"};trigger=${triggerRef};copy_policy=${scope==="marketer"?COPY_POLICY_ID:"none"}`})}catch{}
return json({ok:response.ok,provider_status:response.status,id:providerId,provider_reason_code:probation?"mailgun_account_probation_temporarily_disabled":response.ok?"provider_accepted":"provider_rejected",retry_after_seconds:probation?.retry_after_seconds??null,provider_attempt_id:attemptId,trigger_ref:triggerRef,provider_call_made:true,provider_probation_detected:probation!==null,control:probationControl,response_sha256:responseSha,transport_owner:"PentaMail",copy_policy:scope==="marketer"?COPY_POLICY_ID:null,visible_from:scope==="marketer"?CONTACT_EMAIL:null,raw_secret_exposed:false},response.ok?200:502)}
Deno.serve(async(req:Request)=>{let providerCallMade=false;try{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const authenticated=await actor(req);if(!authenticated)return json({error:"admin_required"},403);const body=await req.json().catch(()=>({}));const action=String(body?.action??"");if(action==="health"){const control=await rpc("penta_mail_provider_status_v1",{p_trigger_ref:null});return json({service:"mailgun-relay-control",version:"1.4.0",stage:"production",domain:DOMAIN,provider_route_id:ROUTE,transport_owner:"PentaMail",send_scope:"internal_allowlist_plus_pentamarketer_governed_external",marketer_visible_from:CONTACT_EMAIL,marketer_copy_policy:COPY_POLICY_ID,policy_id:POLICY_ID,policy_version:POLICY_VERSION,control,raw_secret_exposed:false})}if(action==="provider_health"){return json(await providerHealth(()=>{providerCallMade=true}))}if(action==="send_internal"){providerCallMade=true;return await sendProvider(authenticated,body,"internal")}if(action==="send_marketer"){providerCallMade=true;return await sendProvider(authenticated,body,"marketer")}return json({error:"unknown_action",allowed:["health","provider_health","send_internal","send_marketer"]},400)}catch(error){return json({ok:false,error:error instanceof Error?error.message:"mailgun_relay_error",provider_call_made:providerCallMade,transport_owner:"PentaMail",raw_secret_exposed:false},500)}});
