(()=>{
const PLANS={
 creelpilot:{name:'CreelPilot Pro',price:'$4.99/month',checkout:'https://buy.stripe.com/14A8wO7nu3xo4XU0GzbAs42',entitlement:'creelpilot_pro'},
 lifewright:{name:'LifeWright Pro',price:'$4.99/month',checkout:'https://buy.stripe.com/9B6eVcePWaZQ61YfBtbAt04',entitlement:'lifewright_pro'},
 'zaza-room':{name:'The ZaZa Room Pro',price:'$4.99/month',checkout:'https://buy.stripe.com/9B6dR8ePWaZQaie9d5bAt05',entitlement:'zaza_room_pro'},
 musiqhead:{name:'MusiqHead Pro',price:'$4.99/month',checkout:'https://buy.stripe.com/14A9AS23a6JA3TQ74XbAt06',entitlement:'musiqhead_pro'},
 'melanin-magic-suite':{name:'Melanin Magic Suite Pro',price:'$4.99/month',checkout:'https://buy.stripe.com/7sY8wO0Z67NE3TQ0GzbAt07',entitlement:'melanin_magic_suite_pro'}
};
const read=(k,d=null)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}};
const write=(k,v)=>{localStorage.setItem(k,JSON.stringify(v));return v};
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){let e=document.querySelector('.ct-app-toast');if(!e){e=document.createElement('div');e.className='ct-app-toast';e.setAttribute('role','status');document.body.append(e)}e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
function checkoutReturn(key){const q=new URLSearchParams(location.search),sid=q.get('session_id');if(q.get('upgrade')==='success'&&sid&&/^cs_/.test(sid)){write(`ct:pro:${key}`,{state:'checkout_returned',session_id:sid,local_pro:true,at:new Date().toISOString()});toast('Checkout returned. Local Pro tools are active while account verification reconciles.');q.delete('upgrade');q.delete('session_id');history.replaceState({},'',location.pathname+(q.size?'?'+q.toString():'')+location.hash)}return read(`ct:pro:${key}`,{state:'free',local_pro:false})}
function proState(key){return read(`ct:pro:${key}`,{state:'free',local_pro:false})}
function localPro(key){const s=proState(key);return s.verified===true||s.local_pro===true}
function requirePro(key,fn){if(localPro(key)){fn?.();return true}toast(`${PLANS[key]?.name||'Pro'} is required for this tool.`);document.querySelector('[data-pro-home]')?.scrollIntoView({behavior:'smooth',block:'center'});return false}
function exportJSON(filename,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function share(title,text,url=location.href){try{if(navigator.share)return await navigator.share({title,text,url});if(navigator.clipboard){await navigator.clipboard.writeText(`${text}\n${url}`);toast('Copied to clipboard.')}}catch{}}
function haptic(ms=18){try{navigator.vibrate?.(ms)}catch{}}
function dock(items){document.querySelector('.ct-dock')?.remove();const n=document.createElement('nav');n.className='ct-dock';n.setAttribute('aria-label','App navigation');n.innerHTML=items.map(x=>`<a href="${safe(x.href)}"><b>${safe(x.icon||'•')}</b>${safe(x.label)}</a>`).join('');document.body.append(n)}
function providerHit(raw,id){return raw.toLowerCase().includes(String(id).toLowerCase())}
async function osRead(){const jobs=['/api/health','/api/operations','/api/catalog'].map(u=>fetch(u,{headers:{Accept:'application/json'}}).then(async r=>({ok:r.ok,url:u,data:r.ok?await r.json():null})).catch(()=>({ok:false,url:u,data:null})));const out=await Promise.all(jobs);return {health:out[0],operations:out[1],catalog:out[2]}}
async function mountOS(target,providers=[]){const root=typeof target==='string'?document.querySelector(target):target;if(!root)return;root.innerHTML='<div class="ct-app-panel"><div class="ct-app-row"><div><h3>CrownThrive OS</h3><div class="ct-app-muted">Reading sanitized same-origin provider rails.</div></div><span class="ct-status pending">Checking</span></div><div class="ct-os-grid" data-os-grid></div></div>';const status=root.querySelector('.ct-status'),grid=root.querySelector('[data-os-grid]');const r=await osRead();const h=r.health.data||{},raw=JSON.stringify(r.operations.data||{}),catalog=JSON.stringify(r.catalog.data||{});const operational=r.health.ok&&(String(h.status||h.state||'').toLowerCase().includes('operational')||String(h.status||'').toLowerCase().includes('ok'));status.textContent=operational?'OS operational':'OS partial';status.className='ct-status '+(operational?'ok':'pending');const nodes=[['Control plane',r.health.ok?'Connected':'Unavailable'],...providers.map(p=>[p,providerHit(raw,p)?'Available':'Not advertised']),['Catalog',r.catalog.ok?(catalog.length>80?'Connected':'Connected'):'Unavailable']];grid.innerHTML=nodes.map(([a,b])=>`<div class="ct-os-node"><span>${safe(a)}</span><b>${safe(b)}</b></div>`).join('')}
function mountPro(target,key,features=[],copy=''){const root=typeof target==='string'?document.querySelector(target):target;if(!root||!PLANS[key])return;const plan=PLANS[key],state=checkoutReturn(key),isLocal=localPro(key),box=document.createElement('div');box.className='ct-pro-box';box.dataset.proHome='1';const status=state.verified===true?'Verified Pro':state.local_pro?'Local Pro active · account verification pending':'Free';box.innerHTML=`<div class="ct-app-row"><div><span class="ct-status ${state.verified===true?'ok':state.local_pro?'pending':''}">${safe(status)}</span><h3>${safe(plan.name)}</h3><div class="ct-price">$4.99 <small>/ month</small></div></div><a class="ct-buy" href="${safe(plan.checkout)}">${isLocal?'Manage / verify Pro':'Upgrade to Pro'}</a></div><p class="ct-app-muted">${safe(copy)}</p><div class="ct-pro-grid">${features.map(f=>`<div class="ct-pro-node"><span>PRO TOOL</span><b>${safe(f)}</b></div>`).join('')}</div><div class="ct-app-muted" style="margin-top:10px">A checkout return enables local-only premium tools immediately. Cloud/account authority remains fail-closed until the provider entitlement rail verifies the subscription.</div>`;root.append(box)}
function install(slug,button){let deferred=null;const b=typeof button==='string'?document.querySelector(button):button;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;if(b)b.hidden=false});if(b)b.onclick=async()=>{if(!deferred)return toast('Use the browser install command if the native prompt is unavailable.');deferred.prompt();await deferred.userChoice;deferred=null;b.hidden=true};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register(`/${slug}/sw.js`,{scope:`/${slug}`}).catch(()=>{}))}
function persistStorage(){try{navigator.storage?.persist?.()}catch{}}
window.CrownApp={plans:PLANS,read,write,safe,toast,checkoutReturn,proState,localPro,requirePro,exportJSON,share,haptic,dock,osRead,mountOS,mountPro,install,persistStorage};
})();