(()=>{
const PLANS={creelpilot:{name:'CreelPilot Pro',checkout:'https://buy.stripe.com/14A8wO7nu3xo4XU0GzbAs42',entitlement:'creelpilot_pro'},lifewright:{name:'LifeWright Pro',checkout:'https://buy.stripe.com/9B6eVcePWaZQ61YfBtbAt04',entitlement:'lifewright_pro'},'zaza-room':{name:'The ZaZa Room Pro',checkout:'https://buy.stripe.com/9B6dR8ePWaZQaie9d5bAt05',entitlement:'zaza_room_pro'},musiqhead:{name:'MusiqHead Pro',checkout:'https://buy.stripe.com/14A9AS23a6JA3TQ74XbAt06',entitlement:'musiqhead_pro'},'melanin-magic-suite':{name:'Melanin Magic Suite Pro',checkout:'https://buy.stripe.com/7sY8wO0Z67NE3TQ0GzbAt07',entitlement:'melanin_magic_suite_pro'}};
const TTL=72*60*60*1000,read=(k,d=null)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}},write=(k,v)=>{localStorage.setItem(k,JSON.stringify(v));return v},safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){let e=document.querySelector('.ct-app-toast');if(!e){e=document.createElement('div');e.className='ct-app-toast';e.setAttribute('role','status');document.body.append(e)}e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
const stateKey=k=>`ct:pro:${k}`;
function captureCheckout(key){const q=new URLSearchParams(location.search),sid=q.get('session_id');if(q.get('upgrade')==='success'&&/^cs_live_[A-Za-z0-9_]+$/.test(sid||'')){write(stateKey(key),{state:'verification_pending',session_id:sid,verified:false,received_at:new Date().toISOString()});if(key==='creelpilot'){localStorage.setItem('creelpilot:proSession',sid);sessionStorage.setItem('creelpilot:checkout-session',sid)}q.delete('upgrade');q.delete('session_id');history.replaceState({},'',location.pathname+(q.size?'?'+q.toString():'')+location.hash);return sid}return read(stateKey(key),{})?.session_id||''}
function validCached(s){if(!s?.verified||!s?.verified_at)return false;const age=Date.now()-Date.parse(s.verified_at);if(!Number.isFinite(age)||age>TTL)return false;if(s.expires_at&&Date.parse(s.expires_at)<=Date.now())return false;return true}
function localPro(key){if(validCached(read(stateKey(key),null)))return true;if(key==='creelpilot'){const legacy=read('creelpilot:proState',null);if(legacy?.verified&&legacy?.checked_at&&Date.now()-Date.parse(legacy.checked_at)<TTL)return true}return false}
async function verifyPro(key){const prior=read(stateKey(key),{}),sid=prior.session_id||captureCheckout(key);if(!sid)return validCached(prior)?prior:{state:'free',verified:false};try{const r=await fetch(`/api/app-entitlement?app=${encodeURIComponent(key)}&session_id=${encodeURIComponent(sid)}`,{cache:'no-store',headers:{Accept:'application/json'}}),j=await r.json();if(r.ok&&j.verified===true){const next={state:'pro_active',verified:true,session_id:sid,entitlement:j.entitlement||PLANS[key]?.entitlement,expires_at:j.expires_at||null,verified_at:new Date().toISOString()};write(stateKey(key),next);dispatchEvent(new CustomEvent('ct:prochange',{detail:{app:key,state:next}}));return next}const next={state:j.state||'pro_not_active',verified:false,session_id:sid,checked_at:new Date().toISOString()};write(stateKey(key),next);return next}catch{if(validCached(prior))return prior;return {...prior,state:'verification_unavailable',verified:false}}
function requirePro(key,fn){if(localPro(key)){fn?.();return true}toast(`${PLANS[key]?.name||'Pro'} requires a verified subscription.`);document.querySelector('[data-pro-home]')?.scrollIntoView({behavior:'smooth',block:'center'});return false}
function exportJSON(filename,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function share(title,text,url=location.href){try{if(navigator.share)return await navigator.share({title,text,url});if(navigator.clipboard){await navigator.clipboard.writeText(`${text}\n${url}`);toast('Copied to clipboard.')}}catch{}}
function haptic(ms=18){try{navigator.vibrate?.(ms)}catch{}}
function dock(items){document.querySelector('.ct-dock')?.remove();const n=document.createElement('nav');n.className='ct-dock';n.setAttribute('aria-label','App navigation');n.innerHTML=items.map(x=>`<a href="${safe(x.href)}"><b>${safe(x.icon||'•')}</b>${safe(x.label)}</a>`).join('');document.body.append(n)}
function providerHit(raw,id){return raw.toLowerCase().includes(String(id).toLowerCase())}
async function osRead(){const jobs=['/api/health','/api/operations','/api/catalog'].map(u=>fetch(u,{headers:{Accept:'application/json'}}).then(async r=>({ok:r.ok,data:r.ok?await r.json():null})).catch(()=>({ok:false,data:null})));const [health,operations,catalog]=await Promise.all(jobs);return {health,operations,catalog}}
async function mountOS(target,providers=[]){const root=typeof target==='string'?document.querySelector(target):target;if(!root)return;root.innerHTML='<div class="ct-app-panel"><div class="ct-app-row"><div><h3>CrownThrive OS</h3><div class="ct-app-muted">Sanitized same-origin operating rails.</div></div><span class="ct-status pending">Checking</span></div><div class="ct-os-grid" data-os-grid></div></div>';const status=root.querySelector('.ct-status'),grid=root.querySelector('[data-os-grid]'),r=await osRead(),h=r.health.data||{},raw=JSON.stringify(r.operations.data||{});const operational=r.health.ok&&['operational','ok','healthy'].some(x=>String(h.status||h.state||'').toLowerCase().includes(x));status.textContent=operational?'OS operational':'OS partial';status.className='ct-status '+(operational?'ok':'pending');const nodes=[['Control plane',r.health.ok?'Connected':'Unavailable'],...providers.map(p=>[p,providerHit(raw,p)?'Available':'Not advertised']),['Catalog',r.catalog.ok?'Connected':'Unavailable']];grid.innerHTML=nodes.map(([a,b])=>`<div class="ct-os-node"><span>${safe(a)}</span><b>${safe(b)}</b></div>`).join('')}
async function mountPro(target,key,features=[],copy=''){const root=typeof target==='string'?document.querySelector(target):target;if(!root||!PLANS[key])return;captureCheckout(key);const s=await verifyPro(key),verified=validCached(s),plan=PLANS[key],box=document.createElement('div');box.className='ct-pro-box';box.dataset.proHome='1';const status=verified?'Verified Pro':s.state==='verification_unavailable'?'Verification unavailable':s.state==='verification_pending'?'Verifying':'Free';box.innerHTML=`<div class="ct-app-row"><div><span class="ct-status ${verified?'ok':s.state==='verification_pending'?'pending':''}">${safe(status)}</span><h3>${safe(plan.name)}</h3><div class="ct-price">$4.99 <small>/ month</small></div></div><a class="ct-buy" href="${safe(plan.checkout)}">${verified?'Reverify / manage Pro':'Upgrade to Pro'}</a></div><p class="ct-app-muted">${safe(copy)}</p><div class="ct-pro-grid">${features.map(f=>`<div class="ct-pro-node"><span>PRO TOOL</span><b>${safe(f)}</b></div>`).join('')}</div><div class="ct-app-muted" style="margin-top:10px">Checkout does not grant access by itself. Pro activates only after live Stripe verification through CrownThrive’s server entitlement rail; verified state may be cached for up to 72 hours for offline continuity.</div>`;root.append(box)}
function install(slug,button){let deferred=null;const b=typeof button==='string'?document.querySelector(button):button;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;if(b)b.hidden=false});if(b)b.onclick=async()=>{if(!deferred)return toast('Use the browser install command if the native prompt is unavailable.');deferred.prompt();await deferred.userChoice;deferred=null;b.hidden=true};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register(`/${slug}/sw.js`,{scope:`/${slug}`}).catch(()=>{}))}
function persistStorage(){try{navigator.storage?.persist?.()}catch{}}
window.CrownApp={plans:PLANS,read,write,safe,toast,captureCheckout,verifyPro,localPro,requirePro,exportJSON,share,haptic,dock,osRead,mountOS,mountPro,install,persistStorage};
})();