(()=>{
  const body=document.body;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const css=document.createElement('link');css.rel='stylesheet';css.href='/brand-worlds-app.css';document.head.append(css);
  function insert(section){const f=document.querySelector('footer.foot');if(f)f.before(section);else document.querySelector('main')?.append(section)}
  function switcher(){
    const n=document.createElement('nav');n.className='world-switcher';n.setAttribute('aria-label','CrownThrive experience switcher');n.innerHTML='<a href="/zaza-room">ZaZa</a><a href="/musiqhead">MusiqHead</a><a href="/melanin-magic-suite">MM Suite</a><a href="/creelpilot">CreelPilot</a><a href="/lifewright">LifeWright</a>';body.append(n)
  }
  function reveal(){
    if(!('IntersectionObserver'in window))return;const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('world-visible');io.unobserve(x.target)}}),{threshold:.08});document.querySelectorAll('.card,.band,.sectionhead,.products').forEach(x=>{x.classList.add('world-reveal');io.observe(x)})
  }
  function zaza(){
    const s=document.createElement('section');s.className='section world-console';s.id='room-console';s.innerHTML='<div class="sectionhead"><div><div class="kicker">Room console</div><h2>Set the room before the room sets you.</h2></div><span class="signal">Local session state</span></div><div class="console-grid"><div class="control-card"><small>MOOD SELECTOR</small><div class="choice-row" id="roomModes"><button data-room="slow">Slow Burn</button><button data-room="story">Smoke & Story</button><button data-room="midnight">Midnight Cuts</button><button data-room="write">Writing Room</button></div><div class="console-read"><span id="roomLabel">Slow Burn</span><b id="roomCopy">Low light. Warm low-end. No rush.</b></div></div><div class="control-card"><small>30-MINUTE ROOM</small><div class="session-clock" id="roomClock">30:00</div><p>Use the timer as a boundary: listen, write, talk, or sit still. No feed. No scroll requirement.</p><button class="button" id="roomTimer">Start room</button></div></div>';
    insert(s);
    const modes={slow:['Slow Burn','Low light. Warm low-end. No rush.'],story:['Smoke & Story','Conversation forward. Spoken word, memory and grown humor.'],midnight:['Midnight Cuts','Experimental records, visual mood and unreleased-world energy.'],write:['Writing Room','Clear the noise. One idea, one page, one record at a time.']};
    document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{const [l,c]=modes[b.dataset.room];document.querySelector('#roomLabel').textContent=l;document.querySelector('#roomCopy').textContent=c;body.dataset.room=b.dataset.room;document.querySelectorAll('[data-room]').forEach(x=>x.classList.toggle('active',x===b));localStorage.setItem('zaza:room',b.dataset.room)});
    const saved=localStorage.getItem('zaza:room')||'slow';document.querySelector(`[data-room="${saved}"]`)?.click();
    let timer=null,end=Number(localStorage.getItem('zaza:timerEnd')||0);const clock=document.querySelector('#roomClock'),btn=document.querySelector('#roomTimer');
    const draw=()=>{const active=end>Date.now();let left=active?Math.max(0,Math.ceil((end-Date.now())/1000)):1800;clock.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;btn.textContent=active?'End room':'Start room';if(!active&&timer){clearInterval(timer);timer=null;localStorage.removeItem('zaza:timerEnd')}};
    btn.onclick=()=>{if(end>Date.now()){end=0;localStorage.removeItem('zaza:timerEnd')}else{end=Date.now()+30*60*1000;localStorage.setItem('zaza:timerEnd',String(end))}if(!timer&&end>Date.now())timer=setInterval(draw,1000);draw()};if(end>Date.now())timer=setInterval(draw,1000);draw();
  }
  function musiq(){
    const s=document.createElement('section');s.className='section world-console';s.id='rights-console';s.innerHTML='<div class="sectionhead"><div><div class="kicker">Rights pulse</div><h2>Is this record ready to move?</h2></div><span class="signal">Local checklist · no upload</span></div><div class="console-grid"><div class="control-card"><small>RELEASE READINESS</small><div class="check-stack" id="rightsChecks"><label><input type="checkbox" data-right="title"> Title + version locked</label><label><input type="checkbox" data-right="contributors"> Contributors + splits captured</label><label><input type="checkbox" data-right="source"> Master/source provenance recorded</label><label><input type="checkbox" data-right="art"> Artwork + metadata ready</label><label><input type="checkbox" data-right="state"> Release state explicitly assigned</label><label><input type="checkbox" data-right="license"> Licensing assets / stems classified</label></div></div><div class="control-card score-card"><small>CATALOG READINESS</small><div class="score-ring"><b id="rightsScore">0%</b></div><p id="rightsCopy">Start with ownership and provenance. Release pressure comes after the paper trail.</p><a class="button" href="mailto:contact@crownthrive.com?subject=MusiqHead%20Rights%20Inquiry">Rights inquiry</a></div></div>';
    insert(s);const key='musiqhead:rights-readiness';let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{};
    const checks=[...s.querySelectorAll('[data-right]')];checks.forEach(c=>{c.checked=!!saved[c.dataset.right];c.onchange=()=>{saved[c.dataset.right]=c.checked;localStorage.setItem(key,JSON.stringify(saved));score()}});
    function score(){const n=checks.filter(x=>x.checked).length,p=Math.round(n/checks.length*100);s.querySelector('#rightsScore').textContent=p+'%';s.querySelector('#rightsCopy').textContent=p===100?'Release-ready checklist complete. Provider/distribution state still must be verified separately.':p>=67?'The record is moving, but the missing rights fields are still real debt.':'Start with ownership and provenance. Release pressure comes after the paper trail.';s.style.setProperty('--score',p)}score();
  }
  function magic(){
    const s=document.createElement('section');s.className='section world-console';s.id='suite-console';s.innerHTML='<div class="sectionhead"><div><div class="kicker">Suite operator lab</div><h2>Turn appointments into an operating lane.</h2></div><span class="signal">Planning estimate</span></div><div class="console-grid"><div class="control-card"><small>WEEKLY MODEL</small><div class="calc-grid"><label>Clients / week<input id="mmClients" type="number" min="0" step="1" value="20"></label><label>Average service ticket<input id="mmTicket" type="number" min="0" step="1" value="75"></label><label>Retail attach rate %<input id="mmAttach" type="number" min="0" max="100" step="1" value="20"></label><label>Average retail ticket<input id="mmRetail" type="number" min="0" step="1" value="25"></label></div><div class="estimate"><span>Illustrative weekly gross</span><b id="mmGross">$0</b><small>Service + simple retail attachment estimate. This is not a profit forecast.</small></div></div><div class="control-card"><small>OPERATOR READINESS</small><div class="check-stack" id="suiteChecks"><label><input type="checkbox" data-suite="care"> Service + care routine defined</label><label><input type="checkbox" data-suite="stock"> Wholesale/backbar plan</label><label><input type="checkbox" data-suite="discover"> Discovery profile / local visibility</label><label><input type="checkbox" data-suite="reorder"> Retail + reorder path</label><label><input type="checkbox" data-suite="loyalty"> Loyalty / retention rail</label><label><input type="checkbox" data-suite="ops"> Suite operating discipline</label></div><div class="meter"><i id="suiteMeter"></i></div><b class="meter-copy" id="suiteScore">0 / 6 ready</b></div></div>';
    insert(s);const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);const fields=['mmClients','mmTicket','mmAttach','mmRetail'];
    function calc(){const c=+s.querySelector('#mmClients').value||0,t=+s.querySelector('#mmTicket').value||0,a=Math.min(100,+s.querySelector('#mmAttach').value||0)/100,r=+s.querySelector('#mmRetail').value||0;s.querySelector('#mmGross').textContent=money(c*t+c*a*r)}fields.forEach(id=>s.querySelector('#'+id).oninput=calc);calc();
    const key='mm-suite:readiness';let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{};const checks=[...s.querySelectorAll('[data-suite]')];checks.forEach(c=>{c.checked=!!saved[c.dataset.suite];c.onchange=()=>{saved[c.dataset.suite]=c.checked;localStorage.setItem(key,JSON.stringify(saved));draw()}});function draw(){const n=checks.filter(x=>x.checked).length;s.querySelector('#suiteScore').textContent=`${n} / ${checks.length} ready`;s.querySelector('#suiteMeter').style.width=(n/checks.length*100)+'%'}draw();
  }
  switcher();if(body.classList.contains('zaza'))zaza();if(body.classList.contains('musiq'))musiq();if(body.classList.contains('magic'))magic();reveal();
})();
