(() => {
  'use strict';
  const ENDPOINT = '/api/command-suite';
  const CONTRACT = 'ct.command.operating-suite.v1';
  const SOURCE = /^[a-z][a-z0-9-]{0,63}$/;
  const state = { overview:null, source:'all-catalog-records', category:'All', sourceQuery:'', query:'', page:null, cursor:null, history:[], session:null, request:null, stale:false, pending:false, lastAttempt:0, generation:0 };
  const ui = {};
  const nf = new Intl.NumberFormat('en-US');
  let staleTimer = null;
  let activeController = null;
  const node = (tag,text='',className='') => { const e=document.createElement(tag);if(text!=='')e.textContent=String(text);if(className)e.className=className;return e; };
  const human = value => String(value ?? 'Not supplied').replaceAll('_',' ');
  const when = value => typeof value==='string' && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString('en-US',{timeZone:'America/New_York',timeZoneName:'short'}) : 'Not observed';
  const display = value => value==null ? 'Not supplied' : typeof value==='boolean' ? (value?'Yes':'No') : Array.isArray(value) ? value.join(', ') : String(value);
  const badge = (text) => {const e=node('span',human(text),'suite-status');if(/FAILED|ERROR|HOLD|MISSING|DRIFT|DEGRADED|STALE|QUARANTIN/i.test(String(text)))e.dataset.tone='bad';return e;};
  function button(text,fn){const b=node('button',text);b.type='button';b.addEventListener('click',fn);return b;}
  function safeLink(value){try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||[...u.searchParams.keys()].some(k=>/token|secret|key|signature|auth|credential/i.test(k)))return null;return u.href;}catch{return null;}}
  function link(href,text){const a=node('a',text);a.href=href;if(href.startsWith('https:')){a.target='_blank';a.rel='noopener noreferrer';}return a;}
  function source(){return state.overview?.sources?.find(s=>s.source===state.source);}
  function saveView(){try{localStorage.setItem('ct-command-suite-view',JSON.stringify({source:state.source,category:state.category}));}catch{}}
  async function api(op,params={},post=false){
    const query=new URLSearchParams({op,...params});
    const response=await fetch(post?ENDPOINT:`${ENDPOINT}?${query}`,{method:post?'POST':'GET',credentials:'same-origin',cache:'no-store',redirect:'error',signal:activeController?.signal,
      headers:post?{'Content-Type':'application/json','X-Command-Suite':'1',Accept:'application/json'}:{Accept:'application/json'},...(post?{body:JSON.stringify({op,...params})}:{})});
    let data;try{data=await response.json();}catch{throw new Error('Source response unavailable');}
    if(!response.ok){if(response.status===401||response.status===403){state.session=null;renderSession();}throw new Error(data.error || `Request ${response.status}`);}
    return data;
  }
  function choose(key){if(!SOURCE.test(key))return;state.source=key;state.cursor=null;state.history=[];state.page=null;state.query='';ui.search.value='';state.generation++;saveView();renderSources();renderPage();loadPage();}
  function renderSources(){
    ui.categories.replaceChildren();
    for(const category of ['All',...new Set(['Catalog','Books','Commerce','Drive / Docs',...(state.overview?.sources||[]).map(s=>s.category)].filter(c=>(state.overview?.sources||[]).some(s=>s.category===c)))]){const b=button(category,()=>{state.category=category;saveView();renderSources();});b.setAttribute('aria-pressed',String(state.category===category));ui.categories.append(b);}
    ui.sources.replaceChildren();
    for(const s of state.overview?.sources||[]){if(state.category!=='All'&&s.category!==state.category)continue;if(state.sourceQuery && !`${s.source} ${s.label} ${s.category}`.toLowerCase().includes(state.sourceQuery.toLowerCase()))continue;
      const b=button('',()=>choose(s.source));b.setAttribute('aria-current',String(s.source===state.source));b.append(node('strong',s.label),node('small',`${s.binding_state} · ${s.records_estimate==null?'Count not estimated':`≈ ${nf.format(s.records_estimate)} registry rows`}`));ui.sources.append(b);}
  }
  function renderSession(){
    ui.session.replaceChildren();
    if(state.session?.can_read){ui.session.append(node('p',`Existing operator grant verified. ${state.session.can_manage?'Source-reconciliation requests enabled.':'Read access only.'}`),button('Sign out',async()=>{try{await api('logout',{},true);}finally{state.session=null;state.page=null;state.request=null;ui.request.replaceChildren();renderSession();renderPage();}}));}
    else{
      const form=node('form','','suite-login');const email=node('input');email.type='email';email.autocomplete='username';email.required=true;email.maxLength=254;const password=node('input');password.type='password';password.autocomplete='current-password';password.required=true;password.maxLength=4096;
      for(const [title,input]of[['Operator email',email],['Existing account password',password]]){const label=node('label',title);label.append(input);form.append(label);}
      const submit=node('button','Sign in securely');submit.type='submit';form.append(submit,node('p','Uses the existing ThriveBase account and PentaBrain operator grant. No account or permission is created. Passwords and session tokens are not stored in browser storage.','suite-note'));
      form.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;try{await api('login',{email:email.value,password:password.value},true);password.value='';state.session=await api('session');renderSession();loadPage();}catch(err){password.value='';ui.notice.textContent=`Sign-in not completed: ${human(err.message)}. No new permission was granted.`;}finally{submit.disabled=false;}});ui.session.append(form);
    }
    ui.inspect.disabled=!state.session?.can_manage;ui.reconcile.disabled=!state.session?.can_manage;ui.export.disabled=!state.session?.can_read;
  }
  function rowName(row,s){return row.canonical_name||row.display_name||row.product_title||row.title||row.source_title||row.candidate_name||row.service_name||row.public_name||row.name||row.label||row.filename||row.folder_name||row.jobname||row.object_name||row.operation_key||row.event_type||row[s.keys[0]]||'Record';}
  function sourceHref(key,query=''){if(!SOURCE.test(key))return null;const params=new URLSearchParams({source:key});if(query)params.set('q',String(query).slice(0,120));return `/estate?${params}#operating-suite`;}
  function requestedView(search){const params=new URLSearchParams(search);const key=params.get('source');return key&&SOURCE.test(key)?{source:key,query:(params.get('q')||'').slice(0,120)}:null;}
  function rowTimestamp(row){return row.source_observed_at||row.updated_at||row.refreshed_at||row.observed_at||row.verified_at||row.modified_at||row.last_seen_at||row.created_at;}
  function rowPrice(row){if(row.pricing_display)return String(row.pricing_display);const amount=row.price_amount_minor??row.price_cents??row.unit_amount??row.usd_cents??row.amount_cents??row.amount_minor;const currency=String(row.currency||'').toUpperCase();if(amount==null||amount===''||!Number.isSafeInteger(Number(amount))||Number(amount)<0)return 'Not recorded';if(currency!=='USD')return `${amount} minor units${currency?` ${currency}`:''} · verify currency`;const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(amount)/100);return `${money}${row.billing_model?` · ${human(row.billing_model)}`:''}`;}
  function fieldLink(key,value,row,s){
    const urls=['canonical_url','drive_ref','github_ref','web_view_link','public_url','publication_url','reader_url','preview_url','checkout_url','stripe_payment_link_url','drive_file_url','row_url','source_page_url','site_product_page','origin_url','official_docs_url'];
    if(urls.includes(key))return safeLink(value);
    const files=['drive_file_id','drive_master_file_id','package_drive_file_id','source_drive_file_id'];const folders=['drive_root_folder_id','drive_folder_id','drive_estate_folder_id'];
    if(typeof value==='string'&&/^[A-Za-z0-9_-]{15,150}$/.test(value)){
      if(folders.includes(key))return `https://drive.google.com/drive/folders/${value}`;
      if(files.includes(key))return `https://drive.google.com/file/d/${value}/view`;
      if(key==='source_id'&&(row.source_system==='google_drive'||s.source==='drive-source-census'))return row.source_kind==='folder'?`https://drive.google.com/drive/folders/${value}`:`https://drive.google.com/file/d/${value}/view`;
    }
    return null;
  }
  function attentionText(row){return [rowState(row),row.rights_state,row.fulfillment_state,row.checkout_state,row.readiness_state,row.custody_state,row.provider_state,row.tax_state,row.docs_state,row.route_state].filter(Boolean).join(' ');}
  function rowState(row){return row.health_state??row.runtime_state??row.activation_state??row.lifecycle_state??row.readiness_state??row.release_state??row.public_state??row.commerce_state??row.build_state??row.package_state??row.fulfillment_state??row.checkout_state??row.provider_readback_state??row.provider_state??row.state??row.status??row.binding_state??row.certification_state??row.classification??(row.active==null?'Not supplied':row.active?'Registered active':'Registered inactive');}
  function details(row){
    const s=source();ui.dialog.replaceChildren();const head=node('div','','suite-top');head.append(node('h3',rowName(row,s)),button('Close',()=>ui.dialog.close()));ui.dialog.append(head,node('p',`${s.label}. These are current registry fields; provider verification is separate.`,'suite-note'));
    const dl=node('dl','','suite-detail-list');for(const key of [...new Set([...s.keys,...s.fields])]){if(!(key in row))continue;dl.append(node('dt',human(key)));const dd=node('dd');const value=row[key];const href=fieldLink(key,value,row,s);
      dd.append(href?link(href,display(value)):node('span',display(value)));dl.append(dd);}
    ui.dialog.append(dl);ui.dialog.showModal();
  }
  function renderPage(){
    const s=source();ui.records.replaceChildren();ui.pages.replaceChildren();if(!s){ui.title.textContent='Reading source bindings';return;}
    ui.title.textContent=s.label;ui.boundary.textContent=`Registry steward: ${s.owner}. ${s.pagination==='PRIMARY_KEY_KEYSET'?'Primary-key pagination.':s.pagination==='UNIQUE_CATALOG_OID_KEYSET'?'Unique catalog-identity pagination.':'View pagination; a stable snapshot is not claimed.'} Source reads do not trigger a provider probe.${s.source==='all-catalog-records'?' Cross-source records include distinct editions, files and overlapping provider mappings; this is not a unique-product count.':''}`;
    ui.search.placeholder=s.source==='all-catalog-records'?'Search all connected books, products, commerce and Drive sources':'Search this entire source (literal text)';
    if(!state.session?.can_read){ui.records.append(node('div','Sign in to inspect private inventory, Drive references, action receipts, and operational records. The source coverage above is public-safe.','suite-empty'));return;}
    if(!state.page){ui.records.append(node('div','Reading selected source…','suite-empty'));return;}
    const p=state.page;if(p.status!=='OBSERVED'){ui.records.append(node('div',`${human(p.status)}. Missing fields: ${(p.source?.missing_fields||[]).join(', ')||'Not supplied'}. No healthy state is inferred.`,'suite-alert'));return;}
    ui.records.append(node('p',`${state.stale?'STALE — last known page. ':''}${p.returned} rows on this page · read ${when(p.observed_at)} · ${human(p.search_scope)}. Record timestamps below are distinct from the retrieval time.`,'suite-note'));
    const rows=(p.rows||[]).filter(row=>!ui.attention.checked||/FAILED|ERROR|HOLD|MISSING|DRIFT|DEGRADED|PENDING|QUARANTIN|UNAVAILABLE|NOT_RECORDED/i.test(attentionText(row)));
    if(!rows.length)ui.records.append(node('div',ui.attention.checked?'No flagged rows on this page. This is not a claim about other pages.':'No records returned for this source and search.','suite-empty'));
    else{const wrap=node('div','','suite-table-wrap');wrap.tabIndex=0;wrap.setAttribute('aria-label','Scrollable registry records');const table=node('table','','suite-table');table.append(node('caption','Current registry metadata; select Inspect for every exposed field and evidence link.'));const head=node('thead');const tr=node('tr');for(const t of ['Identity / name','Recorded state','Price / offer','Source updated','Details']){const th=node('th',t);th.scope='col';tr.append(th);}head.append(tr);table.append(head);const body=node('tbody');
      for(const row of rows){const tr=node('tr');const id=node('td');id.append(node('strong',rowName(row,s)),node('div',s.keys.map(k=>display(row[k])).join(' / '),'suite-note'));if(row.source_label)id.append(node('div',row.source_label,'suite-note'));const status=node('td');status.append(badge(rowState(row)));if(row.rights_state&&row.rights_state!==rowState(row))status.append(node('div',`Rights: ${human(row.rights_state)}`,'suite-note'));if(row.fulfillment_state&&row.fulfillment_state!==rowState(row))status.append(node('div',`Fulfillment: ${human(row.fulfillment_state)}`,'suite-note'));tr.append(id,status,node('td',rowPrice(row)),node('td',when(rowTimestamp(row))));const cell=node('td');cell.append(button('Inspect',()=>details(row)));const native=safeLink(row.drive_ref||row.web_view_link||row.drive_file_url||row.public_url||row.reader_url);if(native)cell.append(link(native,'Open source'));if(row.source_key&&SOURCE.test(row.source_key)&&row.source_key!==s.source)cell.append(link(sourceHref(row.source_key,row.sku||''),'Source registry'));tr.append(cell);body.append(tr);}table.append(body);wrap.append(table);ui.records.append(wrap);}
    const back=button('Previous',()=>{state.cursor=state.history.pop()??null;loadPage();});back.disabled=!state.history.length;const next=button('Next page',()=>{state.history.push(state.cursor);state.cursor=p.next_cursor;loadPage();});next.disabled=!p.next_cursor;const first=button('Newest / first page',()=>{state.cursor=null;state.history=[];loadPage();});ui.pages.append(back,next,first);
  }
  async function loadPage(){if(!state.session?.can_read||!source())return;const generation=++state.generation;const selected=state.source;try{const p=await api('records',{source:selected,q:state.query,limit:'50',...(state.cursor?{cursor:JSON.stringify(state.cursor)}:{})});if(generation!==state.generation||selected!==state.source)return;state.page=p;state.stale=false;renderPage();}catch(e){if(generation!==state.generation)return;state.stale=true;ui.notice.textContent=`Selected-source readback failed: ${human(e.message)}. No successful readback is claimed.`;renderPage();}}
  async function request(action){if(!state.session?.can_manage)return;const s=source();if(!s)return;const wording=`Request ${action} of ${s.label}? This checks its schema and one metadata row, records evidence through the existing CHLOM worker, and does not change a provider, publish, send mail, charge, delete, or reopen a hold.`;if(!window.confirm(wording))return;
    ui.inspect.disabled=true;ui.reconcile.disabled=true;try{const result=await api('request',{source:s.source,action,request_id:crypto.randomUUID()},true);state.request=result.request_id;ui.request.replaceChildren(node('strong',`Request ${result.request_id}`),node('p',`${human(result.state)} — request recorded; execution is not yet confirmed.`));await readRequest();}catch(e){ui.request.textContent=`Request not confirmed: ${human(e.message)}. Refresh before trying again.`;}finally{renderSession();}}
  async function readRequest(){if(!state.request||!state.session?.can_read)return;try{const r=await api('request',{id:state.request});ui.request.replaceChildren(node('strong',`Request ${r.request_id || state.request}`),node('p',`${human(r.state)} · ${human(r.execution_effect)} · updated ${when(r.updated_at)}`));if(r.error_code)ui.request.append(node('p',human(r.error_code)));if(r.dail_event_id)ui.request.append(node('p',`DAIL receipt: ${r.dail_event_id}`));}catch(e){ui.request.append(node('p',`Status not refreshed: ${human(e.message)}`));}}
  function renderOverview(){const d=state.overview;if(!d)return;ui.status.textContent=state.stale?'STALE / last known':'Registry readback observed';ui.status.dataset.tone=state.stale?'bad':'neutral';ui.stamp.textContent=`Retrieved ${when(d.observed_at)}. Existing Command refresh cadence; not instantaneous streaming. Estimates are not exact counts.`;
    const misses=d.sources.filter(s=>s.binding_state!=='BOUND');ui.coverage.textContent=`${d.coverage.mapped_sources} explicit source adapters; ${misses.length} missing or changed source contracts. ${d.coverage.other_candidate_relations} additional catalog candidates remain discoverable under Coverage / Discovery—not automatically exposed as record APIs. Sources overlap; row estimates must not be added together.`;renderSources();}
  async function refresh(force=false){if(state.pending||(!force&&(document.hidden||Date.now()-state.lastAttempt<25000)))return;state.pending=true;state.lastAttempt=Date.now();activeController=new AbortController();const deadline=setTimeout(()=>activeController?.abort(),11000);
    try{const d=await api('overview');if(d.schema!==CONTRACT||!Array.isArray(d.sources))throw new Error('Contract mismatch');const age=Date.now()-Date.parse(d.observed_at);if(!Number.isFinite(age)||age< -60000||age>90000)throw new Error('Stale source response');state.overview=d;state.stale=false;ui.notice.textContent='';renderOverview();if(!state.session){try{state.session=await api('session');}catch{state.session=null;}renderSession();}if(!source())state.source=d.sources[0]?.source||'identities';await loadPage();await readRequest();clearTimeout(staleTimer);staleTimer=setTimeout(()=>{state.stale=true;renderOverview();renderPage();},90000);
    }catch(e){state.stale=true;ui.status.textContent='Source readback unavailable';ui.status.dataset.tone='bad';ui.notice.textContent=`No current suite readback: ${human(e.message)}. Existing Command panels remain available.`;if(state.overview)renderOverview();renderPage();}finally{clearTimeout(deadline);activeController=null;state.pending=false;}}
  function mount(){
    const estate=document.querySelector('[data-page="estate"]');if(!estate)return false;
    const old=node('details','','suite-legacy');old.append(node('summary','Earlier bounded estate snapshot — historical reference, not the live operating inventory'));while(estate.firstChild)old.append(estate.firstChild);estate.append(old);
    const panel=node('article','','panel command-suite');panel.id='operating-suite';panel.dataset.commandSuite='1.1.0';panel.tabIndex=-1;estate.prepend(panel);ui.root=panel;
    const top=node('div','','suite-top'),title=node('div');title.append(node('p','CrownThrive · Founder operating suite','suite-kicker'),node('h2','The whole operating picture'));
    ui.status=badge('Reading registry');top.append(title,ui.status);panel.append(top);ui.stamp=node('p','No snapshot received.','suite-stamp');ui.coverage=node('p','','suite-note');ui.notice=node('p','','suite-alert');ui.notice.setAttribute('role','status');ui.notice.setAttribute('aria-live','polite');panel.append(ui.stamp,ui.coverage,ui.notice);
    ui.session=node('div','','suite-session');panel.append(ui.session);const catalogLinks=node('div','','suite-tools');catalogLinks.setAttribute('aria-label','Catalog quick access');for(const[key,title]of[['all-catalog-records','All products & commerce'],['storefront-library','Book library'],['drive-source-census','Drive files & editions']])catalogLinks.append(link(sourceHref(key),title));panel.append(catalogLinks);ui.categories=node('div','','suite-categories');ui.categories.setAttribute('aria-label','Operating workspaces');panel.append(ui.categories);
    const layout=node('div','','suite-layout'),aside=node('aside');const srcsearch=node('input','','suite-source-search');srcsearch.type='search';srcsearch.placeholder='Find a registry, product lane, or system';srcsearch.setAttribute('aria-label','Find a source');srcsearch.addEventListener('input',()=>{state.sourceQuery=srcsearch.value;renderSources();});ui.sources=node('div','','suite-sources');aside.append(srcsearch,ui.sources);
    const main=node('div','','suite-main');ui.title=node('h3','Reading source bindings');ui.boundary=node('p','','suite-source-boundary');main.append(ui.title,ui.boundary);const tools=node('form','','suite-tools');ui.search=node('input');ui.search.type='search';ui.search.maxLength=120;ui.search.placeholder='Search this entire source (literal text)';ui.search.setAttribute('aria-label','Search selected source');const search=node('button','Search');search.type='submit';tools.append(ui.search,search);tools.addEventListener('submit',e=>{e.preventDefault();state.query=ui.search.value;state.cursor=null;state.history=[];loadPage();});main.append(tools);
    const actions=node('div','','suite-tools');ui.inspect=button('Request inspection',()=>request('inspect'));ui.reconcile=button('Reconcile source metadata',()=>request('reconcile'));ui.export=button('Export current page',()=>{if(!state.page||!state.session?.can_read)return;const blob=new Blob([JSON.stringify({...state.page,exported_at:new Date().toISOString(),stale:state.stale,export_scope:'CURRENT_PAGE_ONLY'},null,2)],{type:'application/json'});const href=URL.createObjectURL(blob),a=link(href,'');a.download=`command-${state.source}-page.json`;a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);});ui.attention=node('input');ui.attention.type='checkbox';ui.attention.addEventListener('change',renderPage);const flag=node('label','Flagged rows on this page ');flag.prepend(ui.attention);actions.append(ui.inspect,ui.reconcile,ui.export,flag);main.append(actions,node('p','Management actions here reconcile source metadata only. Native provider changes, content edits, sending, publishing, money movement, rights grants, and hold overrides remain with their verified owner adapters.','suite-note'));
    ui.request=node('div','','suite-request');ui.request.setAttribute('aria-live','polite');ui.records=node('div');ui.pages=node('div','','suite-pages');main.append(ui.request,ui.records,ui.pages);layout.append(aside,main);panel.append(layout);ui.dialog=node('dialog','','suite-dialog command-suite');ui.dialog.addEventListener('click',e=>{if(e.target===ui.dialog)ui.dialog.close();});panel.append(ui.dialog);
    const nav=document.querySelector('#nav');if(nav&&!nav.querySelector('[data-command-suite-link]')){const a=link('/estate#operating-suite','Operating suite');a.dataset.commandSuiteLink='';nav.append(a);}
    const shortcuts={overview:'Full operating inventory and attention',dail:'Cursor, every DAIL system, rails and archive',pentas:'All Penta identities, agents and factories',mail:'PentaMailer route holds and readback',infrastructure:'Services, adapters, jobs and fabrics',commerce:'All product, book and commerce records',integrations:'All adapters, plugins, API and MCP records',evidence:'Drive artifacts, reconciliation and source receipts'};
    for(const[page,text]of Object.entries(shortcuts)){const parent=document.querySelector(`[data-page="${page}"]`);if(!parent)continue;const box=node('div','','suite-shortcut');box.append(node('strong',text),link(page==='commerce'?sourceHref('all-catalog-records'):page==='evidence'?sourceHref('drive-source-census'):'/estate#operating-suite','Open operating suite →'));parent.prepend(box);}
    try{const saved=JSON.parse(localStorage.getItem('ct-command-suite-view')||'{}');if(SOURCE.test(saved.source||''))state.source=saved.source;if(typeof saved.category==='string')state.category=saved.category;}catch{}
    const requested=requestedView(location.search);if(requested){state.source=requested.source;state.category='All';state.query=requested.query;ui.search.value=requested.query;}
    renderSession();renderPage();if(location.hash==='#operating-suite')requestAnimationFrame(()=>panel.scrollIntoView());return true;
  }
  function init(){try{if(!mount())return;const observer=new MutationObserver(()=>refresh());const fresh=document.querySelector('#fresh');if(fresh)observer.observe(fresh,{childList:true,subtree:true,characterData:true});document.querySelector('#refresh')?.addEventListener('click',()=>refresh(true));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});window.addEventListener('pagehide',()=>{observer.disconnect();activeController?.abort();clearTimeout(staleTimer);});window.addEventListener('pageshow',e=>{if(e.persisted){if(fresh)observer.observe(fresh,{childList:true,subtree:true,characterData:true});refresh(true);}});refresh(true);}catch{document.documentElement.dataset.commandSuiteState='UNAVAILABLE';}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
