import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const script=readFileSync(new URL('../command-suite.js',import.meta.url),'utf8');
const cut="  if(document.readyState==='loading')";
assert.equal(script.split(cut).length,2);
const harness=script.slice(0,script.indexOf(cut))+"globalThis.helpers={rowName,rowState,rowTimestamp,rowPrice,fieldLink,safeLink,sourceHref,requestedView,attentionText};})();";
const sandbox={Intl,URL,URLSearchParams};vm.createContext(sandbox);vm.runInContext(harness,sandbox);const h=sandbox.helpers;
const s={keys:['id'],source:'stripe-products'};
test('Stripe title is not replaced by opaque ID',()=>assert.equal(h.rowName({id:'prod_x',name:'Business Vault'},s),'Business Vault'));
test('source inventory title is visible',()=>assert.equal(h.rowName({source_title:'The Moon Knows Our Names'},s),'The Moon Knows Our Names'));
test('canonical title precedence stays intact',()=>assert.equal(h.rowName({canonical_name:'Canon',name:'Provider'},s),'Canon'));
test('publication and commerce states remain visible',()=>{assert.equal(h.rowState({release_state:'PUBLISHED'}),'PUBLISHED');assert.equal(h.rowState({commerce_state:'PAYMENT_PENDING'}),'PAYMENT_PENDING');});
test('rights warning is not hidden by a published state',()=>assert.match(h.attentionText({state:'PUBLISHED',rights_state:'RIGHTS_HOLD'}),/RIGHTS_HOLD/));
test('provider timestamp remains distinct from view fetch',()=>assert.equal(h.rowTimestamp({source_observed_at:'2026-09-01',updated_at:'2026-09-17'}),'2026-09-01'));
test('USD minor units format correctly',()=>assert.equal(h.rowPrice({price_amount_minor:'125000',currency:'usd'}),'$1,250.00'));
test('currency missing is not invented',()=>assert.equal(h.rowPrice({price_cents:1000}),'1000 minor units · verify currency'));
test('zero-decimal and other currencies are not incorrectly divided',()=>assert.equal(h.rowPrice({amount_minor:300,currency:'jpy'}),'300 minor units JPY · verify currency'));
test('missing invalid and unsafe amounts are not presented as free',()=>{for(const amount of [null,'',NaN,-1,'no',1.2,Number.MAX_SAFE_INTEGER+1])assert.equal(h.rowPrice({price_amount_minor:amount,currency:'usd'}),'Not recorded');});
test('explicit pricing display is respected',()=>assert.equal(h.rowPrice({pricing_display:'$147 every three months',amount_minor:14700,currency:'usd'}),'$147 every three months'));
test('no key or token URL is exposed as clickable',()=>{for(const u of ['https://example.org/?X-Amz-Signature=x','https://example.org/?token=x','https://u:p@example.org/','javascript:alert(1)','data:text/html,x'])assert.equal(h.safeLink(u),null);});
test('normal checkout links stay inspectable',()=>assert.equal(h.fieldLink('checkout_url','https://buy.stripe.com/normal',{},s),'https://buy.stripe.com/normal'));
test('Drive file metadata links to the correct provider record',()=>assert.equal(h.fieldLink('source_id','1abcdefghijklmno',{source_system:'google_drive',source_kind:'file'},s),'https://drive.google.com/file/d/1abcdefghijklmno/view'));
test('Drive folders do not become file links',()=>assert.equal(h.fieldLink('source_id','1abcdefghijklmno',{source_system:'google_drive',source_kind:'folder'},s),'https://drive.google.com/drive/folders/1abcdefghijklmno'));
test('arbitrary provider IDs are not misidentified as Drive IDs',()=>assert.equal(h.fieldLink('provider_object_id','1abcdefghijklmno',{},s),null));
test('unknown field does not become an execution link',()=>assert.equal(h.fieldLink('description','https://example.org/',{},s),null));
test('deep-link query is bounded and encoded',()=>{const href=h.sourceHref('all-catalog-records','A & B');assert.equal(href,'/estate?source=all-catalog-records&q=A+%26+B#operating-suite');assert.equal(h.sourceHref('../secrets'),null);});
test('URL cannot inject a source identifier',()=>assert.equal(h.requestedView('?source=../secret'),null));
test('URL search length remains bounded',()=>assert.equal(h.requestedView('?source=book-works&q='+'x'.repeat(200)).query.length,120));
test('no new polling or HTML injection introduced',()=>{assert.doesNotMatch(script,/setInterval\(|\.innerHTML\s*=/);assert.match(script,/credentials:'same-origin'/);assert.match(script,/export_scope:'CURRENT_PAGE_ONLY'/);});
