const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const BUY_URL='https://buy.stripe.com/14A8wO7nu3xo4XU0GzbAs42';
let wx={temp:68,wind:6,code:1,sunrise:'6:42 AM',source:'demo'},coords=null,deferredInstall=null;
const WMO={0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Overcast',45:'Foggy',48:'Foggy',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',80:'Showers',95:'Thunderstorms'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2100)}
function clock(iso){if(!iso)return'—';return new Date(iso).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function km(a,b,c,d){const R=6371,p=x=>x*Math.PI/180,dy=p(c-a),dx=p(d-b),q=Math.sin(dy/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(dx/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function renderWx(){$('#heroTemp').textContent=wx.temp+'°';$('#heroWind').textContent=wx.wind+' mph';$('#heroSunrise').textContent=wx.sunrise;$('#heroCondition').textContent=`${WMO[wx.code]||'Mixed conditions'} · ${wx.source==='local'?'local read':'demo read'}`;$('#heroWindow').textContent=wx.wind<=12?'Good':'Watch wind'}
function mapURL(lat,lon){const d=.09;return `https://www.openstreetmap.org/export/embed.html?bbox=${lon-d}%2C${lat-d}%2C${lon+d}%2C${lat+d}&layer=mapnik&marker=${lat}%2C${lon}`}
function osmDirections(lat,lon){return `https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=${coords.lat}%2C${coords.lon}%3B${lat}%2C${lon}`}
async function getPlace(lat,lon){try{const u=`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lon}&zoom=10&addressdetails=1&email=contact%40crownthrive.com`;const r=await fetch(u);if(!r.ok)throw 0;const j=await r.json();return j.address?.city||j.address?.town||j.address?.village||j.address?.county||j.display_name?.split(',')[0]||'Local area'}catch{return'Local area'}}
async function getNearby(lat,lon){const q=`[out:json][timeout:18];(nwr(around:30000,${lat},${lon})["shop"~"fishing|sports|outdoor|hardware"];nwr(around:30000,${lat},${lon})["leisure"="marina"];nwr(around:30000,${lat},${lon})["amenity"~"boat_rental|fuel"];nwr(around:30000,${lat},${lon})["tourism"="camp_site"];);out center tags;`;const u='https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q);const r=await fetch(u);if(!r.ok)throw new Error('nearby');const j=await r.json();return (j.elements||[]).map(x=>{const la=x.lat??x.center?.lat,lo=x.lon??x.center?.lon,t=x.tags||{};return {name:t.name||t.brand||'Local service',kind:t.shop||t.leisure||t.amenity||t.tourism||'service',lat:la,lon:lo,addr:[t['addr:housenumber'],t['addr:street'],t['addr:city']].filter(Boolean).join(' '),dist:(la&&lo)?km(lat,lon,la,lo):999}}).filter(x=>x.lat&&x.lon).sort((a,b)=>a.dist-b.dist).slice(0,16)}
async function getUSGS(lat,lon){try{const d=.20,bbox=[lon-d,lat-d,lon+d,lat+d].join(',');const u=`https://api.waterdata.usgs.gov/ogcapi/v0/collections/latest-continuous/items?f=json&bbox=${bbox}&parameter_code=00060&limit=12`;const r=await fetch(u);if(!r.ok)throw 0;const j=await r.json(),f=(j.features||[]).find(x=>Number.isFinite(+x.properties?.value));if(!f)return'No nearby flow gauge';const p=f.properties;return `${Number(p.value).toLocaleString()} ${p.unit_of_measure||''}`.trim()}catch{return'Water data unavailable'}}
function renderNearby(items){$('#storeCount').textContent=`${items.length} nearby`;const root=$('#nearbyList');root.innerHTML='';if(!items.length){root.innerHTML='<div class="empty">No mapped tackle/outdoor services were returned nearby. Coverage varies by area.</div>';return}items.forEach(x=>{const e=document.createElement('div');e.className='nearbyitem';const c=document.createElement('div'),b=document.createElement('b'),s=document.createElement('span'),a=document.createElement('a');b.textContent=x.name;s.textContent=`${x.kind.replaceAll('_',' ')} · ${x.dist.toFixed(1)} km${x.addr?' · '+x.addr:''}`;a.textContent='Route';a.href=osmDirections(x.lat,x.lon);a.target='_blank';a.rel='noopener';c.append(b,s);e.append(c,a);root.append(e)})}
async function loadLocal(lat,lon){coords={lat,lon};$('#mapFrame').src=mapURL(lat,lon);$('#mapEmpty').classList.add('hide');$('#locText').textContent='Loading field intelligence…';const weatherURL=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,wind_speed_10m,weather_code&daily=sunrise&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto&forecast_days=1`;const jobs=[fetch(weatherURL).then(r=>r.json()),getPlace(lat,lon),getNearby(lat,lon),getUSGS(lat,lon)];const [w,place,nearby,water]=await Promise.allSettled(jobs);if(w.status==='fulfilled'&&w.value.current){wx={temp:Math.round(w.value.current.temperature_2m),wind:Math.round(w.value.current.wind_speed_10m),code:w.value.current.weather_code,sunrise:clock(w.value.daily?.sunrise?.[0]),source:'local'};renderWx()}$('#placeName').textContent=place.status==='fulfilled'?place.value:'Local area';$('#waterRead').textContent=water.status==='fulfilled'?water.value:'Unavailable';renderNearby(nearby.status==='fulfilled'?nearby.value:[]);$('#locDot').classList.add('on');$('#locText').textContent='Local field intelligence connected';toast('Map, local stores and field conditions loaded.')}
function useLocation(){if(!navigator.geolocation)return toast('Location is not available in this browser.');$('#locText').textContent='Requesting location…';navigator.geolocation.getCurrentPosition(p=>loadLocal(p.coords.latitude,p.coords.longitude).catch(()=>toast('Local data is temporarily unavailable.')),()=>{$('#locText').textContent='Location not shared · demo stays active';toast('Location was not shared.')},{timeout:10000,enableHighAccuracy:false})}
function tactic(species,water){let base={'Largemouth bass':['spinnerbait + soft plastic','start shallow on edges, then work shade and structure'],'Crappie':['small jig + slip float','work vertical cover and transition depth slowly'],'Catfish':['fresh cut bait + circle hook','set on channel edge or current seam and give the spot time'],'Trout':['small spinner + natural presentation','work seams, shade and oxygenated water with a quiet approach'],'Striped bass':['swimbait + search presentation','find bait first and cover water before settling'],'Anything biting':['confidence bait + simple backup','fish visible structure first and let the first bite set the pattern']}[species]||['confidence bait','fish the highest-percentage cover first'];if(water.includes('Coastal'))base=['search bait + natural backup','use tide/current context and protect a conservative return window'];return base}
function buildPlan(){let sp=$('#species').value,water=$('#water').value,h=+$('#hours').value,pace=$('#pace').value,[bait,approach]=tactic(sp,water),score=74;if(wx.wind>=4&&wx.wind<=11)score+=8;if(wx.temp>=58&&wx.temp<=82)score+=7;if(wx.wind>17)score-=15;if([61,63,65,95].includes(wx.code))score-=14;score=Math.max(42,Math.min(94,score));$('#scoreNum').textContent=score;$('#scoreTitle').textContent=score>=84?'Strong fishing window':score>=70?'Good fishing window':'Fishable — keep it flexible';$('#scoreReason').textContent=`${wx.temp}° and ${wx.wind} mph wind. ${approach}.`;$('#planChips').innerHTML=[sp,water,`${h} hr window`,bait,pace].map(x=>`<span class="chip">${esc(x)}</span>`).join('');let now=new Date(),add=m=>new Date(now.getTime()+m*60000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),end=h*60,steps=[[0,'Pack + safety check',`Take ${bait}. Confirm license, access, warnings, water, charged phone and return plan.`],[25,'First water',`${approach.charAt(0).toUpperCase()+approach.slice(1)}. Give the pattern enough time to mean something.`],[Math.min(85,Math.round(end*.3)),'Pattern check','Log the first meaningful bite or miss. Change one variable at a time.'],[Math.round(end*.62),'Second window',pace==='explore'?'Move to one new piece of water; keep the productive pattern as your control.':'Make one deliberate location or depth adjustment, not a full reset.'],[Math.max(60,end-35),'Wrap clean','Log the best catch, replace used tackle and keep a calm return margin.']];$('#timeline').innerHTML=steps.map(s=>`<div class="step"><time>${add(s[0])}</time><div><b>${esc(s[1])}</b><span>${esc(s[2])}</span></div></div>`).join('');$('#plan').classList.add('show');localStorage.setItem('creelpilot:lastPlan',JSON.stringify({sp,water,h,pace,wx,at:new Date().toISOString()}));toast('Fishing day built.')}
function data(k,d=[]){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function renderGear(){let a=data('creelpilot:gear');$('#gearList').innerHTML=a.length?a.map((x,i)=>`<div class="item"><div><b>${esc(x)}</b><span>In my tackle box</span></div><button data-delgear="${i}" aria-label="Remove">×</button></div>`).join(''):'<div class="empty">Your box starts here. Add the gear you actually carry.</div>';$$('[data-delgear]').forEach(b=>b.onclick=()=>{a.splice(+b.dataset.delgear,1);save('creelpilot:gear',a);renderGear()})}
function addGear(v){v=(v||$('#gearInput').value).trim();if(!v)return;let a=data('creelpilot:gear');a.unshift(v);save('creelpilot:gear',a);$('#gearInput').value='';renderGear();toast('Added to the tackle box.')}
function renderCatch(){let a=data('creelpilot:catches');$('#catchList').innerHTML=a.length?a.slice(0,8).map((x,i)=>`<div class="item"><div><b>${esc(x.species)}${x.size?' · '+esc(x.size):''}</b><span>${esc(x.note||'Logged catch')} · ${esc(x.date)}</span></div><button data-delcatch="${i}" aria-label="Remove">×</button></div>`).join(''):'<div class="empty">No catches logged yet.</div>';$$('[data-delcatch]').forEach(b=>b.onclick=()=>{a.splice(+b.dataset.delcatch,1);save('creelpilot:catches',a);renderCatch()})}
function addCatch(){let species=$('#catchSpecies').value.trim();if(!species)return toast('Add the species first.');let a=data('creelpilot:catches');a.unshift({species,size:$('#catchSize').value.trim(),note:$('#catchNote').value.trim(),date:new Date().toLocaleDateString()});save('creelpilot:catches',a);['#catchSpecies','#catchSize','#catchNote'].forEach(x=>$(x).value='');renderCatch();toast('Catch logged.')}
const denKeys=['fridge','garage','game','grill','locker','reset'];
function renderDen(k){const a=data(`creelpilot:den:${k}`),root=$(`#${k}List`);root.innerHTML=a.map((x,i)=>`<button class="den-tag" data-denrm="${k}:${i}" title="Tap to remove">${esc(x)}</button>`).join('');root.querySelectorAll('[data-denrm]').forEach(b=>b.onclick=()=>{const [key,idx]=b.dataset.denrm.split(':');let list=data(`creelpilot:den:${key}`);list.splice(+idx,1);save(`creelpilot:den:${key}`,list);renderDen(key)})}
function addDen(k){const inp=$(`#${k}Input`),v=inp.value.trim();if(!v)return;let a=data(`creelpilot:den:${k}`);a.unshift(v);save(`creelpilot:den:${k}`,a);inp.value='';renderDen(k);toast('Den inventory updated.')}
function toggleEscape(){document.body.classList.toggle('escape-on');let on=document.body.classList.contains('escape-on');$('#escapeBtn').textContent=on?'Leave escape mode':'Turn on escape mode';$('#escapeTop').textContent=on?'Exit escape':'Escape mode';if(on)window.scrollTo({top:$('#field').offsetTop-70,behavior:'smooth'})}
function checkoutState(){const q=new URLSearchParams(location.search);if(q.get('upgrade')==='success'){sessionStorage.setItem('creelpilot:checkout-returned','1');$('#proState').textContent='Checkout returned · verification required';toast('Checkout completed. Pro cloud features unlock only after verified subscription status.');history.replaceState({},'',location.pathname+'#pro')}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').hidden=false});
$('#installBtn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').hidden=true};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/creelpilot/sw.js').catch(()=>{}));
$('#locBtn').onclick=$('#locHero').onclick=useLocation;$('#nearbyBtn').onclick=()=>coords?loadLocal(coords.lat,coords.lon):useLocation();$('#planBtn').onclick=buildPlan;$('#gearAdd').onclick=()=>addGear();$('#gearInput').addEventListener('keydown',e=>{if(e.key==='Enter')addGear()});$$('[data-gear]').forEach(b=>b.onclick=()=>addGear(b.dataset.gear));$('#catchAdd').onclick=addCatch;$('#escapeBtn').onclick=$('#escapeTop').onclick=toggleEscape;$$('[data-addden]').forEach(b=>b.onclick=()=>addDen(b.dataset.addden));$('#proBuy').href=BUY_URL;renderWx();renderGear();renderCatch();denKeys.forEach(renderDen);checkoutState();