import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.5";

const DB=Deno.env.get("SUPABASE_DB_URL")!;
const sql=postgres(DB,{max:3,prepare:false});
const SLUG="penta-wire-mesh";
const BASE=`https://tzajnzshmtzjenqulehq.supabase.co/functions/v1/${SLUG}`;
const VERSION="2.0.0";
const FABRICS=["PentaMesh","PentaFabric","PentaFactory","PentaCertify","PentaStatus","PentaPolice"];
const RESOLVER="https://tzajnzshmtzjenqulehq.supabase.co/functions/v1/chlom-public-resolver";
const SANDBOX="https://tzajnzshmtzjenqulehq.supabase.co/functions/v1/crownthrive-io-api-sandbox";
const PENTABEATA="https://tzajnzshmtzjenqulehq.supabase.co/functions/v1/pentabeata";
const FRAMEWORK_FACTORY="https://tzajnzshmtzjenqulehq.supabase.co/functions/v1/framework-factory-v2";
const PUBLIC_ID=/^ctid_[0-9a-f]{32}$/;
const LINK_ID=/^sandbox-link-[0-9]{3}$/;
const enc=new TextEncoder();
const hex=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
const sha=async(s:string)=>hex(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(s))));
function tail(url:URL){const p=url.pathname.split("/").filter(Boolean),i=p.indexOf(SLUG);return i>=0?p.slice(i+1):p}
function clamp(url:URL,key="limit",d=100,max=200){const raw=url.searchParams.get(key);if(raw===null)return d;const n=Number(raw);return Number.isSafeInteger(n)&&n>=1?Math.min(n,max):d}
function headers(type="application/json; charset=utf-8",cache="public,max-age=30,stale-while-revalidate=120"){return new Headers({"content-type":type,"cache-control":cache,"x-content-type-options":"nosniff","referrer-policy":"no-referrer","permissions-policy":"camera=(), microphone=(), geolocation=(), payment=()","x-frame-options":"DENY","access-control-allow-origin":"*","access-control-allow-methods":"GET,HEAD,OPTIONS","access-control-allow-headers":"accept,content-type,if-none-match,cache-control","access-control-expose-headers":"etag,x-crownthrive-content-sha256,x-crownthrive-mesh-node,x-crownthrive-api-version,x-crownthrive-authority-effect","x-crownthrive-mesh-node":"PentaWire","x-crownthrive-api-version":VERSION,"x-crownthrive-authority-effect":"none"})}
async function respond(req:Request,payload:unknown,status=200,cache?:string){const body=JSON.stringify(payload),digest=await sha(body),h=headers("application/json; charset=utf-8",cache);h.set("etag",`\"sha256:${digest}\"`);h.set("x-crownthrive-content-sha256",digest);return new Response(req.method==="HEAD"?null:body,{status,headers:h})}
function authClass(auth:string,publicSafe:boolean){if(publicSafe)return "public_read";if(/service_role|jwt|token|secret|oauth|oidc|api key|x-public-id/i.test(auth))return "credentialed_or_internal";return "provider_specific"}
async function serviceRows(n:number){return await sql`select s.service_id,s.display_name,s.integration_state,s.credential_state,s.write_gate,b.binding_state,b.gap_state,b.public_read_safe,b.mesh_api_url,b.direct_tool_count,b.enabled_tool_count,b.closed_input_tool_count,b.last_probe_state,b.last_http_status,b.last_response_sha256,b.last_observed_at,case when b.public_read_safe then s.base_url else null end as public_base_url,case when b.public_read_safe then s.docs_url else null end as public_docs_url,s.auth_scheme,ra.adapter_kind,ra.exact_contract,ra.allowed_operations,ra.state as adapter_state from integration_control.services s join integration_control.penta_wire_service_bindings_v1 b on b.service_id=s.service_id left join integration_control.penta_wire_read_adapters_v1 ra on ra.service_id=s.service_id order by s.service_id limit ${n}`}
async function serviceRow(id:string){const r=await sql`select s.service_id,s.display_name,s.integration_state,s.credential_state,s.write_gate,b.binding_state,b.gap_state,b.public_read_safe,b.mesh_api_url,b.direct_tool_count,b.enabled_tool_count,b.closed_input_tool_count,b.last_probe_state,b.last_http_status,b.last_response_sha256,b.last_observed_at,case when b.public_read_safe then s.base_url else null end as public_base_url,case when b.public_read_safe then s.docs_url else null end as public_docs_url,s.auth_scheme,ra.adapter_kind,ra.exact_contract,ra.allowed_operations,ra.state as adapter_state from integration_control.services s join integration_control.penta_wire_service_bindings_v1 b on b.service_id=s.service_id left join integration_control.penta_wire_read_adapters_v1 ra on ra.service_id=s.service_id where s.service_id=${id} limit 1`;return r[0]??null}
function clean(x:any){if(!x)return null;const {auth_scheme,...rest}=x;return {...rest,auth_class:authClass(String(auth_scheme??""),Boolean(x.public_read_safe)),authority_effect:"none",provider_write:false,credential_forwarding:false}}
async function safeFetch(url:string){const c=new AbortController(),timer=setTimeout(()=>c.abort(),5000);try{const r=await fetch(url,{method:"GET",headers:{accept:"application/json","cache-control":"no-cache, no-store","user-agent":"PentaWire-Exact-Read/2.0"},cache:"no-store",redirect:"follow",signal:c.signal});const text=await r.text();if(!r.ok)return {ok:false,status:r.status,data:null};let data:any=null;try{data=JSON.parse(text)}catch{return {ok:false,status:502,data:null}}return {ok:true,status:r.status,data}}catch{return {ok:false,status:503,data:null}}finally{clearTimeout(timer)}}
async function exactRead(url:URL,id:string){
 if(id==="chlom_public_resolver"){
  const publicId=url.searchParams.get("public_id")??"";if(!PUBLIC_ID.test(publicId))return {status:400,payload:{error:"invalid_public_id",expected_format:"ctid_<32 hex>"}};
  const r=await safeFetch(`${RESOLVER}?id=${encodeURIComponent(publicId)}`);return r.ok?{status:200,payload:{service_id:id,contract:"ct.chlom.public-identity-resolver.v1",operation:"identity.resolve",result:r.data,authority_effect:"none"}}:{status:r.status,payload:{error:"upstream_read_unavailable",service_id:id,http_status:r.status}};
 }
 if(id==="crownthrive_io_product_sandbox"){
  const op=url.searchParams.get("operation")??"health.read";let target="";
  if(op==="health.read")target=`${SANDBOX}/health`;
  else if(op==="manifest.read")target=`${SANDBOX}/manifest`;
  else if(op==="openapi.read")target=`${SANDBOX}/openapi.json`;
  else if(op==="links.list"){const page=clamp(url,"page",1,100000),lim=clamp(url,"limit",20,20);target=`${SANDBOX}/v1/links?page=${page}&limit=${lim}`}
  else if(op==="links.read"){const link=url.searchParams.get("link_id")??"";if(!LINK_ID.test(link))return {status:400,payload:{error:"invalid_link_id"}};target=`${SANDBOX}/v1/links/${link}`}
  else if(op==="statistics.read"){const link=url.searchParams.get("link_id")??"",period=url.searchParams.get("period")??"30d";if(!LINK_ID.test(link)||!["7d","30d","90d"].includes(period))return {status:400,payload:{error:"invalid_statistics_request"}};target=`${SANDBOX}/v1/links/${link}/statistics?period=${period}`}
  else return {status:400,payload:{error:"operation_not_allowed",allowed:["health.read","manifest.read","openapi.read","links.list","links.read","statistics.read"]}};
  const r=await safeFetch(target);return r.ok?{status:200,payload:{service_id:id,contract:"ct.contract.crownthrive-io.api-sandbox.v1",operation:op,result:r.data,authority_effect:"none",synthetic_only:true}}:{status:r.status,payload:{error:"upstream_read_unavailable",service_id:id,http_status:r.status}};
 }
 if(id==="pentabeata"||id==="framework_factory_v2"){
  const target=id==="pentabeata"?PENTABEATA:FRAMEWORK_FACTORY;const r=await safeFetch(target);return r.ok?{status:200,payload:{service_id:id,contract:id==="pentabeata"?"ct.pentabeata.v4":"ct.pentaframework-factory.v1",operation:"status.read",result:r.data,authority_effect:"none"}}:{status:r.status,payload:{error:"upstream_read_unavailable",service_id:id,http_status:r.status}};
 }
 if(id==="penta_heartbeat"||id==="penta_od"){
  const rows=await sql`select public.pentaod_status_v1() as value`;const v:any=rows[0]?.value??{};
  const result=id==="penta_heartbeat"?{service:"ct.penta.heartbeat.v1",primitive:"PentaBeata",on_demand_controller:"PentaOD",state:v.state??"UNKNOWN",counts:v.counts??{},partnero:v.partnero??{},authority_expansion:false}:{service:"ct.penta.od.v1",state:v.state??"UNKNOWN",counts:v.counts??{},partnero:v.partnero??{},authority_expansion:false};
  return {status:200,payload:{service_id:id,contract:id==="penta_heartbeat"?"ct.penta.heartbeat.v1":"ct.penta.od.v1",operation:"status.read",result,authority_effect:"none",control_actions_exposed:false}};
 }
 if(id==="thivebase"){
  const rows=await sql`select public.thrivebase_health_snapshot() as value`;const v:any=rows[0]?.value??{};const result={checked_at:v.checked_at??null,database_ok:Boolean(v.database_ok),overall_state:v.overall_state??"UNKNOWN",open_gates:Number(v.open_gates??0),blocking_gates:Number(v.blocking_gates??0),integration_services:Number(v.integration_services??0),approved_governed_deferrals:Number(v.approved_governed_deferrals??0),governed_deferrals_due_review:Number(v.governed_deferrals_due_review??0),founder_action_required:Boolean(v.founder_action_required),status_semantics:v.status_semantics??null,deferral_semantics:v.deferral_semantics??null};
  return {status:200,payload:{service_id:id,contract:"ct.thrivebase.health-snapshot.v1",operation:"health.read",result,authority_effect:"none",provider_credentials_exposed:false,write_authority_exposed:false}};
 }
 return {status:409,payload:{error:"exact_read_adapter_not_available",service_id:id,authority_effect:"none"}};
}
function openapi(){const g=(summary:string)=>({get:{summary,responses:{"200":{description:"Public-safe mesh result"},"404":{description:"Not found"}}}});return {openapi:"3.1.0",info:{title:"CrownThrive PentaWire Mesh API",version:VERSION,description:"Autonomous exact API/MCP gap discovery and safe read-adapter mesh. Credentialed or unknown provider semantics remain fail-closed."},servers:[{url:BASE}],paths:{"/api/services":g("List service wiring states"),"/api/services/{service_id}":g("Get service wiring state"),"/api/gaps":g("List unresolved gaps"),"/api/bindings/{service_id}":g("Get exact binding"),"/api/tools":g("List MCP contracts"),"/api/probes/{service_id}":g("Get latest exact public probe evidence"),"/api/read/{service_id}":g("Execute an allowlisted exact read adapter"),"/api/fabrics":g("Read fabric bindings"),"/api/scan/latest":g("Read latest autonomous scan"),"/api/mesh":g("Mesh discovery"),"/health":g("PentaWire health"),"/manifest":g("Service manifest"),"/.well-known/penta-wire":g("Well-known discovery")}}}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:headers("text/plain")});
 if(!["GET","HEAD"].includes(req.method))return respond(req,{error:"method_not_allowed",authority_effect:"none",provider_write:false},405,"no-store");
 const u=new URL(req.url),t=tail(u),n=clamp(u,"limit",100,200);
 try{
  if(t[0]==="api"&&t[1]==="services"&&!t[2])return respond(req,{schema:"ct.penta.wire.services.v2",node:"PentaWire",authority_effect:"none",items:(await serviceRows(n)).map(clean)});
  if(t[0]==="api"&&t[1]==="services"&&t[2]){const x=clean(await serviceRow(decodeURIComponent(t.slice(2).join("/"))));return x?respond(req,{schema:"ct.penta.wire.service.v2",service:x,links:{binding:`${BASE}/api/bindings/${encodeURIComponent(x.service_id)}`,probe:`${BASE}/api/probes/${encodeURIComponent(x.service_id)}`,read:`${BASE}/api/read/${encodeURIComponent(x.service_id)}`}}):respond(req,{error:"not_found"},404)}
  if(t[0]==="api"&&t[1]==="gaps"){const state=u.searchParams.get("state");const rows=state?await sql`select service_id,binding_state,gap_state,public_read_safe,direct_tool_count,enabled_tool_count,closed_input_tool_count,current_integration_state,last_probe_state,last_http_status,last_observed_at from integration_control.penta_wire_service_bindings_v1 where gap_state=${state} order by service_id limit ${n}`:await sql`select service_id,binding_state,gap_state,public_read_safe,direct_tool_count,enabled_tool_count,closed_input_tool_count,current_integration_state,last_probe_state,last_http_status,last_observed_at from integration_control.penta_wire_service_bindings_v1 where gap_state<>'complete' order by gap_state,service_id limit ${n}`;return respond(req,{schema:"ct.penta.wire.gaps.v2",authority_effect:"none",items:rows})}
  if(t[0]==="api"&&t[1]==="bindings"&&t[2]){const id=decodeURIComponent(t.slice(2).join("/"));const r=await sql`select b.service_id,b.binding_state,b.gap_state,b.public_read_safe,b.probe_method,case when b.public_read_safe then b.probe_url else null end as public_probe_url,b.mesh_adapter_service_id,b.mesh_api_url,b.direct_tool_count,b.enabled_tool_count,b.closed_input_tool_count,b.current_integration_state,b.last_probe_state,b.last_http_status,b.last_response_sha256,b.last_observed_at,b.evidence_sha256,ra.adapter_kind,ra.exact_contract,ra.allowed_operations,ra.state as adapter_state,b.created_at,b.updated_at from integration_control.penta_wire_service_bindings_v1 b left join integration_control.penta_wire_read_adapters_v1 ra on ra.service_id=b.service_id where b.service_id=${id} limit 1`;return r[0]?respond(req,{schema:"ct.penta.wire.binding.v2",authority_effect:"none",binding:r[0]}):respond(req,{error:"not_found"},404)}
  if(t[0]==="api"&&t[1]==="tools"){const sid=u.searchParams.get("service_id");const rows=sid?await sql`select tool_name,service_id,operation_key,risk_class,enabled,requires_human_approval,input_schema,output_schema,notes,updated_at from integration_control.mcp_tools where service_id=${sid} order by tool_name limit ${n}`:await sql`select tool_name,service_id,operation_key,risk_class,enabled,requires_human_approval,input_schema,output_schema,notes,updated_at from integration_control.mcp_tools order by service_id,tool_name limit ${n}`;return respond(req,{schema:"ct.penta.wire.tools.v2",authority_effect:"none",items:rows})}
  if(t[0]==="api"&&t[1]==="probes"&&t[2]){const id=decodeURIComponent(t.slice(2).join("/"));const r=await sql`select p.receipt_id,p.service_id,p.probe_method,case when b.public_read_safe then p.probe_url else null end as public_probe_url,p.probe_url_sha256,p.state,p.http_status,p.content_type,p.response_sha256,p.response_body_stored,p.credential_sent,p.evidence_sha256,p.observed_at from integration_control.penta_wire_probe_receipts_v1 p join integration_control.penta_wire_service_bindings_v1 b on b.service_id=p.service_id where p.service_id=${id} order by p.observed_at desc limit 1`;return r[0]?respond(req,{schema:"ct.penta.wire.probe.v2",authority_effect:"none",probe:r[0]}):respond(req,{error:"not_found"},404)}
  if(t[0]==="api"&&t[1]==="read"&&t[2]){const id=decodeURIComponent(t.slice(2).join("/"));const a=await sql`select service_id,adapter_kind,exact_contract,allowed_operations,state from integration_control.penta_wire_read_adapters_v1 where service_id=${id} and state='active' limit 1`;if(!a[0])return respond(req,{error:"exact_read_adapter_not_available",service_id:id},409);const r=await exactRead(u,id);return respond(req,{schema:"ct.penta.wire.exact-read.v1",adapter:{service_id:id,adapter_kind:a[0].adapter_kind,exact_contract:a[0].exact_contract,allowed_operations:a[0].allowed_operations},...r.payload,provider_write:false,credential_forwarding:false},r.status,"no-store")}
  if(t[0]==="api"&&t[1]==="fabrics"){const agent=await sql`select agent_id,canonical_name,autonomy_class,authority_ceiling,lifecycle_state,self_healing_enabled,no_self_approval,module_scope,metadata->'fabric_bindings' as fabric_bindings,metadata->>'external_scheduler_slot_delta' as external_scheduler_slot_delta from chlom_runtime.agent_templates where agent_id='ct.agent.penta-wire'`;const cron=await sql`select jobid,jobname,schedule,active from cron.job where jobname='ct-software-factory-tick-v2' limit 1`;return respond(req,{schema:"ct.penta.wire.fabrics.v2",authority_effect:"none",fabrics:FABRICS,agent:agent[0]??null,existing_factory_clock:cron[0]??null,new_external_clock:false})}
  if(t[0]==="api"&&t[1]==="scan"&&t[2]==="latest"){const r=await sql`select receipt_id,scan_version,total_services,services_with_zero_tools,public_auto_wired,provider_contract_holds,superseded_services,tool_contract_drift_services,bindings_total,result_state,evidence_sha256,recorded_by_agent_id,observed_at from integration_control.penta_wire_scan_receipts_v1 order by observed_at desc limit 1`;return r[0]?respond(req,{schema:"ct.penta.wire.scan.v2",authority_effect:"none",scan:r[0]}):respond(req,{error:"not_found"},404)}
  if(t[0]==="api"&&t[1]==="mesh"){const c=await sql`select count(*)::int total,count(*) filter(where binding_state='active_probe')::int active_probe,count(*) filter(where binding_state='registry_bound' and gap_state='complete')::int internal_or_registered_complete,count(*) filter(where binding_state='hold_exact_contract')::int provider_hold,count(*) filter(where binding_state='superseded')::int superseded,count(*) filter(where gap_state='tool_contract_drift')::int tool_drift,count(*) filter(where gap_state='complete')::int complete from integration_control.penta_wire_service_bindings_v1`;const adapters=await sql`select count(*)::int total,count(*) filter(where adapter_kind='PUBLIC_HTTP' and state='active')::int public_http,count(*) filter(where adapter_kind='INTERNAL_SQL' and state='active')::int internal_sql from integration_control.penta_wire_read_adapters_v1`;return respond(req,{schema:"ct.penta.wire.mesh.v2",node:"PentaWire",version:VERSION,authority_effect:"none",fabrics:FABRICS,counts:c[0],read_adapters:adapters[0],services:{services:`${BASE}/api/services`,gaps:`${BASE}/api/gaps`,tools:`${BASE}/api/tools`,fabrics:`${BASE}/api/fabrics`,latest_scan:`${BASE}/api/scan/latest`,health:`${BASE}/health`,manifest:`${BASE}/manifest`,openapi:`${BASE}/openapi.json`,well_known:`${BASE}/.well-known/penta-wire`}})}
  if(t[0]==="openapi.json")return respond(req,openapi(),200,"public,max-age=300");
  if(t[0]===".well-known"&&t[1]==="penta-wire")return respond(req,{schema:"ct.penta.wire.well-known.v2",node:"PentaWire",version:VERSION,service_id:"penta_wire_mesh",public_read_only:true,authority_effect:"none",mesh:`${BASE}/api/mesh`,openapi:`${BASE}/openapi.json`,manifest:`${BASE}/manifest`,health:`${BASE}/health`},200,"public,max-age=300");
  if(t[0]==="manifest")return respond(req,{schema:"ct.penta.wire.manifest.v2",node:"PentaWire",version:VERSION,agent_id:"ct.agent.penta-wire",parent_agent_id:"ct.agent.factory.api-mcp-packaging",public_read_only:true,authority_effect:"none",fabrics:FABRICS,auto_wire_rule:"exact public/read-safe or exact internal status contracts only",provider_contract_rule:"credentialed mutation-capable or unknown provider semantics remain HOLD",scheduler:"existing ct-software-factory-tick-v2",external_scheduler_slot_delta:0,security:{credentials_exposed:false,response_bodies_persisted:false,credential_forwarding:false,provider_write:false,money_movement:false,checkout_activation:false,d3_human_reserved:true}},200,"public,max-age=300");
  if(t[0]==="health"){const c=await sql`select count(*)::int bindings,count(*) filter(where binding_state='active_probe' and last_probe_state='pass')::int active_probe_pass,count(*) filter(where binding_state='active_probe' and last_probe_state<>'pass')::int active_probe_nonpass,count(*) filter(where gap_state='complete')::int complete,count(*) filter(where binding_state='hold_exact_contract')::int provider_contract_holds,count(*) filter(where gap_state='tool_contract_drift')::int tool_contract_drift from integration_control.penta_wire_service_bindings_v1`;const latest=await sql`select receipt_id,result_state,evidence_sha256,observed_at from integration_control.penta_wire_scan_receipts_v1 order by observed_at desc limit 1`;return respond(req,{ok:c[0].active_probe_nonpass===0,node:"PentaWire",version:VERSION,authority_effect:"none",counts:c[0],latest_scan:latest[0]??null,existing_factory_clock:true,external_scheduler_slot_delta:0},200,"no-store")}
  const rows=(await serviceRows(100)).map(clean),items=rows.map((x:any)=>({service_id:x.service_id,binding_state:x.binding_state,gap_state:x.gap_state,last_probe_state:x.last_probe_state,adapter_kind:x.adapter_kind??null}));return respond(req,{schema:"ct.penta.wire.index.v2",node:"PentaWire",version:VERSION,authority_effect:"none",description:"Autonomous API/MCP gap convergence. Safe exact reads are wired; provider-specific unknown contracts remain HOLD.",items,links:{mesh:`${BASE}/api/mesh`,gaps:`${BASE}/api/gaps`,openapi:`${BASE}/openapi.json`,manifest:`${BASE}/manifest`}})
 }catch(e){return respond(req,{error:"penta_wire_unavailable",error_class:e instanceof Error?e.name:"unknown",authority_effect:"none",provider_write:false},503,"no-store")}
});