import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const supabaseUrl=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const db=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false}});const j=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
async function auth(req:Request){const bearer=(req.headers.get("authorization")??"").replace(/^Bearer\s+/i,"");if(bearer&&bearer===serviceKey)return true;const {data,error}=await db.rpc("ct_factory_authorize_worker",{p_token:req.headers.get("x-ct-factory-token")});return !error&&data===true}
async function complete(id:string,status:"passed"|"failed"|"hold"|"skipped",output:Record<string,unknown>){const {data,error}=await db.rpc("ct_factory_complete_work",{p_work_unit_id:id,p_status:status,p_output:output});if(error)throw error;return data}
async function adapter(slug:string,payload:unknown){const r=await fetch(`${supabaseUrl}/functions/v1/${slug}`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${serviceKey}`},body:JSON.stringify(payload)});const text=await r.text();let body:any=text;try{body=JSON.parse(text)}catch{}if(!r.ok||body?.ok===false)throw new Error(`${slug} ${r.status}: ${text.slice(0,900)}`);return body}
function requiredTarget(t:any){return t.config?.required_for_release===undefined?t.target_type!=="website_surface":t.config?.required_for_release===true}
function targetApplies(t:any,requirements:any){const types=Array.isArray(requirements?.target_types)?requirements.target_types.map(String):[];const surfaces=Array.isArray(requirements?.target_surface_ids)?requirements.target_surface_ids.map(String):[];if(types.length&& !types.includes(String(t.target_type)))return false;if(String(t.target_type)==="website_surface"&&surfaces.length&&!surfaces.includes(String(t.config?.surface_id??"")))return false;return true}
async function one(){const {data,error}=await db.rpc("ct_factory_claim_work",{p_worker:"ct-software-factory-worker-v7",p_lease_seconds:900});if(error)throw error;const w=data?.[0];if(!w)return {claimed:false};const base={work_unit_id:w.work_unit_id,build_run_id:w.build_run_id,project_id:w.project_id,build_request_id:w.build_request_id,objective:w.objective,requirements:w.requirements,lane:w.lane};try{let out:any;
if(w.lane==="discover"){const {data:bindingSync}=await db.rpc("ct_factory_sync_surface_bindings",{p_project_key:"crownthrive-os-v2-factory"});const [{data:project},{data:targets},{data:bindings}]=await Promise.all([db.from("ct_factory_projects").select("project_key,name,repo_full_name,asset_scope,build_contract,deployment_contract,production_enabled").eq("id",w.project_id).single(),db.from("ct_factory_deployment_targets").select("target_key,target_type,endpoint,production,enabled,config").eq("project_id",w.project_id),db.from("ct_factory_surface_bindings").select("surface_id,provider_system,adapter_key,deployment_policy,required_for_release,certification_state").eq("project_id",w.project_id)]);out={project,targets:targets??[],surface_bindings:bindings??[],binding_sync:bindingSync,discovered_at:new Date().toISOString()};}
else if(w.lane==="architect")out={architecture:"structured-blueprint -> deterministic compiler -> governed provider mesh",invariant:"one production package per successful build run",required_evidence:["source","compiler_report","tests","security","rights_authority","deployment","rollback","sha256"],adapter_chain:["ct-factory-blueprint-planner","ct-factory-compiler.v4","ct-factory-generator.v4","ct-factory-test-runner.v3","ct-factory-deployer.v4"],surface_binding_model:"all production surfaces bound; only certified auto targets required for release"};
else if(w.lane==="generate")out={generated:await adapter("ct-factory-generator",base)};
else if(w.lane==="security")out={baseline:["fail_closed","bounded_structured_codegen","no_arbitrary_shell","no_arbitrary_sql","no_secret_values_in_artifacts","rls_required","least_privilege","rollback_required","test_before_deploy","uncertified_provider_writes_nonblocking_but_held"],rights_owner:"CrownThrive, LLC"};
else if(w.lane==="test")out={tested:await adapter("ct-factory-test-runner",base)};
else if(w.lane==="package"){const [{data:arts},{data:run},{data:bindings},{data:families}]=await Promise.all([db.from("ct_factory_artifacts").select("artifact_type,asset_key,uri,sha256,metadata").eq("build_run_id",w.build_run_id),db.from("ct_factory_build_runs").select("run_no").eq("id",w.build_run_id).single(),db.from("ct_factory_surface_bindings").select("surface_id,provider_system,adapter_key,deployment_policy,required_for_release,certification_state").eq("project_id",w.project_id),db.from("ct_factory_component_families").select("kind,compiler_version,output_class,risk_class").eq("enabled",true)]);const pkg={contract:"ct.factory.v4",build_run_id:w.build_run_id,artifacts:arts??[],component_families:families??[],surface_bindings:bindings??[],rights:{owner:"CrownThrive, LLC",notice:"CrownThrive™ Autonomous Software Factory; ThriveBase™; CHLOM™",registration_claim:false},created_at:new Date().toISOString()};const enc=new TextEncoder().encode(JSON.stringify(pkg));const d=await crypto.subtle.digest("SHA-256",enc);const digest=[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");const releaseVersion=`2.1.${run?.run_no??1}`;const {data:rp,error:pe}=await db.from("ct_factory_release_packages").upsert({build_run_id:w.build_run_id,release_version:releaseVersion,channel:"production",status:"candidate",manifest:pkg,sha256:digest,package_uri:`thrivebase://factory/${w.build_run_id}/release/${releaseVersion}`},{onConflict:"build_run_id,release_version,channel"}).select("id").single();if(pe)throw pe;out={release_package_id:rp.id,release_version:releaseVersion,channel:"production",status:"candidate",sha256:digest,production_limit:1,component_family_count:(families??[]).length,surface_binding_count:(bindings??[]).length};}
else if(w.lane==="deploy"){const {data:project}=await db.from("ct_factory_projects").select("production_enabled").eq("id",w.project_id).single();if(!project?.production_enabled)return {claimed:true,lane:w.lane,result:await complete(w.work_unit_id,"hold",{code:"PRODUCTION_NOT_ENABLED"})};out={deployed:await adapter("ct-factory-deployer",base)};}
else if(w.lane==="assurance"){const [{data:units},{data:deploys},{data:targets},{data:jobs}]=await Promise.all([db.from("ct_factory_work_units").select("lane,status,output").eq("build_run_id",w.build_run_id).order("ordinal"),db.from("ct_factory_deployments").select("target_id,state,evidence").eq("build_run_id",w.build_run_id),db.from("ct_factory_deployment_targets").select("id,target_key,target_type,enabled,config").eq("project_id",w.project_id).eq("enabled",true),db.from("ct_factory_provider_jobs").select("id,adapter_key,state,target_id,response,readback,rollback_ref").eq("build_run_id",w.build_run_id)]);const priorBlocked=(units??[]).filter((u:any)=>u.lane!=="assurance"&&["failed","hold"].includes(u.status));const dmap=new Map((deploys??[]).map((d:any)=>[d.target_id,d]));const applicable=(targets??[]).filter((t:any)=>targetApplies(t,w.requirements));const required=applicable.filter(requiredTarget);const unsatisfied=required.map((t:any)=>({target_key:t.target_key,state:dmap.get(t.id)?.state??"missing",target_id:t.id})).filter((x:any)=>x.state!=="implemented");const pendingRequiredJobs=(jobs??[]).filter((x:any)=>required.some((t:any)=>t.id===x.target_id)&&!["implemented","rolled_back"].includes(x.state));const ok=priorBlocked.length===0&&unsatisfied.length===0&&pendingRequiredJobs.length===0;await db.from("ct_factory_release_packages").update({status:ok?"implemented":"hold",implemented_at:ok?new Date().toISOString():null}).eq("build_run_id",w.build_run_id);return {claimed:true,lane:w.lane,result:await complete(w.work_unit_id,ok?"passed":"hold",{lanes:units,deployments:deploys,applicable_targets:applicable.map((t:any)=>t.target_key),required_targets:required.map((t:any)=>t.target_key),unsatisfied_required_targets:unsatisfied,pending_required_provider_jobs:pendingRequiredJobs,optional_dispositions:(deploys??[]).filter((d:any)=>!required.some((t:any)=>t.id===d.target_id)),blocked_lanes:priorBlocked})};}
else return {claimed:true,lane:w.lane,result:await complete(w.work_unit_id,"failed",{code:"UNKNOWN_LANE",lane:w.lane})};return {claimed:true,lane:w.lane,result:await complete(w.work_unit_id,"passed",out)};}catch(e){const message=e instanceof Error?e.message:String(e);try{await complete(w.work_unit_id,"failed",{code:"WORKER_EXCEPTION",message})}catch{}return {claimed:true,lane:w.lane,error:message}}}
Deno.serve(async req=>{if(req.method!=="POST")return j({error:"POST required"},405);if(!(await auth(req)))return j({error:"unauthorized"},401);let limit=8;try{const b=await req.json();limit=Math.max(1,Math.min(Number(b?.limit??8),16))}catch{}const results=[];for(let i=0;i<limit;i++){const r=await one();results.push(r);if(!r.claimed||r.error)break}return j({ok:!results.some((r:any)=>r.error),worker:"ct-software-factory-worker-v7",drained:results.filter((r:any)=>r.claimed).length,results})});
