import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const BASE=Deno.env.get("SUPABASE_URL")??"";const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";const SERVER={name:"PentaMail Governed External Dispatch",service:"ct.penta.mail.marketer-dispatch.v1",version:"1.1.0",production:true,transport_owner:"PentaMail",communication_control_plane:"PentaMarketer"};
type R=Record<string,unknown>;
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff"}})}
function headers(){return{apikey:SERVICE,authorization:`Bearer ${SERVICE}`,"content-type":"application/json"}}
async function rpc(name:string,body:R={}){const r=await fetch(`${BASE}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(),body:JSON.stringify(body)});const t=await r.text();let d:any=t;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(`${name}:${r.status}:${typeof d==="string"?d.slice(0,400):JSON.stringify(d).slice(0,600)}`);return d}
async function authorized(req:Request){const token=req.headers.get("x-penta-mail-token")??"";if(!token)return false;try{return await rpc("penta_state_report_authorize_v1",{p_token:token})===true}catch{return false}}
async function relay(payload:R){const r=await fetch(`${BASE}/functions/v1/mailgun-relay-control`,{method:"POST",headers:headers(),body:JSON.stringify({action:"send_marketer",...payload})});const t=await r.text();let d:any={};try{d=t?JSON.parse(t):{}}catch{d={error:t.slice(0,400)}}return{ok:r.ok,http_status:r.status,body:d}}
function text(v:any,max=1000){try{return JSON.stringify(v).slice(0,max)}catch{return String(v).slice(0,max)}}
async function sync(messageId:string,state:string,providerId:string|null,error:string|null){try{return await rpc("penta_marketer_sync_mail_state_v1",{p_message_id:messageId,p_state:state,p_provider_message_id:providerId,p_error:error})}catch{return false}}
async function process(batch:number){const rows:any[]=await rpc("penta_marketer_claim_outbox_v2",{p_limit:Math.max(1,Math.min(batch||2,2))});const results:any[]=[];for(const m of rows??[]){const meta=m?.metadata??{};const messageType=String(m?.message_type??"").toLowerCase();const sendKind=String(meta?.send_kind??(messageType==="locticians_claim"?"cold":"support")).toLowerCase();const fromLocal=(sendKind==="cold"||["locticians_claim","sales_outreach","lead_nurture"].includes(messageType))?"outreach":"support";const delivery=await relay({message_id:m.message_id,work_id:meta?.work_id??null,message_type:messageType,to:m.recipient,from_local:fromLocal,from_name:meta?.assigned_display_name??meta?.from_name??"CrownThrive",subject:m.subject,text:m.body_text,trigger_ref:m.trigger_ref,request_key:`penta-mail-marketer:${m.message_id}`,send_kind:sendKind,campaign_ref:meta?.campaign_ref??null,schedule_id:meta?.schedule_id??null});const providerCallMade=delivery.body?.provider_call_made===true;const providerStatus=Number.isInteger(delivery.body?.provider_status)?delivery.body.provider_status:null;const providerId=delivery.body?.id??null;if(delivery.http_status===403&&!providerCallMade){let hold:any=null;try{hold=await rpc("penta_marketer_hold_outbox_v1",{p_message_id:m.message_id,p_reason:String(delivery.body?.error??"governed_external_authorization_denied"),p_control:delivery.body??{}})}catch{}await sync(String(m.message_id),"held",null,text(delivery.body));results.push({message_id:m.message_id,ok:false,state:"held",provider_call_made:false,hold_reason:delivery.body?.error??"authorization_denied",hold});continue}const ok=delivery.ok&&delivery.body?.ok===true;const completion=await rpc("penta_mail_complete_outbox_v3",{p_message_id:m.message_id,p_lease_id:m.lease_id,p_ok:ok,p_provider_call_made:providerCallMade,p_provider_http_status:providerStatus,p_provider_message_id:providerId,p_error:ok?null:text(delivery.body),p_retry_after_seconds:Number(delivery.body?.retry_after_seconds??300)||300});const rawState=String(completion?.state??(ok?"sent":"failed")).toLowerCase();const workState=["queued","dispatching","sent","failed","held","cancelled"].includes(rawState)?rawState:(rawState==="reconciliation_required"?"held":ok?"sent":"failed");await sync(String(m.message_id),workState,providerId,ok?null:text(delivery.body));results.push({message_id:m.message_id,type:messageType,ok,provider_call_made:providerCallMade,provider_status:providerStatus,provider_message_id:providerId,state:completion?.state??workState,agent_id:meta?.assigned_agent_id??null,persona_id:meta?.assigned_persona_id??null});if(delivery.body?.provider_probation_detected===true)break}return{ok:true,server:SERVER,claimed:rows?.length??0,processed:results.length,results,at:new Date().toISOString()}}
Deno.serve(async(req:Request)=>{try{if(req.method!=="POST")return json({ok:false,error:"POST_required",server:SERVER},405);if(!(await authorized(req)))return json({ok:false,error:"dispatch_token_required",server:SERVER},403);const body=await req.json().catch(()=>({}));const action=String(body?.action??"process_outbox");if(action==="health")return json({ok:true,server:SERVER,provider_adapter:"mailgun-relay-control",raw_secret_exposed:false});if(action!=="process_outbox")return json({ok:false,error:"unsupported_action",allowed:["health","process_outbox"],server:SERVER},400);return json(await process(Number(body?.batch??2)))}catch(e){return json({ok:false,server:SERVER,error:e instanceof Error?e.message:String(e),raw_secret_exposed:false},500)}});
