import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.3";

const REPO = "crownthrive1/CrownThrive-OS";
const BRANCH = "penta/identity-label-family-fabric-v1";
const TOKEN_ALIAS = "PENTA_PM_GITHUB_TOKEN";
const CONTROL_ALIAS = "stripe_production_control_gateway_secret_v1";
const TARGETS = ["20260830025630", "20260830025906", "20260830030246"];
let client: ReturnType<typeof postgres> | null = null;
function db(){ const u=Deno.env.get("SUPABASE_DB_URL")??""; if(!u) throw new Error("database_unavailable"); client??=postgres(u,{max:2,idle_timeout:10,prepare:false}); return client; }
function json(v:unknown,s=200){ return new Response(JSON.stringify(v),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}}); }
function hex(b:Uint8Array){ return [...b].map(v=>v.toString(16).padStart(2,"0")).join(""); }
async function sha(v:string){ return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)))); }
function base64(value:string){ const bytes=new TextEncoder().encode(value); let binary=""; for(let i=0;i<bytes.length;i+=8192) binary+=String.fromCharCode(...bytes.subarray(i,i+8192)); return btoa(binary); }
async function vault(n:string){ const r=await db()<Array<{v:string|null}>>`select decrypted_secret as v from vault.decrypted_secrets where name=${n} order by created_at desc limit 1`; return r[0]?.v??""; }
async function gh(token:string,path:string,content:string,message:string){ const url=`https://api.github.com/repos/${REPO}/contents/${path.split("/").map(encodeURIComponent).join("/")}`; const headers={authorization:`Bearer ${token}`,accept:"application/vnd.github+json","x-github-api-version":"2022-11-28","user-agent":"CrownThrive-PentaIdentitySourceCustody/1.0.0"}; const get=await fetch(`${url}?ref=${encodeURIComponent(BRANCH)}`,{headers}); let existing:any=null; if(get.status===200) existing=await get.json(); else if(get.status!==404) throw new Error(`github_read_${get.status}_${path}`); const payload:any={message,content:base64(content),branch:BRANCH}; if(existing?.sha) payload.sha=existing.sha; const put=await fetch(url,{method:"PUT",headers:{...headers,"content-type":"application/json"},body:JSON.stringify(payload),signal:AbortSignal.timeout(30000)}); const text=await put.text(); let data:any={}; try{data=text?JSON.parse(text):{}}catch{data={parse_error:true}}; if(!put.ok) throw new Error(`github_write_${put.status}_${path}_${data?.message??"unknown"}`); return {path,commit_sha:data?.commit?.sha??null,blob_sha:data?.content?.sha??null,updated:Boolean(existing?.sha)}; }
Deno.serve(async(req:Request)=>{ if(req.method!=="POST") return json({ok:false,error:"method_not_allowed"},405); try{ const control=await vault(CONTROL_ALIAS); if(!control || (req.headers.get("x-ct-control-secret")??"")!==control) return json({ok:false,error:"internal_authorization_required"},403); const token=await vault(TOKEN_ALIAS); if(!token) return json({ok:false,error:"github_token_unavailable"},503); const rows=await db()<Array<{version:string,name:string,statements:string[]}>>`select version,name,statements from supabase_migrations.schema_migrations where version=any(${TARGETS}::text[]) order by version`; if(rows.length!==TARGETS.length) throw new Error(`migration_count_mismatch_${rows.length}`); const files:any[]=[]; const manifestRows:any[]=[]; for(const row of rows){ const content=(row.statements??[]).join("\n\n"); const digest=await sha(content); const path=`supabase/migrations/${row.version}_${row.name}.sql`; files.push(await gh(token,path,content,`chore(penta): custody ${row.name} provider migration`)); manifestRows.push({version:row.version,name:row.name,path,sql_sha256:digest,statement_count:(row.statements??[]).length,provider_applied:true}); } const manifest={schema:"crownthrive.penta.identity-source-custody/v1",generated_at:new Date().toISOString(),project_ref:"tzajnzshmtzjenqulehq",repository:REPO,branch:BRANCH,production_history_rewritten:false,replay_attempted:false,provider_migrations:manifestRows,raw_secrets_in_source:false,authority_created:false}; const manifestText=JSON.stringify(manifest,null,2)+"\n"; files.push(await gh(token,"data/penta/source-custody/penta-identity-label-family-fabric.20260830.v1.json",manifestText,"docs(penta): record identity/family fabric source custody")); const evidenceSha=await sha(JSON.stringify(manifest)); await db()`select chlom_runtime.append_dail_event('penta.identity_source_custody.projected','source_custody','penta-identity-label-family-fabric-v1',${db().json({branch:BRANCH,repository:REPO,migration_count:manifestRows.length,evidence_sha256:evidenceSha,raw_secrets_in_source:false,production_history_rewritten:false})},'PentaSerialized/PentaBuild/PentaCertify',null,'PentaSerialized','1.0.0',${evidenceSha},null,'ct.penta.identity.source-custody.v1',null,'internal')`; return json({ok:true,state:"projected",repository:REPO,branch:BRANCH,migration_count:manifestRows.length,files,evidence_sha256:evidenceSha,raw_secret_exposed:false}); }catch(e){ return json({ok:false,error:e instanceof Error?e.message:"projection_failed",raw_secret_exposed:false},500); } });
