import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const url=Deno.env.get("SUPABASE_URL")!,key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const db=createClient(url,key,{auth:{persistSession:false}});
const j=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
function slug(v:unknown){const s=String(v??"service").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70);return s||"service"}
function ident(v:unknown){const s=String(v??"item").replace(/[^A-Za-z0-9_]/g,"_").replace(/^([0-9])/,'_$1').slice(0,60);return s||"item"}
function pathPart(v:unknown){return slug(v).replace(/-/g,"_")}
Deno.serve(async req=>{try{if(req.method!=="POST")return j({error:"POST required"},405);const p=await req.json();if(!p?.build_run_id)throw new Error("build_run_id_required");const r=p.requirements??{};if(r.compiler_spec)return j({ok:true,planner:"ct-factory-blueprint-planner.v1",mode:"passthrough",compiler_spec:r.compiler_spec});const b=r.blueprint??{};const packageName=slug(b.package_name??b.service_name??p.objective??"crownthrive-service");const components:any[]=[];
const serviceName=String(b.service_name??packageName).slice(0,120);
components.push({kind:"typescript_module",path:"src/service-info.ts",export_name:"serviceInfo",value:{name:serviceName,package:packageName,version:String(b.version??"1.0.0"),capabilities:Array.isArray(b.capabilities)?b.capabilities:[]}});
const endpoints=Array.isArray(b.endpoints)?b.endpoints:[];if(endpoints.length){components.push({kind:"openapi_spec",path:"contracts/openapi.json",title:serviceName,version:String(b.version??"1.0.0"),paths:endpoints.map((e:any)=>({path:String(e.path??"/"),method:String(e.method??"get"),operation_id:ident(e.operation_id??`${e.method??"get"}_${String(e.path??"root").replace(/\W+/g,"_")}`),summary:String(e.summary??"").slice(0,240),response_schema:e.response_schema??{type:"object"}}))});components.push({kind:"edge_api",path:`supabase/functions/${packageName}/index.ts`,service:serviceName,message:String(b.api_message??`${serviceName} generated API`)});}
for(const e of (Array.isArray(b.data_entities)?b.data_entities:[]).slice(0,20)){const table=ident(e.table??e.name);components.push({kind:"sql_table",path:`supabase/migrations/${String(components.length).padStart(3,"0")}_${pathPart(table)}.sql`,schema:ident(e.schema??"ct_generated"),table,columns:Array.isArray(e.columns)?e.columns:[{name:"id",type:"uuid",default:"gen_random_uuid()"},{name:"created_at",type:"timestamptz"}]});}
for(const page of (Array.isArray(b.pages)?b.pages:[]).slice(0,24)){const name=slug(page.slug??page.title??`page-${components.length}`);components.push({kind:"static_site",path:name==="home"?"site/index.html":`site/${name}/index.html`,title:String(page.title??serviceName),headline:String(page.headline??page.title??serviceName),body:String(page.body??"")});}
const tools=Array.isArray(b.mcp_tools)?b.mcp_tools:[];if(tools.length)components.push({kind:"mcp_tool_manifest",path:"contracts/mcp-tools.json",server:serviceName,tools:tools.map((t:any)=>({name:ident(t.name),description:String(t.description??""),input_schema:t.input_schema??{type:"object",properties:{}}}))});
for(const d of (Array.isArray(b.docs)?b.docs:[]).slice(0,20)){const name=slug(d.slug??d.title??`doc-${components.length}`);components.push({kind:"mdx_document",path:`docs/${name}.mdx`,title:String(d.title??serviceName),description:String(d.description??""),body:String(d.body??"")});}
if(b.workflow!==false)components.push({kind:"github_workflow",path:`.github/workflows/${packageName}-verify.yml`,name:`${serviceName} Verify`,trigger:String(b.workflow_trigger??"push"),steps:[{type:"checkout"},{type:"deno_setup"},{type:"deno_check",path:"supabase/functions"}]});
const events=Array.isArray(b.events)?b.events:[];for(const e of events.slice(0,16))components.push({kind:"event_contract",path:`contracts/events/${slug(e.name)}.schema.json`,name:ident(e.name),properties:e.properties??{},required:Array.isArray(e.required)?e.required:[]});
const env=Array.isArray(b.environment)?b.environment:[];if(env.length)components.push({kind:"env_contract",path:"contracts/environment.json",variables:env});
const routes=Array.isArray(b.routes)?b.routes:[];if(routes.length)components.push({kind:"route_manifest",path:"contracts/routes.json",routes});
const assets=Array.isArray(b.assets)?b.assets:[];if(assets.length)components.push({kind:"asset_manifest",path:"contracts/assets.json",assets});
if(b.policy)components.push({kind:"policy_manifest",path:"governance/policy.json",policy_id:String(b.policy.policy_id??`${packageName}.policy`),risk_class:String(b.policy.risk_class??"D1"),authority:String(b.policy.authority??"CHLOM"),fail_closed:b.policy.fail_closed!==false,required_evidence:b.policy.required_evidence??["tests","sha256","rollback"],rules:b.policy.rules??[]});
if(Array.isArray(b.cache_assets)&&b.cache_assets.length)components.push({kind:"service_worker",path:"site/sw.js",cache_name:`${packageName}-${String(b.version??"v1")}`,assets:b.cache_assets});
if(components.length>96)throw new Error("blueprint_component_limit_exceeded");const compiler_spec={package_name:packageName,components};const report={contract:"ct.blueprint.plan.v1",package_name:packageName,component_count:components.length,kinds:[...new Set(components.map(c=>c.kind))],generated_at:new Date().toISOString()};await db.from("ct_factory_artifacts").upsert({build_run_id:p.build_run_id,artifact_type:"blueprint_plan",asset_key:`${packageName}-blueprint-plan.json`,uri:`thrivebase://factory/${p.build_run_id}/blueprint-plan`,sha256:null,metadata:report},{onConflict:"build_run_id,artifact_type,asset_key"});return j({ok:true,planner:"ct-factory-blueprint-planner.v1",mode:"structured_blueprint",compiler_spec,report});}catch(e){return j({ok:false,error:e instanceof Error?e.message:String(e)},422)}});
