import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.5";
const sql=postgres(Deno.env.get("SUPABASE_DB_URL")!,{max:2,prepare:false});
const V="1.0.0",C="ct.penta.replicate.v1",P="2025-03-26",enc=new TextEncoder();
type Rpc={jsonrpc?:string;id?:string|number|null;method?:string;params?:any};
function h(req:Request,type="application/json; charset=utf-8"){const x=new Headers({"content-type":type,"cache-control":"no-store","x-content-type-options":"nosniff","x-penta-replicate-version":V,"access-control-allow-origin":req.headers.get("origin")||"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type,authorization,mcp-session-id,x-request-id","access-control-expose-headers":"mcp-session-id,x-penta-replicate-version,x-penta-replicate-sha256,x-request-id"});x.set("x-request-id",req.headers.get("x-request-id")?.slice(0,120)||crypto.randomUUID());return x}
async function d(s:string){const z=await crypto.subtle.digest("SHA-256",enc.encode(s));return [...new Uint8Array(z)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function o(req:Request,b:any,s=200,t="application/json; charset=utf-8",session?:string){const q=typeof b==="string"?b:JSON.stringify(b),x=h(req,t);x.set("x-penta-replicate-sha256",await d(q));if(session)x.set("mcp-session-id",session);return new Response(q,{status:s,headers:x})}
function sid(v:any){const s=String(v??"").trim();if(!s||s.length>240||!/^[A-Za-z0-9._:-]+$/.test(s))throw Error("invalid_surface_id");return s}
async function status(){const r=await sql<Array<{v:any}>>`select integration_control.penta_replicate_status_v1() v`;return r[0]?.v}
async function manifest(s:string){const r=await sql<Array<{v:any}>>`select integration_control.penta_replicate_manifest_v1(${s}) v`;return r[0]?.v}
async function targets(l:any=100){const n=Math.max(1,Math.min(Number(l)||100,100));const r=await sql<Array<any>>`select surface_id,canonical_url,provider_system,update_mode,auto_update_enabled,provider_connection_state,health_state,eligibility_state,authority_ceiling,last_manifest_sha256,last_applied_sha256,last_applied_at,failure_count from integration_control.penta_replicate_targets_v1 order by surface_id limit ${n}`;return{state:"PASS",count:r.length,items:r,provider_credentials_exposed:false}}
async function drift(v?:any){if(v){const s=sid(v);const r=await sql<Array<any>>`select surface_id,eligibility_state,last_manifest_sha256,last_applied_sha256,last_manifest_at,last_applied_at,(last_manifest_sha256 is distinct from last_applied_sha256) drift from integration_control.penta_replicate_targets_v1 where surface_id=${s}`;return{state:"PASS",items:r,provider_credentials_exposed:false}}const r=await sql<Array<any>>`select surface_id,eligibility_state,last_manifest_sha256,last_applied_sha256,last_manifest_at,last_applied_at from integration_control.penta_replicate_targets_v1 where last_manifest_sha256 is distinct from last_applied_sha256 order by updated_at desc limit 100`;return{state:"PASS",count:r.length,items:r,provider_credentials_exposed:false}}
function boot(s:string,origin:string){const m=`${origin}/functions/v1/penta-replicate-v1?action=manifest&surface_id=${encodeURIComponent(s)}`,u=`${origin}/functions/v1/penta-replicate-v1?action=mcp`;return`(()=>{const k="CrownThrivePentaReplicate",sid=${JSON.stringify(s)},manifestUrl=${JSON.stringify(m)},mcpUrl=${JSON.stringify(u)};if(window[k]&&window[k].surfaceId===sid){window[k].refresh?.();return}const x={contract:"ct.penta.replicate.bootstrap.v1",version:"1.0.0",surfaceId:sid,manifestUrl,mcpUrl,registry:null,lastRefresh:null,providerCredentialsExposed:false,providerWrite:false,async refresh(){const r=await fetch(manifestUrl,{headers:{accept:"application/json"},cache:"no-store"});if(!r.ok)throw Error("penta_replicate_manifest_"+r.status);this.registry=await r.json();this.lastRefresh=new Date().toISOString();window.dispatchEvent(new CustomEvent("crownthrive:penta-replicated",{detail:{surfaceId:sid,manifestSha256:this.registry?.manifest_sha256}}));return this.registry}};window[k]=x;let meta=document.querySelector('meta[name="crownthrive:penta-replicate"]');if(!meta){meta=document.createElement("meta");meta.name="crownthrive:penta-replicate";document.head?.appendChild(meta)}meta.content="1.0.0|"+sid;x.refresh().catch(e=>console.warn("PentaReplicate",e?.message||e))})();`}
const tools=[{name:"penta.replicate.status",description:"Read PentaReplicate fleet status.",inputSchema:{type:"object",properties:{},additionalProperties:false}},{name:"penta.replicate.manifest",description:"Read one secret-free surface replication manifest.",inputSchema:{type:"object",properties:{surface_id:{type:"string"}},required:["surface_id"],additionalProperties:false}},{name:"penta.replicate.targets",description:"List PentaReplicate targets and eligibility.",inputSchema:{type:"object",properties:{limit:{type:"integer",minimum:1,maximum:100}},additionalProperties:false}},{name:"penta.replicate.drift",description:"Read manifest/application drift without provider mutation.",inputSchema:{type:"object",properties:{surface_id:{type:"string"}},additionalProperties:false}}].map(t=>({...t,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true}}));
const rr=(id:any,result:any)=>({jsonrpc:"2.0",id:id??null,result}),er=(id:any,code:number,message:string)=>({jsonrpc:"2.0",id:id??null,error:{code,message}}),tr=(v:any,isError=false)=>({content:[{type:"text",text:JSON.stringify(v,null,2)}],structuredContent:v,isError});
async function call(n:string,a:any){if(n==="penta.replicate.status")return status();if(n==="penta.replicate.manifest")return manifest(sid(a?.surface_id));if(n==="penta.replicate.targets")return targets(a?.limit);if(n==="penta.replicate.drift")return drift(a?.surface_id);throw Error("tool_not_found")}
function sr(req:Request){const k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";return k.length>20&&(req.headers.get("authorization")||"")===`Bearer ${k}`}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:h(req)});try{const u=new URL(req.url),a=u.searchParams.get("action")||"health",origin=`${u.protocol}//${u.host}`;if(req.method==="GET"&&a==="health")return o(req,{state:"PASS",service:"penta-replicate-v1",version:V,contract:C,status:await status(),public_reads:true,provider_write_direct:false,provider_credentials_exposed:false,checked_at:new Date().toISOString()});if(req.method==="GET"&&a==="manifest")return o(req,await manifest(sid(u.searchParams.get("surface_id"))));if(req.method==="GET"&&a==="bootstrap")return o(req,boot(sid(u.searchParams.get("surface_id")),origin),200,"application/javascript; charset=utf-8");if(req.method==="POST"&&a==="cycle"){if(!sr(req))return o(req,{state:"DENY",reason:"service_role_required"},403);const b=await req.json().catch(()=>({}));const r=await sql<Array<{v:any}>>`select integration_control.penta_replicate_cycle_v1(${b?.force===true}) v`;return o(req,r[0]?.v)}if(req.method==="POST"&&a==="mcp"){const rpc:Rpc=await req.json().catch(()=>({}));if(rpc.jsonrpc!=="2.0"||!rpc.method)return o(req,er(rpc.id,-32600,"Invalid Request"),400);const s=req.headers.get("mcp-session-id")||crypto.randomUUID();if(rpc.method==="initialize")return o(req,rr(rpc.id,{protocolVersion:P,capabilities:{tools:{listChanged:false}},serverInfo:{name:"PentaReplicate",version:V},instructions:"Read-only CrownThrive replication discovery. Provider writes and credentials are not exposed through this MCP."}),200,"application/json; charset=utf-8",s);if(rpc.method==="notifications/initialized"||rpc.method==="notifications/cancelled")return new Response(null,{status:202,headers:h(req)});if(rpc.method==="ping")return o(req,rr(rpc.id,{}),200,"application/json; charset=utf-8",s);if(rpc.method==="tools/list")return o(req,rr(rpc.id,{tools}),200,"application/json; charset=utf-8",s);if(rpc.method==="tools/call"){const n=String(rpc.params?.name||"");if(!tools.some(t=>t.name===n))return o(req,er(rpc.id,-32602,"Unknown tool"),200,"application/json; charset=utf-8",s);try{return o(req,rr(rpc.id,tr(await call(n,rpc.params?.arguments||{}))),200,"application/json; charset=utf-8",s)}catch(e){return o(req,rr(rpc.id,tr({state:"ERROR",reason:e instanceof Error?e.message:String(e),provider_credentials_exposed:false},true)),200,"application/json; charset=utf-8",s)}}return o(req,er(rpc.id,-32601,"Method not found"),200,"application/json; charset=utf-8",s)}return o(req,{state:"NOT_FOUND",service:"penta-replicate-v1"},404)}catch(e){return o(req,{state:"ERROR",reason:e instanceof Error?e.message:String(e),provider_credentials_exposed:false},500)}});
