const $=s=>document.querySelector(s);let weather={temp:68,wind:5,code:1,local:false};
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2100)}
function date(){let d=new Date();$('#todayDate').textContent=d.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'});}
async function location(){if(!navigator.geolocation)return toast('Location is not available here.');$('#locHint').textContent='Getting local conditions…';navigator.geolocation.getCurrentPosition(async p=>{try{let u=`https://api.open-meteo.com/v1/forecast?latitude=${p.coords.latitude}&longitude=${p.coords.longitude}&current=temperature_2m,wind_speed_10m,weather_code&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto`;let r=await fetch(u);if(!r.ok)throw 0;let j=await r.json();weather={temp:Math.round(j.current.temperature_2m),wind:Math.round(j.current.wind_speed_10m),code:j.current.weather_code,local:true};$('#wxTemp').textContent=`${weather.temp}° · ${weather.wind} mph`;$('#locHint').textContent='Local conditions connected · used only for this planning session';toast('Local conditions loaded.')}catch{$('#locHint').textContent='Conditions unavailable · demo stays active'}} ,()=>{$('#locHint').textContent='Location not shared · demo conditions stay active'},{timeout:9000})}
function cleanLines(v){return v.split(/\n|,|;/).map(x=>x.trim()).filter(Boolean).slice(0,6)}function tplus(min){return new Date(Date.now()+min*60000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function handle(){let must=cleanLines($('#must').value),should=$('#should').value.trim(),want=$('#want').value.trim(),hours=+$('#hours').value,protect=+$('#protect').value,total=hours*60;$('#protectNum').textContent=protect>=120?`${protect/60}h`:`${protect}m`;$('#protectedBrief').textContent=protect>=120?`${protect/60} hr reserved`:`${protect} min reserved`;let obligations=must.length?must:['Handle the one thing that creates the most downstream relief'];if(should)obligations.push(should);let work=Math.max(90,total-protect-50),per=Math.max(25,Math.floor(work/obligations.length));let slots=[],cursor=0;slots.push([cursor,'Set the board','Water, messages, quick scan. Decide what will not be allowed to hijack the day.','RESET']);cursor+=20;obligations.forEach((x,i)=>{slots.push([cursor,x,i===0?'Primary obligation — finish or create a clean handoff before opening another lane.':'Contained work block — enough progress to remove mental drag.','HANDLE']);cursor+=per});let p=Math.min(Math.max(40,total-protect),cursor+10);slots.push([p,want||'Protected time','This block is intentionally yours. Fishing, music, food, sports, a drive, the porch, or nothing.','PROTECTED']);if(p+protect<total)slots.push([p+protect,'Close clean','Capture anything unfinished, choose tomorrow’s first move, then stop carrying it in your head.','CLOSE']);$('#schedule').innerHTML=slots.sort((a,b)=>a[0]-b[0]).map(s=>`<div class="slot"><time>${tplus(s[0])}</time><div><b>${s[1]}</b><span>${s[2]}</span></div><div class="badge">${s[3]}</div></div>`).join('');$('#dayplan').classList.add('show');localStorage.setItem('lifewright:lastDay',JSON.stringify({must,should,want,hours,protect,at:new Date().toISOString()}));toast('Your day is ordered. Protect the protected block.')}
function get(){try{return JSON.parse(localStorage.getItem('lifewright:queue'))||[]}catch{return[]}}function render(){let a=get();$('#reminderList').innerHTML=a.length?a.map((x,i)=>`<div class="item"><div><b>${x}</b><span>Personal queue</span></div><button data-rm="${i}">×</button></div>`).join(''):'<div class="sub" style="padding:10px 0">Nothing queued. That is allowed.</div>';document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{a.splice(+b.dataset.rm,1);localStorage.setItem('lifewright:queue',JSON.stringify(a));render()})}
function add(v){v=(v||$('#reminderInput').value).trim();if(!v)return;let a=get();a.unshift(v);localStorage.setItem('lifewright:queue',JSON.stringify(a));$('#reminderInput').value='';render();toast('Added. You do not have to keep remembering it.')}
function den(){document.body.classList.toggle('den-on');let on=document.body.classList.contains('den-on');$('#denBtn').textContent=on?'Leave Den Mode':'Enter Den Mode';$('#denTop').textContent=on?'Exit Den Mode':'Protect my time';$('#modeBrief').textContent=on?'Protected':'Handle → enjoy';if(on)window.scrollTo({top:document.querySelector('#day').offsetTop-70,behavior:'smooth'})}
$('#todayDate').textContent='';date();$('#wxTemp').textContent=`${weather.temp}° · demo`;$('#handleBtn').onclick=handle;$('#wxBtn').onclick=location;$('#denBtn').onclick=$('#denTop').onclick=den;$('#reminderAdd').onclick=()=>add();$('#reminderInput').onkeydown=e=>{if(e.key==='Enter')add()};document.querySelectorAll('[data-seed]').forEach(b=>b.onclick=()=>add(b.dataset.seed));$('#creelAction').onclick=()=>window.location.assign('/creelpilot');render();
