-- remote_applied_version: 20260827174511
-- CrownThrive migration-lineage restoration marker v3
-- Production migration name: control_plane_explicit_rls_deny_policies_v1
-- This timestamp is recorded as APPLIED in production ThriveBase.
-- Exact historical SQL is intentionally not republished from production history.
-- Canonical applied SQL remains under production migration-ledger custody.
-- This file is a no-op and exists only to restore Git/Supabase timestamp lineage parity.
-- It does not recreate, re-run, roll back, or mutate the production migration.
-- Clean-room reconstruction from public lineage markers alone remains NOT CERTIFIED.
