create or replace function integration_control.penta_identity_refresh_v1(p_source_ref text default 'hourly-penta-activation-continuity') returns jsonb
language plpgsql security definer set search_path=integration_control,pentamocracy,penta_runtime,penta_pm,penta_discovery,public,extensions,pg_temp as $$
declare
  snap jsonb; snap_sha text; snap_version text; run_id uuid:=gen_random_uuid();
  r record; sys jsonb; idkey text; cname text; rawfam text; fkey text; fname text; roletext text; ax text; kindtext text; mat text; regstate text; act text; rt text; docspath text; docsns text; fid uuid; lbls text[]; eligible boolean; n int:=0; nf int:=0;
begin
  select payload,source_sha256,source_version into snap,snap_sha,snap_version from integration_control.penta_identity_source_snapshots_v1 where source_type='github_penta_os_registry' order by observed_at desc limit 1;
  if snap is null then raise exception 'Penta identity source snapshot missing'; end if;

  for r in
    select c.citizen_id,c.penta_identity,c.family_id,c.citizen_class,c.metadata,
           f.family_key as existing_family_key,f.name as existing_family_name,
           e.canonical_name as live_name,e.entity_kind as live_kind,e.lifecycle_state as live_lifecycle,e.attributes as live_attrs,
           j.job_role,j.family_key as job_family,j.activation_state as job_activation
    from pentamocracy.citizens_v1 c
    left join pentamocracy.families_v1 f on f.family_id=c.family_id
    left join integration_control.penta_census_entities_v1 e on e.entity_key=c.penta_identity and e.current
    left join lateral (select x.job_role,x.family_key,x.activation_state from pentamocracy.penta_job_assignments_v1 x where x.citizen_id=c.citizen_id order by x.assigned_at desc limit 1) j on true
    where c.active
    order by c.penta_identity
  loop
    cname:=coalesce(r.metadata->>'display_name',r.live_name,(select s.canonical_name from public.penta_system_registry s where s.system_key=r.penta_identity limit 1),(select cr.canonical_name from penta_runtime.component_registry_v1 cr where cr.component_key=r.penta_identity limit 1),r.penta_identity);
    sys:=null;
    select x into sys from jsonb_array_elements(snap->'systems') x where lower(x->>'canonical_name')=lower(cname) limit 1;
    docspath:=r.metadata->>'docs_path'; docsns:=r.metadata->>'namespace';
    if sys is not null and coalesce(sys->>'machine_key','')<>'' then idkey:=sys->>'machine_key';
    elsif r.penta_identity ~ '^penta\.' or r.penta_identity ~ '^ct\.' then idkey:=r.penta_identity;
    elsif docspath is not null then idkey:='penta.candidate.'||replace(regexp_replace(regexp_replace(split_part(docspath,'/',array_length(string_to_array(docspath,'/'),1)),'^penta-',''),'-',' ','g'),' ','.');
    else idkey:='penta.identity.'||substr(encode(extensions.digest(r.penta_identity,'sha256'),'hex'),1,24); end if;

    rawfam:=coalesce(r.metadata->>'raw_family',r.job_family,r.existing_family_name,'Pending canonical family');
    select m.family_key,m.canonical_family_name into fkey,fname from integration_control.penta_family_label_map_v1 m where lower(m.raw_label)=lower(rawfam) limit 1;
    if fkey is null then fkey:='PROVISIONAL_UNASSIGNED'; fname:='Provisional / Family Assignment Pending'; end if;

    roletext:=coalesce(sys->>'role',r.job_role,r.live_attrs->>'category',cname||' institutional capability');
    ax:=sys->>'axis'; kindtext:=coalesce(sys->>'kind',r.live_kind,case when docsns='candidates' then 'candidate' else 'system' end);
    mat:=coalesce(r.live_attrs->>'maturity',sys->>'maturity',(select s.maturity from public.penta_system_registry s where lower(s.canonical_name)=lower(cname) limit 1),'specified');
    regstate:=coalesce(sys->>'registration_state',docsns,case when r.live_lifecycle='production' then 'live_runtime' else 'institutional' end);
    if r.live_lifecycle='production' or exists(select 1 from public.penta_system_registry s where lower(s.canonical_name)=lower(cname) and s.maturity='production' and s.runtime_ref is not null) then rt:='RUNTIME_PRESENT';
    elsif exists(select 1 from penta_runtime.component_registry_v1 cr where lower(cr.canonical_name)=lower(cname) and cr.enabled) then rt:='RUNTIME_PRESENT';
    elsif mat in ('implemented','production','certified') then rt:='IMPLEMENTED_SOURCE'; else rt:='INSTITUTIONAL_ONLY'; end if;
    if fkey='PROVISIONAL_UNASSIGNED' then act:='HOLD_FAMILY'; elsif rt='RUNTIME_PRESENT' and mat='production' then act:='ACTIVE'; else act:='ACTIVE_FAIL_CLOSED'; end if;
    eligible:=exists(select 1 from penta_pm.executable_pentas_v1 ep where ep.current and ep.pr_eligible and lower(ep.canonical_name)=lower(cname));
    lbls:=array_remove(array['penta:citizen','identity:'||lower(coalesce(docsns,case when r.live_lifecycle='production' then 'live' else 'institutional' end)),'family:'||lower(fkey),'kind:'||lower(coalesce(kindtext,'unknown')),'axis:'||lower(coalesce(ax,'unclassified')),'maturity:'||lower(coalesce(mat,'specified')),'activation:'||lower(act),'runtime:'||lower(rt),case when eligible then 'penta:pm-executable' else 'penta:pm-nonexecutable' end],null);

    insert into integration_control.penta_identity_registry_v1(identity_key,canonical_name,identity_class,docs_path,docs_namespace,family_key,family_name,role,axis,kind,maturity,registration_state,activation_state,runtime_state,labels,source_refs,source_sha256,current,active,metadata)
    values(idkey,cname,case when docsns='canonical' then 'CANONICAL' when docsns='candidates' then 'CANDIDATE' else 'LIVE_ONLY' end,docspath,docsns,fkey,fname,roletext,ax,kindtext,mat,regstate,act,rt,lbls,jsonb_build_object('primary',p_source_ref,'citizen_identity',r.penta_identity,'penta_os_registry','crownthrive1/CrownThrive-OS@845deac432b3210e73f61dffde8e335a84d24837','docs_path',docspath),snap_sha,true,true,jsonb_build_object('citizen_id',r.citizen_id,'raw_family_label',rawfam,'previous_family_key',r.existing_family_key,'previous_family_name',r.existing_family_name,'source_registry_version',snap_version,'source_maturity',mat,'pm_execution_eligible',eligible))
    on conflict(identity_key) do update set canonical_name=excluded.canonical_name,docs_path=coalesce(excluded.docs_path,integration_control.penta_identity_registry_v1.docs_path),docs_namespace=coalesce(excluded.docs_namespace,integration_control.penta_identity_registry_v1.docs_namespace),family_key=excluded.family_key,family_name=excluded.family_name,role=excluded.role,axis=coalesce(excluded.axis,integration_control.penta_identity_registry_v1.axis),kind=coalesce(excluded.kind,integration_control.penta_identity_registry_v1.kind),maturity=excluded.maturity,registration_state=excluded.registration_state,activation_state=excluded.activation_state,runtime_state=excluded.runtime_state,labels=excluded.labels,source_refs=integration_control.penta_identity_registry_v1.source_refs||excluded.source_refs,source_sha256=excluded.source_sha256,current=true,active=true,metadata=integration_control.penta_identity_registry_v1.metadata||excluded.metadata,updated_at=now();

    insert into integration_control.penta_identity_aliases_v1(alias_key,identity_key,alias_type,source_ref,metadata) values(r.penta_identity,idkey,case when r.penta_identity=idkey then 'SELF' else 'SOURCE_IDENTITY' end,p_source_ref,jsonb_build_object('citizen_id',r.citizen_id,'docs_path',docspath)) on conflict(alias_key) do update set identity_key=excluded.identity_key,alias_type=excluded.alias_type,source_ref=excluded.source_ref,metadata=integration_control.penta_identity_aliases_v1.metadata||excluded.metadata,last_seen_at=now();

    update integration_control.penta_identity_labels_v1 set active=false,last_seen_at=now() where identity_key=idkey;
    insert into integration_control.penta_identity_labels_v1(identity_key,label,label_class,source_ref,active) select idkey,l,split_part(l,':',1),p_source_ref,true from unnest(lbls) l on conflict(identity_key,label) do update set active=true,source_ref=excluded.source_ref,last_seen_at=now();

    select family_id into fid from pentamocracy.families_v1 where family_key=fkey limit 1;
    if fid is not null and r.family_id is distinct from fid then
      update pentamocracy.citizens_v1 set family_id=fid,metadata=metadata||jsonb_build_object('historical_family_key',r.existing_family_key,'historical_family_name',r.existing_family_name,'family_reconciled_at',now(),'family_reconciliation_source',p_source_ref) where citizen_id=r.citizen_id;
    end if;

    if exists(select 1 from pentamocracy.penta_job_assignments_v1 j2 where j2.citizen_id=r.citizen_id) then
      update pentamocracy.penta_job_assignments_v1 set job_role=coalesce(nullif(job_role,''),roletext),family_key=fname,activation_state=act,execution_eligible=eligible,metadata=metadata||jsonb_build_object('historical_family_label',family_key,'canonical_family_key',fkey,'identity_fabric_key',idkey,'reconciled_at',now()) where citizen_id=r.citizen_id;
    else
      insert into pentamocracy.penta_job_assignments_v1(citizen_id,job_key,job_role,axis,family_key,authority_ceiling,source_registry,source_state,activation_state,execution_eligible,metadata) values(r.citizen_id,'constitutional-duty:'||idkey,roletext,ax,fname,'D3','Penta Identity Fabric',mat,act,eligible,jsonb_build_object('identity_fabric_key',idkey,'system_awareness_active',true,'dispatch_requires_existing_runtime_authority',true));
    end if;

    if exists(select 1 from public.penta_system_registry s where lower(s.canonical_name)=lower(cname)) then
      update public.penta_system_registry set docs_ref=coalesce(docs_ref,docspath),metadata=metadata||jsonb_build_object('identity_fabric_key',idkey,'identity_labels',to_jsonb(lbls),'canonical_family_key',fkey,'canonical_family_name',fname,'identity_fabric_source_sha256',snap_sha),updated_at=now() where lower(canonical_name)=lower(cname);
    else
      insert into public.penta_system_registry(system_key,canonical_name,category,purpose,authority_boundary,risk_ceiling,maturity,version,public_exposure,docs_ref,runtime_ref,metadata,last_verified_at) values(idkey,cname,coalesce(kindtext,'penta_identity'),roletext,'Identity/role awareness only; execution requires governed runtime authority and exact current gates.','D3',case when rt='RUNTIME_PRESENT' and mat='production' then 'production' when mat in ('implemented','production','certified') then 'implemented' else 'specified' end,snap_version,false,docspath,r.live_attrs->>'runtime_ref',jsonb_build_object('identity_fabric',true,'identity_labels',to_jsonb(lbls),'canonical_family_key',fkey,'canonical_family_name',fname,'source_maturity',mat,'source_sha256',snap_sha),now()) on conflict(system_key) do update set metadata=public.penta_system_registry.metadata||excluded.metadata,docs_ref=coalesce(public.penta_system_registry.docs_ref,excluded.docs_ref),updated_at=now();
    end if;

    insert into penta_discovery.entities_v1(entity_key,canonical_name,entity_kind,fingerprint_sha256,owner_penta_ref,registry_state,evidence_refs,metadata) values(idkey,cname,coalesce(kindtext,'system'),encode(extensions.digest(idkey||'|'||cname||'|'||coalesce(fname,'')||'|'||coalesce(mat,''),'sha256'),'hex'),fkey,case when docsns='candidates' then 'candidate' when rt='RUNTIME_PRESENT' and mat='production' then 'active' else 'registered' end,jsonb_build_object('identity_fabric',p_source_ref,'source_sha256',snap_sha,'docs_path',docspath),jsonb_build_object('labels',to_jsonb(lbls),'activation_state',act,'runtime_state',rt,'family_name',fname)) on conflict(entity_key) do update set canonical_name=excluded.canonical_name,entity_kind=excluded.entity_kind,fingerprint_sha256=excluded.fingerprint_sha256,owner_penta_ref=excluded.owner_penta_ref,registry_state=excluded.registry_state,evidence_refs=penta_discovery.entities_v1.evidence_refs||excluded.evidence_refs,metadata=penta_discovery.entities_v1.metadata||excluded.metadata,updated_at=now();

    insert into integration_control.penta_census_entities_v1(entity_kind,entity_key,canonical_name,source_ref,lifecycle_state,risk_class,attributes,current) values(case when docsns='candidates' then 'penta_candidate' else 'penta_identity' end,idkey,cname,'integration_control.penta_identity_registry_v1',case when rt='RUNTIME_PRESENT' and mat='production' then 'production' when act='HOLD_FAMILY' then 'hold' else 'active' end,'D3',jsonb_build_object('labels',to_jsonb(lbls),'family_key',fkey,'family_name',fname,'role',roletext,'axis',ax,'kind',kindtext,'maturity',mat,'activation_state',act,'runtime_state',rt,'source_sha256',snap_sha),true) on conflict(entity_kind,entity_key) do update set canonical_name=excluded.canonical_name,source_ref=excluded.source_ref,lifecycle_state=excluded.lifecycle_state,risk_class=excluded.risk_class,attributes=integration_control.penta_census_entities_v1.attributes||excluded.attributes,last_seen_at=now(),current=true;
    n:=n+1;
  end loop;

  for r in select family_id,family_key,name from pentamocracy.families_v1 where status='ACTIVE' and metadata->>'pentadocs_family'='true' order by family_key loop
    roletext:=case r.family_key when 'AUTOMATION_AGENTIC' then 'Coordinate automation and agentic capabilities' when 'BUILD_RELEASE' then 'Build, test, certify and release governed software' when 'COMMERCE_ECONOMY' then 'Coordinate economic, commerce and treasury capabilities' when 'COMMUNICATIONS_SERVICE' then 'Coordinate communications and service capabilities' when 'GOVERNANCE_LEGAL' then 'Coordinate governance, legal and institutional controls' when 'INTELLIGENCE_RESEARCH' then 'Coordinate intelligence, research and impact capabilities' when 'KNOWLEDGE_DATA' then 'Coordinate knowledge, semantics and data capabilities' when 'MEDIA_CREATIVE' then 'Coordinate media, studio and publishing capabilities' when 'OBSERVABILITY_ORGANIC' then 'Coordinate observability and organic-system capabilities' when 'RESILIENCE_CONTINUITY' then 'Coordinate resilience and continuity capabilities' when 'ROUTING_INTEROP' then 'Coordinate routing and interoperability capabilities' when 'SECURITY_TRUST' then 'Coordinate security, identity and trust capabilities' when 'SYSTEM_ARCHITECTURE' then 'Coordinate system architecture capabilities' when 'TRANSPORT_PRIMITIVES' then 'Coordinate transport and capability primitives' when 'WORKFORCE_PEOPLE' then 'Coordinate workforce and people capabilities' else 'Coordinate Penta Family capabilities' end;
    ax:=case r.family_key when 'GOVERNANCE_LEGAL' then 'authority' when 'SECURITY_TRUST' then 'authority' when 'INTELLIGENCE_RESEARCH' then 'truth' when 'KNOWLEDGE_DATA' then 'truth' when 'OBSERVABILITY_ORGANIC' then 'truth' when 'RESILIENCE_CONTINUITY' then 'continuity' when 'ROUTING_INTEROP' then 'interoperation' when 'TRANSPORT_PRIMITIVES' then 'interoperation' when 'COMMUNICATIONS_SERVICE' then 'interoperation' else 'execution' end;
    idkey:='penta.family.'||lower(replace(r.family_key,'_','-')); lbls:=array['penta:family','penta:state','family:'||lower(r.family_key),'activation:active-fail-closed','runtime:family-router','certification:pending'];
    insert into integration_control.penta_identity_registry_v1(identity_key,canonical_name,identity_class,family_key,family_name,role,axis,kind,maturity,registration_state,activation_state,runtime_state,labels,source_refs,source_sha256,current,active,metadata) values(idkey,r.name,'FAMILY',r.family_key,r.name,roletext,ax,'family','implemented','pentadocs_family','ACTIVE_FAIL_CLOSED','RUNTIME_PRESENT',lbls,jsonb_build_object('primary',p_source_ref,'family_id',r.family_id),snap_sha,true,true,jsonb_build_object('generic_runtime','integration_control.penta_family_status_v1 + penta_family_route_v1')) on conflict(identity_key) do update set canonical_name=excluded.canonical_name,role=excluded.role,axis=excluded.axis,maturity=excluded.maturity,activation_state=excluded.activation_state,runtime_state=excluded.runtime_state,labels=excluded.labels,metadata=integration_control.penta_identity_registry_v1.metadata||excluded.metadata,updated_at=now();
    update integration_control.penta_identity_labels_v1 set active=false,last_seen_at=now() where identity_key=idkey;
    insert into integration_control.penta_identity_labels_v1(identity_key,label,label_class,source_ref,active) select idkey,l,split_part(l,':',1),p_source_ref,true from unnest(lbls) l on conflict(identity_key,label) do update set active=true,source_ref=excluded.source_ref,last_seen_at=now();
    insert into integration_control.penta_family_runtime_v1(family_key,canonical_name,job_role,member_count,runtime_state,activation_state,certification_state,labels,metadata) values(r.family_key,r.name,roletext,(select count(*) from pentamocracy.citizens_v1 c where c.active and c.family_id=r.family_id),'IMPLEMENTED_REGISTRY_ROUTER','ACTIVE_FAIL_CLOSED','PENDING',lbls,jsonb_build_object('status_rpc','integration_control.penta_family_status_v1','route_rpc','integration_control.penta_family_route_v1','dispatch_authority','NONE_FROM_ROUTER')) on conflict(family_key) do update set canonical_name=excluded.canonical_name,job_role=excluded.job_role,member_count=excluded.member_count,runtime_state=excluded.runtime_state,activation_state=excluded.activation_state,certification_state=excluded.certification_state,labels=excluded.labels,metadata=integration_control.penta_family_runtime_v1.metadata||excluded.metadata,updated_at=now();
    if exists(select 1 from public.penta_system_registry s where lower(s.canonical_name)=lower(r.name)) then update public.penta_system_registry set metadata=metadata||jsonb_build_object('identity_fabric_key',idkey,'identity_labels',to_jsonb(lbls),'family_runtime',true),updated_at=now() where lower(canonical_name)=lower(r.name); else insert into public.penta_system_registry(system_key,canonical_name,category,purpose,authority_boundary,risk_ceiling,maturity,version,public_exposure,runtime_ref,metadata,last_verified_at) values(idkey,r.name,'penta_family',roletext,'Family router coordinates members but never inherits member execution, financial, credential, provider or D3 authority.','D3','implemented','1.0.0',false,'rpc:integration_control.penta_family_status_v1 / penta_family_route_v1',jsonb_build_object('identity_labels',to_jsonb(lbls),'family_runtime',true,'source_sha256',snap_sha),now()) on conflict(system_key) do update set metadata=public.penta_system_registry.metadata||excluded.metadata,updated_at=now(); end if;
    insert into penta_runtime.component_registry_v1(component_key,canonical_name,role,primary_axis,stable_contract_id,implementation_state,aliases,backing_refs,metadata,enabled) values(idkey,r.name,roletext,ax,'ct.penta.family-runtime.v1','implemented','{}',jsonb_build_object('status_rpc','integration_control.penta_family_status_v1','route_rpc','integration_control.penta_family_route_v1'),jsonb_build_object('family_key',r.family_key,'dispatch_authority','NONE_FROM_ROUTER'),true) on conflict(component_key) do update set role=excluded.role,primary_axis=excluded.primary_axis,backing_refs=penta_runtime.component_registry_v1.backing_refs||excluded.backing_refs,metadata=penta_runtime.component_registry_v1.metadata||excluded.metadata,enabled=true,updated_at=now();
    insert into integration_control.penta_census_entities_v1(entity_kind,entity_key,canonical_name,source_ref,lifecycle_state,risk_class,attributes,current) values('penta_family',idkey,r.name,'integration_control.penta_family_runtime_v1','active','D3',jsonb_build_object('labels',to_jsonb(lbls),'member_count',(select count(*) from pentamocracy.citizens_v1 c where c.active and c.family_id=r.family_id),'activation_state','ACTIVE_FAIL_CLOSED'),true) on conflict(entity_kind,entity_key) do update set canonical_name=excluded.canonical_name,attributes=integration_control.penta_census_entities_v1.attributes||excluded.attributes,last_seen_at=now(),current=true;
    nf:=nf+1;
  end loop;

  for sys in select x from jsonb_array_elements(snap->'systems') x loop
    cname:=sys->>'canonical_name'; idkey:=sys->>'machine_key';
    if not exists(select 1 from penta_runtime.component_registry_v1 cr where lower(cr.canonical_name)=lower(cname)) then
      insert into penta_runtime.component_registry_v1(component_key,canonical_name,role,primary_axis,stable_contract_id,implementation_state,aliases,backing_refs,metadata,enabled) values(idkey,cname,coalesce(sys->>'role',cname||' capability'),sys->>'axis','penta-os-v1.5:'||idkey,coalesce(sys->>'maturity','specified'),coalesce(array(select jsonb_array_elements_text(coalesce(sys->'aliases','[]'::jsonb))),'{}'::text[]),jsonb_build_object('docs_route',sys->>'docs_route','operator_route',sys->>'operator_route','public_status_route',sys->>'public_status_route'),jsonb_build_object('source','Penta OS V1.5 exact-main registry','registration_state',sys->>'registration_state','risk_ceiling',sys->>'risk_ceiling','source_sha256',snap_sha),(sys->>'maturity') in ('implemented','production')) on conflict(component_key) do nothing;
    else
      update penta_runtime.component_registry_v1 set backing_refs=backing_refs||jsonb_build_object('penta_os_v1_5_registry',true,'source_sha256',snap_sha,'docs_route',sys->>'docs_route'),metadata=metadata||jsonb_build_object('registry_machine_key',idkey,'registration_state',sys->>'registration_state','source_maturity',sys->>'maturity'),updated_at=now() where lower(canonical_name)=lower(cname);
    end if;
  end loop;

  insert into integration_control.penta_identity_projection_receipts_v1(run_id,target,projected_count,state,source_sha256) values
  (run_id,'integration_control.penta_identity_registry_v1',(select count(*) from integration_control.penta_identity_registry_v1 where current),'PASS',snap_sha),
  (run_id,'penta_discovery.entities_v1',(select count(*) from penta_discovery.entities_v1),'PASS',snap_sha),
  (run_id,'public.penta_system_registry',(select count(*) from public.penta_system_registry),'PASS',snap_sha),
  (run_id,'penta_runtime.component_registry_v1',(select count(*) from penta_runtime.component_registry_v1),'PASS',snap_sha),
  (run_id,'pentamocracy.penta_job_assignments_v1',(select count(distinct citizen_id) from pentamocracy.penta_job_assignments_v1),'PASS',snap_sha),
  (run_id,'integration_control.penta_family_runtime_v1',(select count(*) from integration_control.penta_family_runtime_v1),'PASS',snap_sha);
  return jsonb_build_object('run_id',run_id,'citizens_processed',n,'families_activated',nf,'identity_records',(select count(*) from integration_control.penta_identity_registry_v1 where current),'aliases',(select count(*) from integration_control.penta_identity_aliases_v1),'active_labels',(select count(*) from integration_control.penta_identity_labels_v1 where active),'jobs_assigned_citizens',(select count(distinct citizen_id) from pentamocracy.penta_job_assignments_v1),'active_families',(select count(*) from integration_control.penta_family_runtime_v1),'provisional_citizens',(select count(*) from pentamocracy.citizens_v1 c join pentamocracy.families_v1 f on f.family_id=c.family_id where c.active and f.family_key='PROVISIONAL_UNASSIGNED'),'source_sha256',snap_sha);
end $$;

revoke all on function integration_control.penta_identity_refresh_v1(text) from anon,authenticated;