insert into penta_self.capability_registry_v1(capability_key,canonical_name,purpose,handler_ref,action_mode,max_risk_class,reversible_required,verification_required,enabled,metadata)
values
('provider.google.drive.oauth.read','Google Drive OAuth Read','Read governed Drive files/folders through OAuth/service identity or connected user connector.','connector.google-drive','observational','D1',false,true,true,jsonb_build_object('provider','Google','service','drive.googleapis.com','provider_state','ENABLED','certification','PASS')),
('provider.google.drive.oauth.write','Google Drive OAuth Write','Perform bounded Drive file/folder mutations with governed readback.','connector.google-drive','direct_bounded','D2',true,true,true,jsonb_build_object('provider','Google','service','drive.googleapis.com','provider_state','ENABLED','certification','PASS')),
('provider.google.sheets.oauth.read','Google Sheets OAuth Read','Read private native Google Sheets through OAuth/service-account authorization.','edge:thrivebase-sheets-mirror-v1','observational','D1',false,true,true,jsonb_build_object('provider','Google','service','sheets.googleapis.com','provider_state','ENABLED','certification','PASS','canary_spreadsheet_id_sha256',encode(extensions.digest('110EHdAYkSMRv31BzeCd4skD0wenHiNkUR8NHYw9Uk_I','sha256'),'hex'))),
('provider.google.sheets.oauth.write','Google Sheets OAuth Write','Write private native Google Sheets through OAuth/service-account authorization with independent readback.','edge:thrivebase-sheets-mirror-v1','direct_bounded','D2',true,true,true,jsonb_build_object('provider','Google','service','sheets.googleapis.com','provider_state','ENABLED','certification','PASS','service_identity_write_observed',true,'independent_connector_readback_pass',true,'mirror_orchestrator_state','HOLD_BOOTSTRAP_TERMINAL_PATH')),
('provider.google.sheets.create.user_owned','Google Sheets User-Owned Provisioning','Create user-owned native Sheets, move into governed Drive folders, then bind service identity for machine population/readback.','connector.google-drive + rpc:thrivebase_sheet_mirror_record_provision_v1','delegated','D2',true,true,true,jsonb_build_object('ownership_model','USER_OWNED_SERVICE_WRITER','certification','PASS','service_owned_creation_not_required',true)),
('provider.google.sheets.create.service_owned','Google Sheets Service-Owned Provisioning','Create native Sheets directly owned by the ThriveBase service identity.','edge:thrivebase-sheets-create-probe-v1','delegated','D2',true,true,false,jsonb_build_object('state','HOLD_PROVIDER_QUOTA','provider_http_status',403,'reason','SERVICE_IDENTITY_DRIVE_STORAGE_QUOTA')),
('provider.google.serviceusage.read','Google Service Usage Read','Read enabled Google Cloud APIs for capability discovery and drift reconciliation.','edge:google-cloud-control-plane','observational','D1',false,true,true,jsonb_build_object('enabled_service_count',96,'certification','PASS')),
('provider.google.api_keys.inspect','Google API Keys Inspect','Inspect API-key metadata/restrictions without exporting key strings.','edge:google-api-keys-control','observational','D1',false,true,false,jsonb_build_object('service','apikeys.googleapis.com','provider_state','ENABLED','state','HOLD_IAM','granted_permissions',0,'required_permission','apikeys.keys.list')),
('provider.google.api_keys.rotate','Google API Keys Governed Rotation','Create/restrict/bind/verify/supersede Google API keys using overlap rotation and immutable lineage.','edge:google-api-keys-control','human_reserved','D3',true,true,false,jsonb_build_object('service','apikeys.googleapis.com','provider_state','ENABLED','state','HOLD_IAM_D3','fresh_chlom_invocation_required',true,'rotation_order',jsonb_build_array('create_new','apply_restrictions','bind_consumers','verify_readback','supersede_old','retire_old_after_overlap')))
on conflict(capability_key) do update set canonical_name=excluded.canonical_name,purpose=excluded.purpose,handler_ref=excluded.handler_ref,action_mode=excluded.action_mode,max_risk_class=excluded.max_risk_class,reversible_required=excluded.reversible_required,verification_required=excluded.verification_required,enabled=excluded.enabled,metadata=penta_self.capability_registry_v1.metadata||excluded.metadata,updated_at=now();

insert into integration_control.penta_adapter_registry_v2(adapter_id,display_name,provider_name,adapter_class,transport,penta_wire_service_id,required_by_factories,capabilities,authority_ceiling,direct_tool_count,active_tool_count,intentionally_gated_tool_count,retired_tool_count,exact_contract_state,certification_state,state,packet_enabled,mutation_enabled,auto_enable_allowed,last_probe_state,last_http_status,last_reconciled_at,evidence)
values('wire.google-sheets-oauth','Google Sheets OAuth / Living Mirror Adapter','Google','provider','HYBRID','google_sheets',array['PentaDrive','PentaFactory','PentaCensus'],array['sheet.read','sheet.write','sheet.user_owned.create','sheet.readback'],'D2',4,4,0,0,'pass','pass','production_active',true,true,false,'pass',200,now(),jsonb_build_object('sheets_api_enabled',true,'drive_api_enabled',true,'auth_model','OAuth/service account + connected user provisioning','service_write_observed',true,'independent_readback_pass',true,'service_owned_create_state','HOLD_PROVIDER_QUOTA','mirror_orchestrator_state','HOLD_BOOTSTRAP_TERMINAL_PATH','enabled_google_services',96))
on conflict(adapter_id) do update set capabilities=excluded.capabilities,authority_ceiling=excluded.authority_ceiling,direct_tool_count=excluded.direct_tool_count,active_tool_count=excluded.active_tool_count,intentionally_gated_tool_count=excluded.intentionally_gated_tool_count,exact_contract_state=excluded.exact_contract_state,certification_state=excluded.certification_state,state=excluded.state,packet_enabled=excluded.packet_enabled,mutation_enabled=excluded.mutation_enabled,auto_enable_allowed=excluded.auto_enable_allowed,last_probe_state=excluded.last_probe_state,last_http_status=excluded.last_http_status,last_reconciled_at=excluded.last_reconciled_at,evidence=integration_control.penta_adapter_registry_v2.evidence||excluded.evidence,updated_at=now();

update integration_control.penta_adapter_registry_v2 set authority_ceiling='D3',capabilities=array['permissions.test','keys.list','candidate.classify','keys.create','keys.patch','keys.delete'],direct_tool_count=6,active_tool_count=1,intentionally_gated_tool_count=5,exact_contract_state='pass',certification_state='hold',state='certification_pending',packet_enabled=true,mutation_enabled=false,auto_enable_allowed=false,last_probe_state='hold',last_http_status=403,last_reconciled_at=now(),evidence=evidence||jsonb_build_object('api_enabled',true,'iam_permissions_granted',0,'iam_hold','apikeys.keys.list and mutation permissions absent','rotation_state','HOLD_IAM_D3','fresh_d3_required',true,'key_strings_returned',false,'reconciled_at',now()),updated_at=now() where adapter_id='wire.google-cloud-api-keys-admin';

update integration_control.penta_adapter_registry_v2 set exact_contract_state='pass',last_probe_state='pass',last_http_status=200,last_reconciled_at=now(),evidence=evidence||jsonb_build_object('serviceusage_read_pass',true,'enabled_google_services',96,'drive_api_enabled',true,'sheets_api_enabled',true,'apikeys_api_enabled',true,'reconciled_at',now()),updated_at=now() where adapter_id='wire.google-cloud-iam-control';
