create table if not exists chlom_runtime.construction_work_queue (
  work_id text primary key,
  workstream text not null,
  canonical_name text not null,
  scope_type text not null check (scope_type in ('protocol','module','platform','binding','agent','algorithm','oracle','release','paper')),
  scope_id text not null,
  priority integer not null check(priority between 1 and 999),
  owner_agent_id text not null references chlom_runtime.agent_templates(agent_id) on delete restrict,
  verifier_agent_id text not null references chlom_runtime.agent_templates(agent_id) on delete restrict,
  depends_on text[] not null default '{}',
  closes_gates text[] not null default '{}',
  required_outputs jsonb not null default '{}'::jsonb,
  state text not null default 'ready' check(state in ('ready','running','waiting','blocked','verifying','done','superseded')),
  blocker_reason text,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(owner_agent_id <> verifier_agent_id)
);
create index if not exists idx_chlom_work_queue_state_priority on chlom_runtime.construction_work_queue(state,priority,work_id);
revoke all on chlom_runtime.construction_work_queue from public,anon,authenticated;

insert into chlom_runtime.construction_work_queue(work_id,workstream,canonical_name,scope_type,scope_id,priority,owner_agent_id,verifier_agent_id,depends_on,closes_gates,required_outputs,state,evidence)
values
('CW-001','source-control','Private CHLOM Implementation Repository','protocol','ct.framework.chlom',1,'ct.chlom.agent.developer','ct.chlom.agent.security',array[]::text[],array['CG-011','CG-012','CG-052','CG-054'],jsonb_build_object('outputs',jsonb_build_array('private_repo','AGENTS.md','CURRENT_STATE.md','HANDOFF.md','ADR tree','migrations','Rust workspace','contracts','tests','SBOM workflow')),'ready','{}'),
('CW-002','kernel','Rust CHLOM Kernel Workspace','module','ct.chlom.kernel',2,'ct.chlom.agent.kernel','ct.chlom.agent.release-certifier',array['CW-001'],array['CG-004','CG-005','CG-006','CG-012','CG-013','CG-014'],jsonb_build_object('outputs',jsonb_build_array('Cargo workspace','kernel router','typed IDs','authority hooks','event envelope','error contract')),'waiting','{}'),
('CW-003','rights','Rights and Version Graph Runtime','module','ct.chlom.rights',3,'ct.chlom.agent.ip-licensing','ct.chlom.agent.security',array['CW-002'],array['CG-006','CG-012','CG-014','CG-029','CG-048'],jsonb_build_object('outputs',jsonb_build_array('asset/version graph','rights intervals','contributor claims','evidence refs','conflict queries')),'waiting','{}'),
('CW-004','licensing','DLA Runtime and State Machine','module','ct.chlom.dla',4,'ct.chlom.agent.dla','ct.chlom.agent.security',array['CW-003'],array['CG-015','CG-016','CG-029','CG-030'],jsonb_build_object('outputs',jsonb_build_array('DLA schema','state machine','license templates','suspension','revocation','supersession','verification')),'waiting','{}'),
('CW-005','licensing','DLA Multidimensional Conflict Engine','algorithm','ct.alg.chlom.dla-conflict.v1',5,'ct.chlom.agent.dla','ct.chlom.agent.tevv',array['CW-003','CW-004'],array['CG-015','CG-028','CG-030'],jsonb_build_object('outputs',jsonb_build_array('territory/time/media/right interval conflict detector','property tests','negative cases')),'waiting','{}'),
('CW-006','market','LEX Discovery RFQ Quote and Offer Runtime','module','ct.chlom.lex',6,'ct.chlom.agent.lex','ct.chlom.agent.security',array['CW-004'],array['CG-006','CG-014','CG-031'],jsonb_build_object('outputs',jsonb_build_array('listings','RFQ','quotes','offers','eligibility','rights-aware search')),'waiting','{}'),
('CW-007','remedies','Dispute Remedies Appeals Runtime','module','ct.chlom.disputes',7,'ct.chlom.agent.dispute','ct.chlom.agent.ip-licensing',array['CW-003','CW-004'],array['CG-032'],jsonb_build_object('outputs',jsonb_build_array('holds','case evidence','decision','remedy','appeal','restoration','correction without erasure')),'waiting','{}'),
('CW-008','policy','ACE Deterministic Policy Engine and DSL','module','ct.chlom.ace',8,'ct.chlom.agent.ace','ct.chlom.agent.security',array['CW-002','CW-003'],array['CG-006','CG-014','CG-023','CG-024'],jsonb_build_object('outputs',jsonb_build_array('policy DSL','versioned packs','dry-run','explanations','deny>hold>allow precedence','rollback')),'waiting','{}'),
('CW-009','oracle','Signed Oracle Observation Pipeline','module','ct.chlom.oracle-fabric',9,'ct.chlom.agent.oracle','ct.chlom.agent.blockchain-crypto',array['CW-002'],array['CG-026'],jsonb_build_object('outputs',jsonb_build_array('signed observations','freshness','source authority','weighted median','quorum','divergence','failover')),'waiting','{}'),
('CW-010','ai-ml','AIE Feature Store and Evaluation Pipeline','module','ct.chlom.aie',10,'ct.chlom.agent.aie','ct.chlom.agent.tevv',array['CW-008','CW-009'],array['CG-027','CG-028'],jsonb_build_object('outputs',jsonb_build_array('feature registry','dataset lineage','baseline rules','anomaly ensemble','graph risk','model cards','shadow/canary','drift')),'waiting','{}'),
('CW-011','identity','Credential and Key Lifecycle Hardening','module','ct.chlom.credentials',11,'ct.chlom.agent.identity','ct.chlom.agent.security',array['CW-001'],array['CG-008','CG-009','CG-023'],jsonb_build_object('outputs',jsonb_build_array('credential lifecycle','key rotation','revocation','recovery','scoped attestations','privacy boundaries')),'waiting','{}'),
('CW-012','privacy','ZKX Circuit Laboratory','module','ct.chlom.zkx',12,'ct.chlom.agent.zkx','ct.chlom.agent.blockchain-crypto',array['CW-011','CW-008'],array['CG-043'],jsonb_build_object('outputs',jsonb_build_array('proof-of-license circuit','credential proof','witness handling','verifier benchmarks','scheme ADR')),'waiting','{}'),
('CW-013','chain','Polkadot SDK Solo-Chain Bootstrap','module','ct.chlom.chain-adapters',13,'ct.chlom.agent.chain','ct.chlom.agent.blockchain-crypto',array['CW-001','CW-002'],array['CG-039','CG-041'],jsonb_build_object('outputs',jsonb_build_array('Rust node','chain spec','multi-validator local testnet','finality tests','node-loss recovery','readback')),'waiting','{}'),
('CW-014','chain','CHLOM Substrate Runtime Pallets','protocol','ct.framework.chlom',14,'ct.chlom.agent.chain','ct.chlom.agent.security',array['CW-013','CW-003','CW-004','CW-008','CW-009'],array['CG-015','CG-016','CG-039'],jsonb_build_object('outputs',jsonb_build_array('identity pallet','DAIL anchor pallet','rights attestation pallet','DLA reference pallet','policy pallet','oracle pallet','governance test pallet')),'waiting','{}'),
('CW-015','chain','Solidity EVM Test Anchor Suite','module','ct.chlom.chain-adapters',15,'ct.chlom.agent.chain','ct.chlom.agent.security',array['CW-001','CW-002'],array['CG-040','CG-041'],jsonb_build_object('outputs',jsonb_build_array('anchor registry','version registry','license attestation registry','Foundry tests','fuzz/invariants','Slither','testnet readback')),'waiting','{}'),
('CW-016','economics','tCHLOM Test Token and Governance Lock','protocol','ct.framework.chlom',16,'ct.chlom.agent.tokenomics-treasury','ct.chlom.agent.blockchain-crypto',array['CW-013','CW-015'],array['CG-036','CG-038','CG-057'],jsonb_build_object('outputs',jsonb_build_array('1B max test supply','test allocations','vesting simulation','veCHLOM lock','staking/bonding simulation','zero-real-value disclosure')),'waiting','{}'),
('CW-017','economics','Tokenomics Monte Carlo Simulator','algorithm','ct.alg.chlom.tokenomics-monte-carlo.v1',17,'ct.chlom.agent.tokenomics-treasury','ct.chlom.agent.finance-tax',array['CW-016'],array['CG-028','CG-036'],jsonb_build_object('outputs',jsonb_build_array('1k/10k/100k/1m user scenarios','treasury runway','concentration','fees','staking','creator economics','attack simulations')),'waiting','{}'),
('CW-018','treasury','Smart Treasury Test Laboratory','module','ct.chlom.treasury',18,'ct.chlom.agent.tokenomics-treasury','ct.chlom.agent.finance-tax',array['CW-016','CW-017'],array['CG-035','CG-036','CG-038'],jsonb_build_object('outputs',jsonb_build_array('fee router','test royalties','reserve rules','multisig simulation','timelock','test slashing')),'waiting','{}'),
('CW-019','settlement','Settlement ADE and Royalty Conservation','module','ct.chlom.settlement',19,'ct.chlom.agent.commerce','ct.chlom.agent.finance-tax',array['CW-004','CW-018'],array['CG-015','CG-033','CG-035'],jsonb_build_object('outputs',jsonb_build_array('agreement','entitlement','usage','royalty accrual','split conservation','reconciliation')),'waiting','{}'),
('CW-020','developer','OpenAPI SDK and MCP Transport Certification','module','ct.chlom.api-mcp',20,'ct.chlom.agent.developer','ct.chlom.agent.security',array['CW-002','CW-008'],array['CG-023','CG-024','CG-052'],jsonb_build_object('outputs',jsonb_build_array('OpenAPI','Rust SDK','TypeScript SDK','Python SDK','core MCP external auth test','gate MCP transport','negative authorization tests')),'waiting','{}'),
('CW-021','observability','OpenTelemetry Dashboards and SLOs','module','ct.chlom.observability',21,'ct.chlom.agent.sre','ct.chlom.agent.release-certifier',array['CW-002'],array['CG-018','CG-022'],jsonb_build_object('outputs',jsonb_build_array('traces','metrics','logs','correlation IDs','SLOs','alerts','capacity dashboard')),'waiting','{}'),
('CW-022','resilience','Bounded Self-Healing Remediation Engine','module','ct.chlom.agent-fabric',22,'ct.chlom.agent.sre','ct.chlom.agent.security',array['CW-021'],array['CG-019','CG-025','CG-049'],jsonb_build_object('outputs',jsonb_build_array('root-cause classifier','remedy catalog','circuit breakers','approved failover','canary','auto rollback','DAIL repair evidence')),'waiting','{}'),
('CW-023','assurance','Chaos Red-Team and Formal Verification Suite','protocol','ct.framework.chlom',23,'ct.chlom.agent.red-team','ct.chlom.agent.release-certifier',array['CW-004','CW-008','CW-009','CW-013','CW-015','CW-019','CW-022'],array['CG-015','CG-016','CG-021','CG-049'],jsonb_build_object('outputs',jsonb_build_array('TLA+ specs','fuzzing','privilege escalation','oracle fraud','DAIL tamper','governance capture','node failures','DB failures','agent failures')),'waiting','{}'),
('CW-024','integration','Virality Music End-to-End CHLOM Pilot','platform','ct.platform.virality-music',24,'ct.chlom.agent.vm-integration','ct.chlom.agent.release-certifier',array['CW-003','CW-004','CW-006','CW-008','CW-019','CW-020'],array['CG-029','CG-030','CG-033','CG-044','CG-047','CG-048'],jsonb_build_object('outputs',jsonb_build_array('music master','book','printable','character package','commercial license','superseded work','Credits transaction','tCHLOM simulation','verification','correction')),'waiting','{}'),
('CW-025','integration','KJV/Sermon Toolkit End-to-End CHLOM Pilot','platform','ct.platform.kjv-sermon-toolkit',25,'ct.chlom.agent.kjv-integration','ct.chlom.agent.release-certifier',array['CW-003','CW-004','CW-008','CW-019','CW-020'],array['CG-029','CG-030','CG-033','CG-045','CG-047','CG-048'],jsonb_build_object('outputs',jsonb_build_array('original contribution rights distinctions','fingerprint','DLA','Credits entitlement','verification','correction')),'waiting','{}'),
('CW-026','integration','Third-Party Creator Gated Beta','protocol','ct.framework.chlom',26,'ct.chlom.agent.creator-beta','ct.chlom.agent.security',array['CW-024','CW-025','CW-007'],array['CG-046','CG-047'],jsonb_build_object('outputs',jsonb_build_array('creator DID','rights assertion','evidence','conflict review','DLA','LEX','commerce','dispute','appeal')),'waiting','{}'),
('CW-027','commercial','CHLOM SaaS API and Licensing Monetization','protocol','ct.framework.chlom',27,'ct.chlom.agent.commerce','ct.chlom.agent.finance-tax',array['CW-024','CW-025','CW-020'],array['CG-033','CG-034','CG-035','CG-047','CG-055'],jsonb_build_object('outputs',jsonb_build_array('Sandbox','Creator','Pro','Studio','Enterprise','API metering','verification fees','license issuance fees','Credits-first checkout','disclosures')),'waiting','{}'),
('CW-028','legal','Production Crypto Mainnet Gate Packet','release','ct.release.chlom.mainnet',28,'ct.chlom.agent.legal-regulatory','ct.chlom.agent.release-certifier',array['CW-016','CW-017','CW-018','CW-023'],array['CG-037','CG-038','CG-050','CG-055','CG-057'],jsonb_build_object('outputs',jsonb_build_array('securities','commodities','AML/KYC','OFAC','money transmission','tax','custody','consumer','staking','marketing','jurisdiction availability')),'waiting','{}'),
('CW-029','documentation','CHLOM Public and Restricted Paper Suite','paper','ct.paper-suite.chlom',29,'ct.chlom.agent.docs','ct.chlom.agent.ip-licensing',array['CW-003','CW-008','CW-010','CW-017','CW-023'],array['CG-051','CG-052','CG-055'],jsonb_build_object('outputs',jsonb_build_array('whitepaper','technical paper','tokenomics paper','rights paper','AI/ML paper','agent paper','oracle paper','security paper','VM case study','KJV case study','restricted Gold/Black technical papers')),'waiting','{}'),
('CW-030','continuity','Reproducible Bootstrap Restore and Disaster Drill','protocol','ct.framework.chlom',30,'ct.chlom.agent.recovery','ct.chlom.agent.release-certifier',array['CW-001','CW-020','CW-021'],array['CG-020','CG-052','CG-053','CG-054'],jsonb_build_object('outputs',jsonb_build_array('fresh bootstrap','schema restore','secret-reference restore','Drive readback','repo reconstruction','runbook','RTO/RPO evidence')),'waiting','{}'),
('CW-031','release','Staged CHLOM Certification Canary','release','ct.release.chlom.staged',31,'ct.chlom.agent.release-certifier','ct.chlom.agent.security',array['CW-023','CW-024','CW-025','CW-030'],array['CG-049','CG-051','CG-052','CG-053','CG-056'],jsonb_build_object('outputs',jsonb_build_array('staged release packet','independent readback','rollback proof','monitoring','DAIL certification')),'waiting','{}'),
('CW-032','release','Production CHLOM Certification','release','ct.release.chlom.production',32,'ct.chlom.agent.release-certifier','ct.chlom.agent.security',array['CW-027','CW-028','CW-031'],array['CG-050','CG-055','CG-056','CG-057','CG-058'],jsonb_build_object('outputs',jsonb_build_array('production artifact SHA','approvals','readback','security','legal','economics','rollback','monitoring','DAIL production release event')),'waiting','{}')
on conflict (work_id) do update set
 workstream=excluded.workstream,canonical_name=excluded.canonical_name,scope_type=excluded.scope_type,scope_id=excluded.scope_id,
 priority=excluded.priority,owner_agent_id=excluded.owner_agent_id,verifier_agent_id=excluded.verifier_agent_id,depends_on=excluded.depends_on,
 closes_gates=excluded.closes_gates,required_outputs=excluded.required_outputs,
 state=case when chlom_runtime.construction_work_queue.state='done' then 'done' else excluded.state end,
 updated_at=now();

create or replace function public.chlom_construction_work_queue_snapshot()
returns jsonb language sql stable security definer set search_path to 'pg_catalog','chlom_runtime'
as $$
select jsonb_build_object('work',coalesce(jsonb_agg(jsonb_build_object(
 'work_id',work_id,'workstream',workstream,'canonical_name',canonical_name,'scope_type',scope_type,'scope_id',scope_id,
 'priority',priority,'owner_agent_id',owner_agent_id,'verifier_agent_id',verifier_agent_id,'depends_on',depends_on,
 'closes_gates',closes_gates,'required_outputs',required_outputs,'state',state,'blocker_reason',blocker_reason,'updated_at',updated_at
) order by priority,work_id),'[]'::jsonb),'generated_at',now()) from chlom_runtime.construction_work_queue where state <> 'superseded'
$$;
revoke all on function public.chlom_construction_work_queue_snapshot() from public,anon,authenticated;
grant execute on function public.chlom_construction_work_queue_snapshot() to service_role;

insert into integration_control.mcp_tools(tool_name,service_id,operation_key,risk_class,enabled,requires_human_approval,input_schema,output_schema,notes)
values('chlom.build.queue','chlom_core','build.queue','D0',true,false,'{"type":"object","additionalProperties":false}'::jsonb,'{"type":"object"}'::jsonb,'Read the CHLOM machine construction queue, dependencies, gate targets and assigned independent owner/verifier agents.')
on conflict(tool_name) do update set service_id=excluded.service_id,operation_key=excluded.operation_key,risk_class=excluded.risk_class,enabled=true,requires_human_approval=false,input_schema=excluded.input_schema,output_schema=excluded.output_schema,notes=excluded.notes,updated_at=now();
insert into chlom_runtime.mcp_tool_exposure(tool_name,server_id,enabled,exposure_state,minimum_authority)
values('chlom.build.queue','ct.mcp.chlom-gates',true,'test','D0')
on conflict(tool_name) do update set server_id=excluded.server_id,enabled=true,exposure_state='test',minimum_authority='D0',updated_at=now();