insert into chlom_runtime.construction_gate_definitions
(gate_id,gate_family,canonical_name,description,required_for_stages,scope_types,applies_to_module_classes,risk_class,d3_human_reserved,specialist_domains,auto_evaluable,evaluation_method,sequence_no,metadata)
values
('CG-001','source','Source Authority','Canonical sources are reconciled, current authority is known, and historical/target material is not flattened into production state.',array['specified','prototype','test','staged','production','maintained'],array['module','platform','protocol','release','paper'],array[]::text[],'D1',false,array[]::text[],false,'source_registry_and_adjudication',1,'{}'),
('CG-002','identity','Stable Identity & Namespace','Stable CHLOM IDs, typed identities, version namespaces, predecessor/successor links and collision controls exist.',array['specified','prototype','test','staged','production','maintained'],array['module','platform','protocol','agent','algorithm','oracle','release','paper'],array[]::text[],'D1',false,array[]::text[],true,'stable_id_registry',2,'{}'),
('CG-003','terminology','Terminology & Lineage','Canonical terminology, historical aliases and acronym drift are resolved without rewriting source history.',array['specified','prototype','test','staged','production','maintained'],array['module','protocol','paper'],array[]::text[],'D1',false,array[]::text[],false,'terminology_lineage',3,'{}'),
('CG-004','architecture','Architecture Specification','Versioned architecture, boundaries, invariants, interfaces and failure semantics are documented.',array['specified','prototype','test','staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D1',false,array[]::text[],false,'architecture_adr',4,'{}'),
('CG-005','architecture','Dependency Graph','Upstream/downstream dependencies, replacement strategy, failure modes and circularity checks are explicit.',array['specified','prototype','test','staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D1',false,array[]::text[],true,'module_dependency_graph',5,'{}'),
('CG-006','data','Schema & Contract','Data, event, API and state-machine schemas are versioned, validated and migration-safe.',array['prototype','test','staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array[]::text[],false,'schema_validation',6,'{}'),
('CG-007','authority','Authority / RBAC','Least privilege, autonomy class, environment scope, approval class and separation of duties are enforceable.',array['prototype','test','staged','production','maintained'],array['module','platform','protocol','agent','release'],array[]::text[],'D2',false,array['security_privacy']::text[],false,'authority_matrix',7,'{}'),
('CG-008','security','Secret & Key Custody','Secrets/private keys are server-side, vault/KMS-backed, rotatable, non-exported and recovery-controlled.',array['prototype','test','staged','production','maintained'],array['module','platform','protocol','agent','oracle','release'],array[]::text[],'D3',true,array['security_privacy','blockchain_crypto']::text[],false,'vault_kms_custody',8,'{}'),
('CG-009','privacy','Privacy & Data Classification','Data classes, PII handling, minimization, retention, public/private boundaries and privacy impact are defined.',array['prototype','test','staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array['security_privacy','legal_regulatory']::text[],false,'privacy_data_impact',9,'{}'),
('CG-010','security','Threat Model','Abuse cases, threat actors, trust boundaries, mitigations, kill switches and residual risks are documented and tested.',array['test','staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array['security_privacy']::text[],false,'threat_model',10,'{}'),
('CG-011','security','Supply Chain / SBOM','Dependencies, exact versions, licenses, integrity, vulnerability state, SBOM and exit options are controlled.',array['test','staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array['security_privacy']::text[],false,'sbom_dependency_scan',11,'{}'),
('CG-012','implementation','Implementation Artifact','Executable implementation exists at a pinned SHA/package/version; documentation alone is not accepted as proof.',array['prototype','test','staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array[]::text[],true,'implementation_ref',12,'{}'),
('CG-013','testing','Unit Tests','Deterministic unit tests cover success, failure, boundary and negative cases.',array['test','staged','production','maintained'],array['module','protocol','release'],array[]::text[],'D2',false,array[]::text[],true,'unit_test_evidence',13,'{}'),
('CG-014','testing','Integration Tests','Cross-module, database, API, MCP, chain and platform integration paths are exercised where applicable.',array['test','staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array[]::text[],true,'integration_test_evidence',14,'{}'),
('CG-015','testing','Property / Fuzz / Invariant Tests','Property, fuzz, replay, idempotency and invariant tests exist for stateful/security-critical components.',array['test','staged','production','maintained'],array['module','protocol','release'],array[]::text[],'D2',false,array['security_privacy']::text[],false,'property_fuzz_invariant',15,'{}'),
('CG-016','assurance','Formal Invariants','Critical state machines and conservation/authority properties are formally specified or explicitly justified as not applicable.',array['staged','production','maintained'],array['module','protocol','release'],array['kernel','dail','dla','lex','settlement','treasury','governance','pallet']::text[],'D2',false,array['security_privacy','blockchain_crypto']::text[],false,'formal_methods',16,'{}'),
('CG-017','evidence','DAIL Evidence','Material changes, tests, approvals, corrections and releases are append-recorded with hash-linked evidence.',array['test','staged','production','maintained'],array['module','platform','protocol','agent','algorithm','oracle','release','paper'],array[]::text[],'D2',false,array[]::text[],true,'dail_integrity',17,'{}'),
('CG-018','operations','Observability & SLO','Health, metrics, logs/traces, correlation IDs, SLOs and alert thresholds are defined and measured.',array['test','staged','production','maintained'],array['module','platform','protocol','agent','oracle','release'],array[]::text[],'D2',false,array['operations_sre']::text[],false,'health_slo_evidence',18,'{}'),
('CG-019','resilience','Rollback & Self-Healing','Rollback, canary, compensating action and bounded self-healing behavior exist and cannot escalate authority.',array['test','staged','production','maintained'],array['module','platform','protocol','agent','release'],array[]::text[],'D2',false,array['operations_sre','security_privacy']::text[],false,'rollback_self_heal',19,'{}'),
('CG-020','resilience','Backup & Restore','Backup, independent recovery copy, restore procedure, checksum and restore drill evidence exist.',array['test','staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array['operations_sre','security_privacy']::text[],true,'backup_restore_status',20,'{}'),
('CG-021','resilience','Chaos & Failure Injection','Relevant node, API, DB, oracle, queue, cache, agent and network failures have been injected safely and recovered.',array['staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array['operations_sre','security_privacy']::text[],false,'chaos_suite',21,'{}'),
('CG-022','performance','Performance & Capacity','Latency, throughput, concurrency, storage, rate, cost and saturation limits are benchmarked against explicit targets.',array['staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array['operations_sre']::text[],false,'benchmark_capacity',22,'{}'),
('CG-023','developer','API Contract','Versioned API/OpenAPI contract, auth, errors, idempotency, rate limits and independent readback are certified.',array['test','staged','production','maintained'],array['module','platform','protocol','release'],array['api_mcp','kernel','identity','fingerprint','credentials','rights_graph','dla','dail','lex','dispute','settlement','treasury','oracle','ace','aie','zkx']::text[],'D2',false,array['security_privacy']::text[],false,'api_contract',23,'{}'),
('CG-024','developer','MCP Contract','Versioned MCP discovery/tool schemas, scoped auth, authority ceilings, audit and fail-closed unsupported operations are certified.',array['test','staged','production','maintained'],array['module','platform','protocol','release'],array['api_mcp','kernel','identity','fingerprint','dail','agent_fabric','oracle','ace','aie','rights_graph','dla','lex']::text[],'D2',false,array['security_privacy','ai_ml_tevv']::text[],false,'mcp_contract',24,'{}'),
('CG-025','agents','Agent Identity / Heartbeat','Registered agent identity, parentage, authority, tool scope, heartbeat, evaluation and replacement continuity are active.',array['test','staged','production','maintained'],array['module','agent','protocol','release'],array['agent_fabric','api_mcp']::text[],'D2',false,array['ai_ml_tevv','security_privacy']::text[],true,'agent_registry_health',25,'{}'),
('CG-026','oracles','Oracle Assurance','Oracle identity, source authority, signatures, freshness, quorum/divergence, slashing/reputation policy and failover are tested.',array['test','staged','production','maintained'],array['module','oracle','protocol','release'],array['oracle','ace','aie','chain_adapter','pallet']::text[],'D2',false,array['blockchain_crypto','security_privacy']::text[],false,'oracle_assurance',26,'{}'),
('CG-027','ai_ml','AI/ML TEVV','Model cards, data lineage, intended/excluded use, precision/recall, calibration, drift, bias, adversarial tests and rollback are complete.',array['test','staged','production','maintained'],array['module','algorithm','protocol','release'],array['ace','aie','agent_fabric','oracle']::text[],'D2',false,array['ai_ml_tevv','security_privacy']::text[],false,'model_tevv',27,'{}'),
('CG-028','ai_ml','Algorithm Registry','Every operational algorithm has stable ID, version, public contract digest, implementation binding, authority ceiling and evaluation evidence.',array['test','staged','production','maintained'],array['module','algorithm','protocol','release'],array['ace','aie','oracle','fingerprint','rights_graph','dla','lex','agent_fabric']::text[],'D2',false,array['ai_ml_tevv']::text[],true,'algorithm_registry',28,'{}'),
('CG-029','rights','Rights / IP / Chain of Title','Ownership claims, contributor rights, provenance, evidence, license authority and protected/public boundaries are supportable.',array['staged','production','maintained'],array['module','platform','protocol','release'],array['rights_graph','dla','lex','dispute','settlement','ade','treasury']::text[],'D3',true,array['ip_licensing','legal_regulatory']::text[],false,'rights_chain_of_title',29,'{}'),
('CG-030','licensing','DLA State Machine','DLA issuance, permissions, conflict detection, suspension, expiry, supersession, revocation and verification are tested.',array['test','staged','production','maintained'],array['module','platform','protocol','release'],array['dla']::text[],'D3',true,array['ip_licensing','legal_regulatory','security_privacy']::text[],false,'dla_state_machine',30,'{}'),
('CG-031','market','LEX Market Integrity','Eligibility, listing, RFQ/quote, escrow/settlement handoff, rights checks, disclosure and abuse controls are tested.',array['staged','production','maintained'],array['module','platform','protocol','release'],array['lex']::text[],'D3',true,array['ip_licensing','legal_regulatory','finance_tax_treasury','accessibility_consumer']::text[],false,'lex_market_integrity',31,'{}'),
('CG-032','remedies','Dispute / Remedies / Appeals','Hold, evidence, review, decision, remedy, appeal, restoration and correction-without-erasure flows are tested.',array['test','staged','production','maintained'],array['module','platform','protocol','release'],array['dispute']::text[],'D3',true,array['legal_regulatory','ip_licensing']::text[],false,'dispute_remedies',32,'{}'),
('CG-033','commerce','Commerce & Entitlement','Order, credits/payment, agreement, license grant, entitlement, delivery, refund/dispute and reconciliation are end-to-end tested.',array['staged','production','maintained'],array['module','platform','protocol','release'],array['settlement','lex','dla','api_mcp']::text[],'D3',true,array['finance_tax_treasury','legal_regulatory','ip_licensing']::text[],false,'commerce_entitlement_e2e',33,'{}'),
('CG-034','commerce','Pricing & Monetization','Pricing, credit equivalents, fees, usage metering, disclosures, margin/cost model and entitlement value are approved and testable.',array['staged','production','maintained'],array['module','platform','protocol','release'],array['lex','dla','settlement','api_mcp']::text[],'D3',true,array['finance_tax_treasury','accessibility_consumer']::text[],false,'commercial_manifest',34,'{}'),
('CG-035','finance','Finance / Tax / Treasury','Money flow, royalty/split conservation, tax treatment, reconciliation, reserves and treasury authority are reviewed.',array['staged','production','maintained'],array['module','protocol','release'],array['treasury','settlement','ade','lex']::text[],'D3',true,array['finance_tax_treasury','legal_regulatory']::text[],false,'finance_tax_treasury_review',35,'{}'),
('CG-036','economics','Tokenomics & Economic Simulation','Supply, vesting, fees, staking, concentration, treasury runway, attacks and creator economics are reproducibly simulated.',array['test','staged','production','maintained'],array['module','protocol','release'],array['treasury','settlement','governance','chain_adapter']::text[],'D3',true,array['finance_tax_treasury','blockchain_crypto','legal_regulatory']::text[],false,'tokenomics_simulation',36,'{}'),
('CG-037','legal','Token / Crypto Legal Gate','Current securities, commodities, AML/KYC, sanctions, money transmission, tax, consumer, custody and marketing analysis is documented.',array['production','maintained'],array['module','protocol','release'],array['treasury','settlement','governance','chain_adapter']::text[],'D3',true,array['legal_regulatory','finance_tax_treasury','blockchain_crypto']::text[],false,'production_crypto_legal_packet',37,'{}'),
('CG-038','custody','Treasury / Multisig / Key Custody','Production signing and treasury keys use hardened custody, multisig/timelock, rotation, recovery and independent control.',array['production','maintained'],array['module','protocol','release'],array['treasury','settlement','governance','identity']::text[],'D3',true,array['security_privacy','blockchain_crypto','finance_tax_treasury']::text[],false,'production_key_custody',38,'{}'),
('CG-039','chain','Polkadot SDK Testnet','Rust/Polkadot SDK test chain, validators, runtime/pallet tests, recovery, finality and explorer/readback evidence exist.',array['test','staged','production','maintained'],array['module','protocol','release'],array['chain_adapter','pallet']::text[],'D2',false,array['blockchain_crypto','security_privacy','operations_sre']::text[],false,'polkadot_testnet',39,'{}'),
('CG-040','chain','EVM Anchor Adapter','Solidity test contracts, fuzz/invariant/static analysis, deployment and independent EVM testnet readback are certified.',array['test','staged','production','maintained'],array['module','protocol','release'],array['chain_adapter']::text[],'D2',false,array['blockchain_crypto','security_privacy']::text[],false,'evm_testnet_anchor',40,'{}'),
('CG-041','chain','Chain Readback & Finality','Anchors are independently readable; confirmations/finality, reorg policy, replay protection and chain-ID binding are tested.',array['test','staged','production','maintained'],array['module','protocol','release'],array['chain_adapter','pallet']::text[],'D2',false,array['blockchain_crypto']::text[],false,'chain_finality_readback',41,'{}'),
('CG-042','chain','Cross-Chain / Bridge Gate','Any bridge or cross-chain value flow has a separate threat model, custody model, exit strategy and adversarial certification.',array['production','maintained'],array['module','protocol','release'],array['chain_adapter']::text[],'D3',true,array['blockchain_crypto','security_privacy','legal_regulatory']::text[],false,'bridge_certification',42,'{}'),
('CG-043','privacy','ZKX / Privacy Proof Gate','Proof scheme, circuits, witness handling, verifier correctness, trusted-setup risk and privacy properties are evaluated.',array['test','staged','production','maintained'],array['module','protocol','release'],array['zkx','identity','credentials','pallet']::text[],'D2',false,array['blockchain_crypto','security_privacy']::text[],false,'zkx_assurance',43,'{}'),
('CG-044','integration','Virality Music Integration','Real VM pilot assets prove identity, fingerprint, rights, DLA/DAIL, Credits/test settlement, verification and version correction.',array['staged','production','maintained'],array['platform','protocol','release'],array[]::text[],'D3',true,array['ip_licensing','finance_tax_treasury','security_privacy']::text[],false,'vm_end_to_end_pilot',44,'{}'),
('CG-045','integration','KJV/Sermon Toolkit Integration','Real KJV/Sermon assets prove rights distinction, fingerprint, DLA/DAIL, entitlement, verification and commerce boundaries.',array['staged','production','maintained'],array['platform','protocol','release'],array[]::text[],'D3',true,array['ip_licensing','legal_regulatory','security_privacy']::text[],false,'kjv_end_to_end_pilot',45,'{}'),
('CG-046','integration','Third-Party Creator Beta','Gated creator identity, rights assertions, evidence, conflict handling, DLA, commerce and dispute flows are proven.',array['production','maintained'],array['protocol','release','platform'],array[]::text[],'D3',true,array['ip_licensing','legal_regulatory','security_privacy','accessibility_consumer']::text[],false,'creator_beta',46,'{}'),
('CG-047','consumer','Accessibility & Consumer Protection','Customer-facing flows meet accessibility requirements, truthful disclosures, cancellation/refund clarity and anti-dark-pattern review.',array['staged','production','maintained'],array['platform','protocol','release'],array[]::text[],'D3',true,array['accessibility_consumer','legal_regulatory']::text[],false,'accessibility_consumer_review',47,'{}'),
('CG-048','culture','CIE / Cultural Governance','Cultural Imprint Engine rules, protected identities, canon and culturally consequential decisions are separately governed.',array['staged','production','maintained'],array['module','platform','protocol','release'],array['rights_graph','dla','lex','governance','agent_fabric','api_mcp']::text[],'D3',true,array['cultural_governance','ip_licensing']::text[],false,'cie_governance',48,'{}'),
('CG-049','governance','Quorum & Separation of Duties','Originator exclusion, snapshot binding, specialist activation, quorum, fail-closed denial and rollback authority are proven.',array['test','staged','production','maintained'],array['module','protocol','release'],array['governance','agent_fabric','api_mcp']::text[],'D2',false,array['security_privacy']::text[],false,'governance_quorum',49,'{}'),
('CG-050','governance','Founder / Reserved Human Approval','D3 actions carry explicit non-reusable authorized human approval; agent quorum cannot substitute.',array['production','maintained'],array['protocol','release'],array[]::text[],'D3',true,array['legal_regulatory','security_privacy']::text[],false,'reserved_human_approval',50,'{}'),
('CG-051','documentation','Documentation & Public/Private Boundary','Mintlify/GitHub docs reflect actual state; restricted algorithms, evidence, secrets and keys remain out of public surfaces.',array['prototype','test','staged','production','maintained'],array['module','platform','protocol','release','paper'],array[]::text[],'D2',false,array['security_privacy','ip_licensing']::text[],false,'docs_state_and_boundary',51,'{}'),
('CG-052','continuity','Institutional Continuity & Replicability','Git source, migrations, manifests, Drive masters, Supabase runtime records, handoff and reproducible bootstrap are synchronized.',array['test','staged','production','maintained'],array['module','platform','protocol','agent','algorithm','oracle','release','paper'],array[]::text[],'D2',false,array['operations_sre']::text[],false,'institutional_continuity',52,'{}'),
('CG-053','operations','Incident & Runbook Readiness','Known failures have runbooks, severity, owner, pause/degraded mode, recovery, evidence and post-incident review.',array['staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array['operations_sre','security_privacy']::text[],false,'incident_runbooks',53,'{}'),
('CG-054','portability','Vendor Exit & Portability','Provider dependency, export format, recovery path, open standards/adapters and replacement strategy are tested.',array['staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array['operations_sre','security_privacy']::text[],false,'vendor_exit',54,'{}'),
('CG-055','claims','Public Claims / Legal State','Public claims match verified deployment, IP/legal status and measured evidence; target/research is labeled correctly.',array['staged','production','maintained'],array['platform','protocol','release','paper'],array[]::text[],'D3',true,array['legal_regulatory','accessibility_consumer','ip_licensing']::text[],false,'public_claims_review',55,'{}'),
('CG-056','release','Canary & Independent Readback','Release passes canary, independent readback, rollback verification and post-release monitoring before promotion.',array['staged','production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D2',false,array['operations_sre','security_privacy']::text[],false,'canary_readback',56,'{}'),
('CG-057','chain','Mainnet Readiness','Real-value/mainnet activation requires legal, security, custody, economics, operations, governance and public-disclosure gates simultaneously PASS.',array['production','maintained'],array['protocol','release'],array[]::text[],'D3',true,array['blockchain_crypto','legal_regulatory','finance_tax_treasury','security_privacy','operations_sre']::text[],false,'mainnet_gate_packet',57,'{}'),
('CG-058','release','Production Release Evidence','Production status requires exact artifact SHA/version, deployment evidence, tests, approvals, readback, monitoring, rollback and DAIL release event.',array['production','maintained'],array['module','platform','protocol','release'],array[]::text[],'D3',true,array['security_privacy','operations_sre']::text[],false,'production_release_packet',58,'{}')
on conflict (gate_id) do update set
 gate_family=excluded.gate_family, canonical_name=excluded.canonical_name, description=excluded.description,
 required_for_stages=excluded.required_for_stages, scope_types=excluded.scope_types,
 applies_to_module_classes=excluded.applies_to_module_classes, risk_class=excluded.risk_class,
 d3_human_reserved=excluded.d3_human_reserved, specialist_domains=excluded.specialist_domains,
 auto_evaluable=excluded.auto_evaluable, evaluation_method=excluded.evaluation_method,
 sequence_no=excluded.sequence_no, metadata=excluded.metadata, updated_at=now();

insert into chlom_runtime.construction_tracks(scope_type,scope_id,current_stage,target_stage,overall_state,owner_agent_id,evidence)
select 'module',m.module_id,m.lifecycle_state,
 case m.lifecycle_state when 'reconciled' then 'specified' when 'specified' then 'prototype' when 'prototype' then 'test' when 'test' then 'staged' when 'staged' then 'production' when 'production' then 'maintained' else 'maintained' end,
 'building','ct.chlom.agent.orchestrator',jsonb_build_object('seed','module_lifecycle','module_class',m.module_class)
from chlom_runtime.modules m
on conflict (scope_type,scope_id,target_stage) do update set current_stage=excluded.current_stage,owner_agent_id=excluded.owner_agent_id,evidence=excluded.evidence,updated_at=now();

insert into chlom_runtime.construction_tracks(scope_type,scope_id,current_stage,target_stage,overall_state,owner_agent_id,evidence)
values
('protocol','ct.framework.chlom','controlled_test','staged','building','ct.chlom.agent.orchestrator',jsonb_build_object('purpose','CHLOM metaprotocol staged-construction hard gate')),
('platform','ct.platform.virality-music','controlled_test','staged','building','ct.chlom.agent.vm-integration',jsonb_build_object('pilot','customer_zero')),
('platform','ct.platform.kjv-sermon-toolkit','controlled_test','staged','building','ct.chlom.agent.kjv-integration',jsonb_build_object('pilot','customer_one'))
on conflict (scope_type,scope_id,target_stage) do update set overall_state='building',owner_agent_id=excluded.owner_agent_id,evidence=excluded.evidence,updated_at=now();