-- PentaContext v1.1 production promotion. Applied to production 20260826232536.
create or replace function public.penta_context_health_v1() returns jsonb language sql stable set search_path=pg_catalog,public as $$
select jsonb_build_object('system_key','penta.context','version','1.1.0','state',case when q.dead_letter>0 then 'degraded' when q.pending>1000 then 'degraded' when r.active_records>0 then 'healthy' else 'ready_empty' end,'active_records',r.active_records,'expired_pending_tombstone',r.expired_pending,'restricted_records',r.restricted_records,'latest_observed_at',r.latest_observed_at,'queue_pending',q.pending,'queue_processing',q.processing,'queue_retry',q.retry,'queue_dead_letter',q.dead_letter,'oldest_pending_at',q.oldest_pending_at,'ingest_worker_schedule','* * * * *','maintenance_schedule','*/15 * * * *','checked_at',now(),'authority_created',false)
from (select count(*) filter(where tombstoned_at is null and (expires_at is null or expires_at>now())) active_records,count(*) filter(where tombstoned_at is null and expires_at<=now()) expired_pending,count(*) filter(where classification='restricted' and tombstoned_at is null) restricted_records,max(observed_at) filter(where tombstoned_at is null) latest_observed_at from public.penta_context_records_v1) r
cross join (select count(*) filter(where status in('queued','retry')) pending,count(*) filter(where status='processing') processing,count(*) filter(where status='retry') retry,count(*) filter(where status='dead_letter') dead_letter,min(created_at) filter(where status in('queued','retry')) oldest_pending_at from public.penta_context_ingest_queue_v1) q; $$;
revoke execute on function public.penta_context_health_v1() from public,anon,authenticated; grant execute on function public.penta_context_health_v1() to service_role;

do $$ declare v_evidence jsonb; v_sha text; begin
 v_evidence:=jsonb_build_object('system_key','penta.context','canonical_name','PentaContext','version','1.1.0','promotion','PRODUCTION','automation',jsonb_build_object('durable_ingest_queue',true,'worker_schedule','* * * * *','maintenance_schedule','*/15 * * * *','batch_size',50,'idempotent_enqueue',true,'retry_backoff','exponential_capped_1h','dead_letter',true,'redaction_before_queue_persistence',true,'arbitrary_external_fetching',false,'acquisition_boundary','PentaFetch/PentaIngest/PentaSync provider adapters'),'queue_canary',jsonb_build_object('job_id','d7b68b25-af01-4cab-8207-c91051397646','context_id','f9652520-aac3-4ecb-99cb-74da8a025c65','source_id','441d78be-e139-49dd-b967-b9693fe5cba1','fingerprint_sha256','e2cab0771d685af3258ff7cd040838aa64a8e86c123cd3b7ba7475d5394beb50','query_output_sha256','0caae31cbbdd52f8b925cf342ac87c3772796876c170c04341f4dd4f79a363b0','enqueue_pass',true,'duplicate_enqueue_inserted',false,'redacted_at_rest',true,'metadata_redacted_at_rest',true,'worker_completed',true,'attempt_count',1,'retry_count',0,'dead_letter_count',0,'retrieval_pass',true,'authority_created',false),'edge',jsonb_build_object('slug','penta-context','deployment_id','e111f3eb-a3c7-488e-92b9-f55d3e63bbce','version',2,'status','ACTIVE','artifact_sha256','4b8902e1d639e9a80d3e9f028cac2bb26662658ff5a547af210514f76fc3d212','custom_service_role_auth',true,'allowed_actions',jsonb_build_array('health','queue_status','query','ingest','enqueue')),'authority',jsonb_build_object('ceiling','D2','context_is_authority',false,'authority_created',false,'provider_write',false,'money_movement',false,'d3_effect',false),'observed_at',now());
 v_sha:=encode(extensions.digest(v_evidence::text,'sha256'),'hex');
 insert into public.penta_system_production_receipts_v1(system_key,system_version,canary_key,runtime_ref,passed,evidence,evidence_sha256,authority_ceiling,provider_write,money_movement,d3_effect) values('penta.context','1.1.0','penta-context-automation-canary-20260826','edge:penta-context@2;rpc:public.penta_context_query_v1;queue:public.penta_context_ingest_queue_v1',true,v_evidence,v_sha,'D2',false,false,false) on conflict(system_key,system_version,canary_key) do update set runtime_ref=excluded.runtime_ref,passed=excluded.passed,evidence=excluded.evidence,evidence_sha256=excluded.evidence_sha256,authority_ceiling=excluded.authority_ceiling,provider_write=false,money_movement=false,d3_effect=false,observed_at=now();
 update public.penta_system_registry set maturity='production',version='1.1.0',runtime_ref='edge:penta-context@2;rpc:public.penta_context_query_v1;queue:public.penta_context_ingest_queue_v1',last_verified_at=now(),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('operational_state','PRODUCTION','automated',true,'automated_ingestion',true,'edge_version',2,'edge_artifact_sha256','4b8902e1d639e9a80d3e9f028cac2bb26662658ff5a547af210514f76fc3d212','production_receipt_sha256',v_sha,'production_canary_pending',false,'source_control_sync_pending',true,'production_promoted_at',now()),updated_at=now() where system_key='penta.context';
end $$;
